// Vymova — js/features/speak-lang.ts
// Shared "speak text in the right language's voice, falling back to
// English" helper. Kept in its own small module (rather than living in
// card-actions.ts) so that card-front-text.tsx — a presentational component
// rendered for every card flip — doesn't need to pull in card-actions.ts's
// much heavier transitive import graph (storage, game, combo, notes, etc).
import {
  getSelectedUkVoice,
  getSelectedEsVoice,
  getSelectedFrVoice,
  getSelectedItVoice,
  getSelectedPtVoice,
  getSelectedDeVoice,
  getSelectedHeVoice,
  getSelectedArVoice,
  getSelectedPlVoice,
  getSelectedZhVoice,
  getSelectedElVoice,
  getSelectedJaVoice,
  getSelectedTrVoice,
  getSelectedNlVoice,
  getSelectedViVoice,
  getSelectedHiVoice,
  getSelectedBnVoice,
  getSelectedIdVoice,
  getSelectedPcmVoice,
  getSelectedKoVoice,
  getSelectedFaVoice,
  getSelectedSwVoice,
  getSelectedMsVoice,
  getSelectedThVoice,
  getSelectedAzVoice,
  getSelectedRoVoice,
  getSelectedHuVoice,
  getSelectedCsVoice,
  getSelectedKkVoice,
  getSelectedSvVoice,
  getSelectedKaVoice,
  getSelectedHrVoice,
  getSelectedSrVoice,
  getSelectedBsVoice,
  getSelectedBgVoice,
  getSelectedSkVoice,
  getSelectedHyVoice,
  getSelectedDaVoice,
  getSelectedFiVoice,
  getSelectedNoVoice,
  getSelectedLaVoice,
  getSelectedLtVoice,
  getSelectedLvVoice,
  getSelectedEtVoice,
  getSelectedSlVoice,
  getSelectedMkVoice,
  getSelectedSqVoice,
  getSelectedIsVoice,
  getSelectedCyVoice,
  getSelectedGaVoice,
  getSelectedTlVoice,
  getSelectedMnVoice,
  getSelectedUzVoice,
  getSelectedAmVoice,
  getSelectedEoVoice,
  getSelectedTaVoice,
  getSelectedPaVoice,
  getSelectedZuVoice,
  getSelectedAfVoice,
  getSelectedKyVoice,
  getSelectedTgVoice,
  getSelectedTkVoice,
  getSelectedUgVoice,
  getSelectedEuVoice,
  getSelectedCaVoice,
  getSelectedGlVoice,
  getSelectedMtVoice,
  getSelectedLbVoice,
  getSelectedHtVoice,
  getSelectedBoVoice,
  getSelectedMyVoice,
  getSelectedKmVoice,
  getSelectedLoVoice,
  getSelectedNeVoice,
  getSelectedSiVoice,
  getSelectedUrVoice,
  getSelectedTeVoice,
  getSelectedMlVoice,
  getSelectedKnVoice,
  getSelectedMrVoice,
  getSelectedGuVoice,
  getSelectedOrVoice,
  getSelectedAsVoice,
  getSelectedSdVoice,
  getSelectedPsVoice,
  getSelectedSoVoice,
  getSelectedHaVoice,
  getSelectedYoVoice,
  getSelectedIgVoice,
  getSelectedTiVoice,
  getSelectedWoVoice,
  getSelectedMgVoice,
  getSelectedXhVoice,
  getSelectedSnVoice,
  getSelectedNyVoice,
  getSelectedFjVoice,
  getSelectedSmVoice,
  getSelectedToVoice,
  getSelectedMiVoice,
  getSelectedHawVoice,
  getSelectedJvVoice,
  getSelectedSuVoice,
  getSelectedGdVoice,
  getSelectedBrVoice,
  getSelectedKwVoice,
  getSelectedGvVoice,
  getSelectedFoVoice,
  getSelectedOcVoice,
  getSelectedCoVoice,
  getSelectedScVoice,
  getSelectedFyVoice,
  getSelectedYiVoice,
  getSelectedLadVoice,
  getSelectedQuVoice,
  getSelectedGnVoice,
  getSelectedAyVoice,
  getSelectedDzVoice,
  getSelectedDvVoice,
  getSelectedTetVoice,
  getSelectedBeVoice,
  getSelectedQyaVoice,
  getSelectedSjnVoice,
  getSelectedKuVoice,
  getSelectedOmVoice,
  getSelectedLnVoice,
  getSelectedBhoVoice,
  getSelectedCebVoice,
  getSelectedRmVoice,
  getSelectedTyVoice,
  getSelectedChVoice,
  getSelectedMhVoice,
  getSelectedPauVoice,
  getSelectedNahVoice,
  getSelectedNvVoice,
  getSelectedTlhVoice,
  getSelectedValVoice,
  getSelectedDthVoice,
} from './voice.tsx';
import { speak, _speakWithLang } from './speech.ts';
import { latinizeForSpeech } from './latinize.ts';
import {
  isTargetLang,
  langConfig,
  LATIN_TRANSLIT_LANGS,
  NATIVE_LATIN_LANGS,
  type TargetLang,
  type Code,
} from '../mode-utils.ts';

export const VOICE_GETTERS: Record<TargetLang, () => SpeechSynthesisVoice | null> = {
  es: getSelectedEsVoice,
  fr: getSelectedFrVoice,
  it: getSelectedItVoice,
  pt: getSelectedPtVoice,
  de: getSelectedDeVoice,
  he: getSelectedHeVoice,
  ar: getSelectedArVoice,
  pl: getSelectedPlVoice,
  zh: getSelectedZhVoice,
  el: getSelectedElVoice,
  ja: getSelectedJaVoice,
  tr: getSelectedTrVoice,
  nl: getSelectedNlVoice,
  vi: getSelectedViVoice,
  hi: getSelectedHiVoice,
  bn: getSelectedBnVoice,
  id: getSelectedIdVoice,
  pcm: getSelectedPcmVoice,
  ko: getSelectedKoVoice,
  fa: getSelectedFaVoice,
  sw: getSelectedSwVoice,
  ms: getSelectedMsVoice,
  th: getSelectedThVoice,
  az: getSelectedAzVoice,
  ro: getSelectedRoVoice,
  hu: getSelectedHuVoice,
  cs: getSelectedCsVoice,
  kk: getSelectedKkVoice,
  sv: getSelectedSvVoice,
  ka: getSelectedKaVoice,
  hr: getSelectedHrVoice,
  sr: getSelectedSrVoice,
  bs: getSelectedBsVoice,
  bg: getSelectedBgVoice,
  sk: getSelectedSkVoice,
  hy: getSelectedHyVoice,
  da: getSelectedDaVoice,
  fi: getSelectedFiVoice,
  no: getSelectedNoVoice,
  la: getSelectedLaVoice,
  lt: getSelectedLtVoice,
  lv: getSelectedLvVoice,
  et: getSelectedEtVoice,
  sl: getSelectedSlVoice,
  mk: getSelectedMkVoice,
  sq: getSelectedSqVoice,
  is: getSelectedIsVoice,
  cy: getSelectedCyVoice,
  ga: getSelectedGaVoice,
  tl: getSelectedTlVoice,
  mn: getSelectedMnVoice,
  uz: getSelectedUzVoice,
  am: getSelectedAmVoice,
  eo: getSelectedEoVoice,
  ta: getSelectedTaVoice,
  pa: getSelectedPaVoice,
  zu: getSelectedZuVoice,
  af: getSelectedAfVoice,
  ky: getSelectedKyVoice,
  tg: getSelectedTgVoice,
  tk: getSelectedTkVoice,
  ug: getSelectedUgVoice,
  eu: getSelectedEuVoice,
  ca: getSelectedCaVoice,
  gl: getSelectedGlVoice,
  mt: getSelectedMtVoice,
  lb: getSelectedLbVoice,
  ht: getSelectedHtVoice,
  bo: getSelectedBoVoice,
  my: getSelectedMyVoice,
  km: getSelectedKmVoice,
  lo: getSelectedLoVoice,
  ne: getSelectedNeVoice,
  si: getSelectedSiVoice,
  ur: getSelectedUrVoice,
  te: getSelectedTeVoice,
  ml: getSelectedMlVoice,
  kn: getSelectedKnVoice,
  mr: getSelectedMrVoice,
  gu: getSelectedGuVoice,
  or: getSelectedOrVoice,
  as: getSelectedAsVoice,
  sd: getSelectedSdVoice,
  ps: getSelectedPsVoice,
  so: getSelectedSoVoice,
  ha: getSelectedHaVoice,
  yo: getSelectedYoVoice,
  ig: getSelectedIgVoice,
  ti: getSelectedTiVoice,
  wo: getSelectedWoVoice,
  mg: getSelectedMgVoice,
  xh: getSelectedXhVoice,
  sn: getSelectedSnVoice,
  ny: getSelectedNyVoice,
  fj: getSelectedFjVoice,
  sm: getSelectedSmVoice,
  to: getSelectedToVoice,
  mi: getSelectedMiVoice,
  haw: getSelectedHawVoice,
  jv: getSelectedJvVoice,
  su: getSelectedSuVoice,
  gd: getSelectedGdVoice,
  br: getSelectedBrVoice,
  kw: getSelectedKwVoice,
  gv: getSelectedGvVoice,
  fo: getSelectedFoVoice,
  oc: getSelectedOcVoice,
  co: getSelectedCoVoice,
  sc: getSelectedScVoice,
  fy: getSelectedFyVoice,
  yi: getSelectedYiVoice,
  lad: getSelectedLadVoice,
  qu: getSelectedQuVoice,
  gn: getSelectedGnVoice,
  ay: getSelectedAyVoice,
  dz: getSelectedDzVoice,
  dv: getSelectedDvVoice,
  tet: getSelectedTetVoice,
  be: getSelectedBeVoice,
  qya: getSelectedQyaVoice,
  sjn: getSelectedSjnVoice,
  ku: getSelectedKuVoice,
  om: getSelectedOmVoice,
  ln: getSelectedLnVoice,
  bho: getSelectedBhoVoice,
  ceb: getSelectedCebVoice,
  rm: getSelectedRmVoice,
  ty: getSelectedTyVoice,
  ch: getSelectedChVoice,
  mh: getSelectedMhVoice,
  pau: getSelectedPauVoice,
  nah: getSelectedNahVoice,
  nv: getSelectedNvVoice,
  tlh: getSelectedTlhVoice,
  val: getSelectedValVoice,
  dth: getSelectedDthVoice,
};

export function speakForCode(
  code: Code,
  text: string,
  fallbackEnText: string,
  btn: HTMLElement | null,
  translit?: string,
): void {
  // Reset on every call (not just on the translit branch) so a button that
  // previously used the approximate-pronunciation fallback doesn't keep
  // showing that hint once a real voice becomes available (e.g. after the
  // user installs a language pack) or for a different word on the same card.
  btn?.classList.remove('approx');
  if (isTargetLang(code)) {
    const cfg = langConfig(code);
    if (text && VOICE_GETTERS[code]()) {
      _speakWithLang(text, cfg.voiceLocale, btn);
      return;
    }
    if (translit && LATIN_TRANSLIT_LANGS.has(code)) {
      btn?.classList.add('approx');
      speak(translit, btn);
      return;
    }
    // NATIVE_LATIN_LANGS have no separate Entry[2] translit field — the
    // target-language `text` itself (word or full sentence, whichever the
    // caller passed) is already plain Latin script, just possibly with
    // diacritics an English voice mishandles. latinizeForSpeech() strips
    // those live, working for words and sentences alike with no extra
    // per-word data needed.
    if (text && NATIVE_LATIN_LANGS.has(code)) {
      btn?.classList.add('approx');
      speak(latinizeForSpeech(text, code), btn);
      return;
    }
    speak(fallbackEnText, btn);
    return;
  }
  if (code === 'ua') {
    if (text && getSelectedUkVoice()) {
      _speakWithLang(text, 'uk-UA', btn);
      return;
    }
    speak(fallbackEnText, btn);
    return;
  }
  speak(text || fallbackEnText, btn);
}
