// Vymova — js/features/idioms-loader.ts
// Lazy per-language loader for per-language idiom data (formerly data/idioms.ts's IDIOMS_BY_LANG), generated by
// scripts/gen-lang-loader.js (scans data/idioms-data/) — mirrors mode-utils.ts's
// TABLES/LANG_LOADERS pattern for word data. Only the learner's actual
// language(s) get downloaded instead of every language's data eagerly (see
// docs/architecture-assessment.md p.6). Regenerate (don't hand-edit the
// loader map) after adding or removing a data/idioms-data/idioms_xx.ts file.
import type { Idiom } from '../../data/idioms.ts';

const CACHE: Partial<Record<string, Idiom[]>> = {};
const LOADING: Partial<Record<string, Promise<void>>> = {};

const LOADERS: Partial<Record<string, () => Promise<Idiom[]>>> = {
  af: () =>
    import('../../data/idioms-data/idioms_af.ts').then((m) => m.IDIOMS_AF),
  am: () =>
    import('../../data/idioms-data/idioms_am.ts').then((m) => m.IDIOMS_AM),
  ar: () =>
    import('../../data/idioms-data/idioms_ar.ts').then((m) => m.IDIOMS_AR),
  as: () =>
    import('../../data/idioms-data/idioms_as.ts').then((m) => m.IDIOMS_AS),
  ay: () =>
    import('../../data/idioms-data/idioms_ay.ts').then((m) => m.IDIOMS_AY),
  az: () =>
    import('../../data/idioms-data/idioms_az.ts').then((m) => m.IDIOMS_AZ),
  be: () =>
    import('../../data/idioms-data/idioms_be.ts').then((m) => m.IDIOMS_BE),
  bg: () =>
    import('../../data/idioms-data/idioms_bg.ts').then((m) => m.IDIOMS_BG),
  bho: () =>
    import('../../data/idioms-data/idioms_bho.ts').then((m) => m.IDIOMS_BHO),
  bn: () =>
    import('../../data/idioms-data/idioms_bn.ts').then((m) => m.IDIOMS_BN),
  bo: () =>
    import('../../data/idioms-data/idioms_bo.ts').then((m) => m.IDIOMS_BO),
  br: () =>
    import('../../data/idioms-data/idioms_br.ts').then((m) => m.IDIOMS_BR),
  bs: () =>
    import('../../data/idioms-data/idioms_bs.ts').then((m) => m.IDIOMS_BS),
  ca: () =>
    import('../../data/idioms-data/idioms_ca.ts').then((m) => m.IDIOMS_CA),
  ceb: () =>
    import('../../data/idioms-data/idioms_ceb.ts').then((m) => m.IDIOMS_CEB),
  ch: () =>
    import('../../data/idioms-data/idioms_ch.ts').then((m) => m.IDIOMS_CH),
  co: () =>
    import('../../data/idioms-data/idioms_co.ts').then((m) => m.IDIOMS_CO),
  cs: () =>
    import('../../data/idioms-data/idioms_cs.ts').then((m) => m.IDIOMS_CS),
  cy: () =>
    import('../../data/idioms-data/idioms_cy.ts').then((m) => m.IDIOMS_CY),
  da: () =>
    import('../../data/idioms-data/idioms_da.ts').then((m) => m.IDIOMS_DA),
  de: () =>
    import('../../data/idioms-data/idioms_de.ts').then((m) => m.IDIOMS_DE),
  dth: () =>
    import('../../data/idioms-data/idioms_dth.ts').then((m) => m.IDIOMS_DTH),
  dv: () =>
    import('../../data/idioms-data/idioms_dv.ts').then((m) => m.IDIOMS_DV),
  dz: () =>
    import('../../data/idioms-data/idioms_dz.ts').then((m) => m.IDIOMS_DZ),
  el: () =>
    import('../../data/idioms-data/idioms_el.ts').then((m) => m.IDIOMS_EL),
  en: () =>
    import('../../data/idioms-data/idioms_en.ts').then((m) => m.IDIOMS_EN),
  eo: () =>
    import('../../data/idioms-data/idioms_eo.ts').then((m) => m.IDIOMS_EO),
  es: () =>
    import('../../data/idioms-data/idioms_es.ts').then((m) => m.IDIOMS_ES),
  et: () =>
    import('../../data/idioms-data/idioms_et.ts').then((m) => m.IDIOMS_ET),
  eu: () =>
    import('../../data/idioms-data/idioms_eu.ts').then((m) => m.IDIOMS_EU),
  fa: () =>
    import('../../data/idioms-data/idioms_fa.ts').then((m) => m.IDIOMS_FA),
  fi: () =>
    import('../../data/idioms-data/idioms_fi.ts').then((m) => m.IDIOMS_FI),
  fj: () =>
    import('../../data/idioms-data/idioms_fj.ts').then((m) => m.IDIOMS_FJ),
  fo: () =>
    import('../../data/idioms-data/idioms_fo.ts').then((m) => m.IDIOMS_FO),
  fr: () =>
    import('../../data/idioms-data/idioms_fr.ts').then((m) => m.IDIOMS_FR),
  fy: () =>
    import('../../data/idioms-data/idioms_fy.ts').then((m) => m.IDIOMS_FY),
  ga: () =>
    import('../../data/idioms-data/idioms_ga.ts').then((m) => m.IDIOMS_GA),
  gd: () =>
    import('../../data/idioms-data/idioms_gd.ts').then((m) => m.IDIOMS_GD),
  gl: () =>
    import('../../data/idioms-data/idioms_gl.ts').then((m) => m.IDIOMS_GL),
  gn: () =>
    import('../../data/idioms-data/idioms_gn.ts').then((m) => m.IDIOMS_GN),
  gu: () =>
    import('../../data/idioms-data/idioms_gu.ts').then((m) => m.IDIOMS_GU),
  gv: () =>
    import('../../data/idioms-data/idioms_gv.ts').then((m) => m.IDIOMS_GV),
  ha: () =>
    import('../../data/idioms-data/idioms_ha.ts').then((m) => m.IDIOMS_HA),
  haw: () =>
    import('../../data/idioms-data/idioms_haw.ts').then((m) => m.IDIOMS_HAW),
  he: () =>
    import('../../data/idioms-data/idioms_he.ts').then((m) => m.IDIOMS_HE),
  hi: () =>
    import('../../data/idioms-data/idioms_hi.ts').then((m) => m.IDIOMS_HI),
  hr: () =>
    import('../../data/idioms-data/idioms_hr.ts').then((m) => m.IDIOMS_HR),
  ht: () =>
    import('../../data/idioms-data/idioms_ht.ts').then((m) => m.IDIOMS_HT),
  hu: () =>
    import('../../data/idioms-data/idioms_hu.ts').then((m) => m.IDIOMS_HU),
  hy: () =>
    import('../../data/idioms-data/idioms_hy.ts').then((m) => m.IDIOMS_HY),
  id: () =>
    import('../../data/idioms-data/idioms_id.ts').then((m) => m.IDIOMS_ID),
  ig: () =>
    import('../../data/idioms-data/idioms_ig.ts').then((m) => m.IDIOMS_IG),
  is: () =>
    import('../../data/idioms-data/idioms_is.ts').then((m) => m.IDIOMS_IS),
  it: () =>
    import('../../data/idioms-data/idioms_it.ts').then((m) => m.IDIOMS_IT),
  ja: () =>
    import('../../data/idioms-data/idioms_ja.ts').then((m) => m.IDIOMS_JA),
  jv: () =>
    import('../../data/idioms-data/idioms_jv.ts').then((m) => m.IDIOMS_JV),
  ka: () =>
    import('../../data/idioms-data/idioms_ka.ts').then((m) => m.IDIOMS_KA),
  kk: () =>
    import('../../data/idioms-data/idioms_kk.ts').then((m) => m.IDIOMS_KK),
  km: () =>
    import('../../data/idioms-data/idioms_km.ts').then((m) => m.IDIOMS_KM),
  kn: () =>
    import('../../data/idioms-data/idioms_kn.ts').then((m) => m.IDIOMS_KN),
  ko: () =>
    import('../../data/idioms-data/idioms_ko.ts').then((m) => m.IDIOMS_KO),
  ku: () =>
    import('../../data/idioms-data/idioms_ku.ts').then((m) => m.IDIOMS_KU),
  kw: () =>
    import('../../data/idioms-data/idioms_kw.ts').then((m) => m.IDIOMS_KW),
  ky: () =>
    import('../../data/idioms-data/idioms_ky.ts').then((m) => m.IDIOMS_KY),
  la: () =>
    import('../../data/idioms-data/idioms_la.ts').then((m) => m.IDIOMS_LA),
  lad: () =>
    import('../../data/idioms-data/idioms_lad.ts').then((m) => m.IDIOMS_LAD),
  lb: () =>
    import('../../data/idioms-data/idioms_lb.ts').then((m) => m.IDIOMS_LB),
  ln: () =>
    import('../../data/idioms-data/idioms_ln.ts').then((m) => m.IDIOMS_LN),
  lo: () =>
    import('../../data/idioms-data/idioms_lo.ts').then((m) => m.IDIOMS_LO),
  lt: () =>
    import('../../data/idioms-data/idioms_lt.ts').then((m) => m.IDIOMS_LT),
  lv: () =>
    import('../../data/idioms-data/idioms_lv.ts').then((m) => m.IDIOMS_LV),
  mg: () =>
    import('../../data/idioms-data/idioms_mg.ts').then((m) => m.IDIOMS_MG),
  mh: () =>
    import('../../data/idioms-data/idioms_mh.ts').then((m) => m.IDIOMS_MH),
  mi: () =>
    import('../../data/idioms-data/idioms_mi.ts').then((m) => m.IDIOMS_MI),
  mk: () =>
    import('../../data/idioms-data/idioms_mk.ts').then((m) => m.IDIOMS_MK),
  ml: () =>
    import('../../data/idioms-data/idioms_ml.ts').then((m) => m.IDIOMS_ML),
  mn: () =>
    import('../../data/idioms-data/idioms_mn.ts').then((m) => m.IDIOMS_MN),
  mr: () =>
    import('../../data/idioms-data/idioms_mr.ts').then((m) => m.IDIOMS_MR),
  ms: () =>
    import('../../data/idioms-data/idioms_ms.ts').then((m) => m.IDIOMS_MS),
  mt: () =>
    import('../../data/idioms-data/idioms_mt.ts').then((m) => m.IDIOMS_MT),
  my: () =>
    import('../../data/idioms-data/idioms_my.ts').then((m) => m.IDIOMS_MY),
  nah: () =>
    import('../../data/idioms-data/idioms_nah.ts').then((m) => m.IDIOMS_NAH),
  ne: () =>
    import('../../data/idioms-data/idioms_ne.ts').then((m) => m.IDIOMS_NE),
  nl: () =>
    import('../../data/idioms-data/idioms_nl.ts').then((m) => m.IDIOMS_NL),
  no: () =>
    import('../../data/idioms-data/idioms_no.ts').then((m) => m.IDIOMS_NO),
  nv: () =>
    import('../../data/idioms-data/idioms_nv.ts').then((m) => m.IDIOMS_NV),
  ny: () =>
    import('../../data/idioms-data/idioms_ny.ts').then((m) => m.IDIOMS_NY),
  oc: () =>
    import('../../data/idioms-data/idioms_oc.ts').then((m) => m.IDIOMS_OC),
  om: () =>
    import('../../data/idioms-data/idioms_om.ts').then((m) => m.IDIOMS_OM),
  or: () =>
    import('../../data/idioms-data/idioms_or.ts').then((m) => m.IDIOMS_OR),
  pa: () =>
    import('../../data/idioms-data/idioms_pa.ts').then((m) => m.IDIOMS_PA),
  pau: () =>
    import('../../data/idioms-data/idioms_pau.ts').then((m) => m.IDIOMS_PAU),
  pcm: () =>
    import('../../data/idioms-data/idioms_pcm.ts').then((m) => m.IDIOMS_PCM),
  pl: () =>
    import('../../data/idioms-data/idioms_pl.ts').then((m) => m.IDIOMS_PL),
  ps: () =>
    import('../../data/idioms-data/idioms_ps.ts').then((m) => m.IDIOMS_PS),
  pt: () =>
    import('../../data/idioms-data/idioms_pt.ts').then((m) => m.IDIOMS_PT),
  qu: () =>
    import('../../data/idioms-data/idioms_qu.ts').then((m) => m.IDIOMS_QU),
  qya: () =>
    import('../../data/idioms-data/idioms_qya.ts').then((m) => m.IDIOMS_QYA),
  rm: () =>
    import('../../data/idioms-data/idioms_rm.ts').then((m) => m.IDIOMS_RM),
  ro: () =>
    import('../../data/idioms-data/idioms_ro.ts').then((m) => m.IDIOMS_RO),
  sc: () =>
    import('../../data/idioms-data/idioms_sc.ts').then((m) => m.IDIOMS_SC),
  sd: () =>
    import('../../data/idioms-data/idioms_sd.ts').then((m) => m.IDIOMS_SD),
  si: () =>
    import('../../data/idioms-data/idioms_si.ts').then((m) => m.IDIOMS_SI),
  sjn: () =>
    import('../../data/idioms-data/idioms_sjn.ts').then((m) => m.IDIOMS_SJN),
  sk: () =>
    import('../../data/idioms-data/idioms_sk.ts').then((m) => m.IDIOMS_SK),
  sl: () =>
    import('../../data/idioms-data/idioms_sl.ts').then((m) => m.IDIOMS_SL),
  sm: () =>
    import('../../data/idioms-data/idioms_sm.ts').then((m) => m.IDIOMS_SM),
  sn: () =>
    import('../../data/idioms-data/idioms_sn.ts').then((m) => m.IDIOMS_SN),
  so: () =>
    import('../../data/idioms-data/idioms_so.ts').then((m) => m.IDIOMS_SO),
  sq: () =>
    import('../../data/idioms-data/idioms_sq.ts').then((m) => m.IDIOMS_SQ),
  sr: () =>
    import('../../data/idioms-data/idioms_sr.ts').then((m) => m.IDIOMS_SR),
  su: () =>
    import('../../data/idioms-data/idioms_su.ts').then((m) => m.IDIOMS_SU),
  sv: () =>
    import('../../data/idioms-data/idioms_sv.ts').then((m) => m.IDIOMS_SV),
  sw: () =>
    import('../../data/idioms-data/idioms_sw.ts').then((m) => m.IDIOMS_SW),
  ta: () =>
    import('../../data/idioms-data/idioms_ta.ts').then((m) => m.IDIOMS_TA),
  te: () =>
    import('../../data/idioms-data/idioms_te.ts').then((m) => m.IDIOMS_TE),
  tet: () =>
    import('../../data/idioms-data/idioms_tet.ts').then((m) => m.IDIOMS_TET),
  tg: () =>
    import('../../data/idioms-data/idioms_tg.ts').then((m) => m.IDIOMS_TG),
  th: () =>
    import('../../data/idioms-data/idioms_th.ts').then((m) => m.IDIOMS_TH),
  ti: () =>
    import('../../data/idioms-data/idioms_ti.ts').then((m) => m.IDIOMS_TI),
  tk: () =>
    import('../../data/idioms-data/idioms_tk.ts').then((m) => m.IDIOMS_TK),
  tl: () =>
    import('../../data/idioms-data/idioms_tl.ts').then((m) => m.IDIOMS_TL),
  tlh: () =>
    import('../../data/idioms-data/idioms_tlh.ts').then((m) => m.IDIOMS_TLH),
  to: () =>
    import('../../data/idioms-data/idioms_to.ts').then((m) => m.IDIOMS_TO),
  tr: () =>
    import('../../data/idioms-data/idioms_tr.ts').then((m) => m.IDIOMS_TR),
  ty: () =>
    import('../../data/idioms-data/idioms_ty.ts').then((m) => m.IDIOMS_TY),
  ua: () =>
    import('../../data/idioms-data/idioms_ua.ts').then((m) => m.IDIOMS_UA),
  ug: () =>
    import('../../data/idioms-data/idioms_ug.ts').then((m) => m.IDIOMS_UG),
  ur: () =>
    import('../../data/idioms-data/idioms_ur.ts').then((m) => m.IDIOMS_UR),
  uz: () =>
    import('../../data/idioms-data/idioms_uz.ts').then((m) => m.IDIOMS_UZ),
  val: () =>
    import('../../data/idioms-data/idioms_val.ts').then((m) => m.IDIOMS_VAL),
  vi: () =>
    import('../../data/idioms-data/idioms_vi.ts').then((m) => m.IDIOMS_VI),
  wo: () =>
    import('../../data/idioms-data/idioms_wo.ts').then((m) => m.IDIOMS_WO),
  xh: () =>
    import('../../data/idioms-data/idioms_xh.ts').then((m) => m.IDIOMS_XH),
  yi: () =>
    import('../../data/idioms-data/idioms_yi.ts').then((m) => m.IDIOMS_YI),
  yo: () =>
    import('../../data/idioms-data/idioms_yo.ts').then((m) => m.IDIOMS_YO),
  zh: () =>
    import('../../data/idioms-data/idioms_zh.ts').then((m) => m.IDIOMS_ZH),
  zu: () =>
    import('../../data/idioms-data/idioms_zu.ts').then((m) => m.IDIOMS_ZU),
};

/** Returns the cached data for `lang`, or undefined if not loaded (yet). */
export function getIdiomsForLang(lang: string): Idiom[] | undefined {
  return CACHE[lang];
}

/** Loads (and caches) `lang`'s data on first call; a no-op if already loaded/loading/unavailable. */
export async function ensureIdiomsLoaded(lang: string): Promise<void> {
  if (CACHE[lang]) return;
  const loader = LOADERS[lang];
  if (!loader) return;
  if (!LOADING[lang]) {
    LOADING[lang] = loader().then((data) => {
      CACHE[lang] = data;
    });
  }
  await LOADING[lang];
}

/** True if `lang` has data available at all (synchronous — doesn't trigger or wait for a load). */
export function hasIdiomsForLang(lang: string): boolean {
  return lang in LOADERS;
}


export type { Idiom } from '../../data/idioms.ts';
