// Vymova — js/features/synonyms-loader.ts
// Lazy per-language loader for per-language synonym data (formerly data/synonyms.ts's SYNONYMS_BY_LANG), generated by
// scripts/gen-lang-loader.js (scans data/synonyms-data/) — mirrors mode-utils.ts's
// TABLES/LANG_LOADERS pattern for word data. Only the learner's actual
// language(s) get downloaded instead of every language's data eagerly (see
// docs/architecture-assessment.md p.6). Regenerate (don't hand-edit the
// loader map) after adding or removing a data/synonyms-data/synonyms_xx.ts file.
import type { SynonymEntry } from '../../data/synonyms.ts';
import { buildSynonymReverse } from '../../data/synonyms.ts';

const CACHE: Partial<Record<string, Record<string, SynonymEntry[]>>> = {};
const REVERSE_CACHE: Partial<Record<string, Map<string, string>>> = {};
const LOADING: Partial<Record<string, Promise<void>>> = {};

const LOADERS: Partial<Record<string, () => Promise<Record<string, SynonymEntry[]>>>> = {
  ar: () =>
    import('../../data/synonyms-data/synonyms_ar.ts').then((m) => m.SYNONYMS_AR),
  de: () =>
    import('../../data/synonyms-data/synonyms_de.ts').then((m) => m.SYNONYMS_DE),
  el: () =>
    import('../../data/synonyms-data/synonyms_el.ts').then((m) => m.SYNONYMS_EL),
  en: () =>
    import('../../data/synonyms-data/synonyms_en.ts').then((m) => m.SYNONYMS_EN),
  es: () =>
    import('../../data/synonyms-data/synonyms_es.ts').then((m) => m.SYNONYMS_ES),
  fr: () =>
    import('../../data/synonyms-data/synonyms_fr.ts').then((m) => m.SYNONYMS_FR),
  he: () =>
    import('../../data/synonyms-data/synonyms_he.ts').then((m) => m.SYNONYMS_HE),
  it: () =>
    import('../../data/synonyms-data/synonyms_it.ts').then((m) => m.SYNONYMS_IT),
  ja: () =>
    import('../../data/synonyms-data/synonyms_ja.ts').then((m) => m.SYNONYMS_JA),
  nl: () =>
    import('../../data/synonyms-data/synonyms_nl.ts').then((m) => m.SYNONYMS_NL),
  pl: () =>
    import('../../data/synonyms-data/synonyms_pl.ts').then((m) => m.SYNONYMS_PL),
  pt: () =>
    import('../../data/synonyms-data/synonyms_pt.ts').then((m) => m.SYNONYMS_PT),
  tr: () =>
    import('../../data/synonyms-data/synonyms_tr.ts').then((m) => m.SYNONYMS_TR),
  ua: () =>
    import('../../data/synonyms-data/synonyms_ua.ts').then((m) => m.SYNONYMS_UA),
  zh: () =>
    import('../../data/synonyms-data/synonyms_zh.ts').then((m) => m.SYNONYMS_ZH),
};

/** Returns the cached base dict for `lang`, or undefined if not loaded (yet). */
export function getSynonymsForLang(lang: string): Record<string, SynonymEntry[]> | undefined {
  return CACHE[lang];
}

/** Returns `lang`'s reverse-lookup map (member word → headword), built lazily on first call after the base dict is loaded. Undefined if the base dict itself isn't loaded yet. */
export function getSynonymReverseForLang(lang: string): Map<string, string> | undefined {
  const dict = CACHE[lang];
  if (!dict) return undefined;
  let rev = REVERSE_CACHE[lang];
  if (!rev) {
    rev = buildSynonymReverse(dict);
    REVERSE_CACHE[lang] = rev;
  }
  return rev;
}

/** Loads (and caches) `lang`'s base dict on first call; a no-op if already loaded/loading/unavailable. */
export async function ensureSynonymsLoaded(lang: string): Promise<void> {
  if (CACHE[lang]) return;
  const loader = LOADERS[lang];
  if (!loader) return;
  if (!LOADING[lang]) {
    LOADING[lang] = loader().then((data) => {
      CACHE[lang] = data;
    });
  }
  await LOADING[lang];
}

export type { SynonymEntry } from '../../data/synonyms.ts';
