// Vymova — js/features/usage-notes-loader.ts
// Lazy per-language loader for per-language usage notes (formerly data/usage-notes.ts's USAGE_NOTES_BY_LANG), generated by
// scripts/gen-lang-loader.js (scans data/usage-notes-data/) — mirrors mode-utils.ts's
// TABLES/LANG_LOADERS pattern for word data. Only the learner's actual
// language(s) get downloaded instead of every language's data eagerly (see
// docs/architecture-assessment.md p.6). Regenerate (don't hand-edit the
// loader map) after adding or removing a data/usage-notes-data/usage-notes_xx.ts file.


const CACHE: Partial<Record<string, Record<string, string>>> = {};
const LOADING: Partial<Record<string, Promise<void>>> = {};

const LOADERS: Partial<Record<string, () => Promise<Record<string, string>>>> = {
  de: () =>
    import('../../data/usage-notes-data/usage-notes_de.ts').then((m) => m.USAGE_NOTES_DE),
  en: () =>
    import('../../data/usage-notes-data/usage-notes_en.ts').then((m) => m.USAGE_NOTES_EN),
  es: () =>
    import('../../data/usage-notes-data/usage-notes_es.ts').then((m) => m.USAGE_NOTES_ES),
  fr: () =>
    import('../../data/usage-notes-data/usage-notes_fr.ts').then((m) => m.USAGE_NOTES_FR),
  it: () =>
    import('../../data/usage-notes-data/usage-notes_it.ts').then((m) => m.USAGE_NOTES_IT),
  pl: () =>
    import('../../data/usage-notes-data/usage-notes_pl.ts').then((m) => m.USAGE_NOTES_PL),
  pt: () =>
    import('../../data/usage-notes-data/usage-notes_pt.ts').then((m) => m.USAGE_NOTES_PT),
};

/** Returns the cached data for `lang`, or undefined if not loaded (yet). */
export function getUsageNotesForLang(lang: string): Record<string, string> | undefined {
  return CACHE[lang];
}

/** Loads (and caches) `lang`'s data on first call; a no-op if already loaded/loading/unavailable. */
export async function ensureUsageNotesLoaded(lang: string): Promise<void> {
  if (CACHE[lang]) return;
  const loader = LOADERS[lang];
  if (!loader) return;
  if (!LOADING[lang]) {
    LOADING[lang] = loader().then((data) => {
      CACHE[lang] = data;
    });
  }
  await LOADING[lang];
}

