// worker/src/lang-data.ts — supported learn/know language codes, moved out
// of index.ts so the request-handling logic isn't buried under ~140 lines of
// literal data. LANG_NAMES is the single source of truth: VALID_LANGS is
// derived from its keys rather than kept as a second hand-maintained list —
// a language added to one but not the other used to be possible (silent
// drift), this makes it structurally impossible.
export const LANG_NAMES: Record<string, string> = {
  en: 'English',
  ua: 'Ukrainian',
  es: 'Spanish',
  fr: 'French',
  it: 'Italian',
  pt: 'Portuguese',
  de: 'German',
  he: 'Hebrew',
  ar: 'Arabic',
  pl: 'Polish',
  zh: 'Chinese',
  el: 'Greek',
  ja: 'Japanese',
  tr: 'Turkish',
  nl: 'Dutch',
  vi: 'Vietnamese',
  hi: 'Hindi',
  bn: 'Bengali',
  id: 'Indonesian',
  pcm: 'Nigerian Pidgin',
  ko: 'Korean',
  fa: 'Persian',
  sw: 'Swahili',
  ms: 'Malay',
  th: 'Thai',
  az: 'Azerbaijani',
  ro: 'Romanian',
  hu: 'Hungarian',
  cs: 'Czech',
  kk: 'Kazakh',
  sv: 'Swedish',
  ka: 'Georgian',
  hr: 'Croatian',
  sr: 'Serbian',
  bs: 'Bosnian',
  bg: 'Bulgarian',
  sk: 'Slovak',
  hy: 'Armenian',
  da: 'Danish',
  fi: 'Finnish',
  no: 'Norwegian',
  la: 'Latin',
  lt: 'Lithuanian',
  lv: 'Latvian',
  et: 'Estonian',
  sl: 'Slovenian',
  mk: 'Macedonian',
  sq: 'Albanian',
  is: 'Icelandic',
  cy: 'Welsh',
  ga: 'Irish',
  tl: 'Filipino',
  mn: 'Mongolian',
  uz: 'Uzbek',
  am: 'Amharic',
  eo: 'Esperanto',
  ta: 'Tamil',
  pa: 'Punjabi',
  zu: 'Zulu',
  af: 'Afrikaans',
  ky: 'Kyrgyz',
  tg: 'Tajik',
  tk: 'Turkmen',
  ug: 'Uyghur',
  eu: 'Basque',
  ca: 'Catalan',
  gl: 'Galician',
  mt: 'Maltese',
  lb: 'Luxembourgish',
  ht: 'Haitian Creole',
  bo: 'Tibetan',
  my: 'Burmese',
  km: 'Khmer',
  lo: 'Lao',
  ne: 'Nepali',
  si: 'Sinhala',
  ur: 'Urdu',
  te: 'Telugu',
  ml: 'Malayalam',
  kn: 'Kannada',
  mr: 'Marathi',
  gu: 'Gujarati',
  or: 'Odia',
  as: 'Assamese',
  sd: 'Sindhi',
  ps: 'Pashto',
  so: 'Somali',
  ha: 'Hausa',
  yo: 'Yoruba',
  ig: 'Igbo',
  ti: 'Tigrinya',
  wo: 'Wolof',
  mg: 'Malagasy',
  xh: 'Xhosa',
  sn: 'Shona',
  ny: 'Chewa',
  fj: 'Fijian',
  sm: 'Samoan',
  to: 'Tongan',
  mi: 'Maori',
  haw: 'Hawaiian',
  jv: 'Javanese',
  su: 'Sundanese',
  gd: 'Scottish Gaelic',
  br: 'Breton',
  kw: 'Cornish',
  gv: 'Manx',
  fo: 'Faroese',
  oc: 'Occitan',
  co: 'Corsican',
  sc: 'Sardinian',
  fy: 'Frisian',
  yi: 'Yiddish',
  lad: 'Ladino',
  qu: 'Quechua',
  gn: 'Guarani',
  ay: 'Aymara',
  dz: 'Dzongkha',
  dv: 'Maldivian',
  tet: 'Tetum',
  be: 'Belarusian',
  qya: "Quenya (Tolkien's constructed Elvish language)",
  sjn: "Sindarin (Tolkien's constructed Elvish language)",
  ku: 'Kurdish (Kurmanji)',
  om: 'Oromo',
  ln: 'Lingala',
  bho: 'Bhojpuri',
  ceb: 'Cebuano',
  rm: 'Romansh',
  ty: 'Tahitian',
  ch: 'Chamorro',
  mh: 'Marshallese',
  pau: 'Palauan',
  nah: 'Nahuatl',
  nv: 'Navajo',
  tlh: 'Klingon (constructed language from Star Trek)',
  val: 'High Valyrian (constructed language from Game of Thrones)',
  dth: 'Dothraki (constructed language from Game of Thrones)',
};

export const VALID_LANGS = new Set(Object.keys(LANG_NAMES));
