// scripts/add-words.mjs
// Merges NEW_WORDS into data/words.js, deduplicates, sorts alphabetically, writes back.
import { readFileSync, writeFileSync } from 'fs';
import { fileURLToPath } from 'url';
import { dirname, join } from 'path';

const __dir = dirname(fileURLToPath(import.meta.url));
const wordsPath = join(__dir, '../data/words.js');

// ── New words to add ─────────────────────────────────────────
// Format: [english, ukrainian, example_en, example_ua, ipa]
const NEW_WORDS = [
  // ── A2 ───────────────────────────────────────────────────────
  ["already","вже","I've already finished my homework — can I go out?","Я вже зробив домашнє завдання — можна мені вийти?","/ɔːlˈredi/"],
  ["basic","базовий, основний","You need a basic understanding of grammar first.","Спочатку тобі потрібне базове розуміння граматики.","/ˈbeɪsɪk/"],
  ["begin","починати","The concert will begin at eight o'clock sharp.","Концерт почнеться рівно о восьмій годині.","/bɪˈɡɪn/"],
  ["believe","вірити","I believe she is telling the truth about what happened.","Я вірю, що вона говорить правду про те, що сталося.","/bɪˈliːv/"],
  ["between","між","The café is located between the bank and the pharmacy.","Кафе знаходиться між банком і аптекою.","/bɪˈtwiːn/"],
  ["born","народжений","She was born in Kyiv but grew up in the countryside.","Вона народилася в Києві, але виросла в сільській місцевості.","/bɔːrn/"],
  ["build","будувати","They plan to build a new school in the neighbourhood.","Вони планують побудувати нову школу в мікрорайоні.","/bɪld/"],
  ["busy","зайнятий","I'm too busy to meet today — can we reschedule?","Я занадто зайнятий сьогодні — чи можемо перенести зустріч?","/ˈbɪzi/"],
  ["care","дбати, турбота","She really cares about the wellbeing of her students.","Вона справді дбає про добробут своїх учнів.","/keər/"],
  ["certainly","звичайно, безумовно","I will certainly try my best to help you with this.","Я безумовно докладу всіх зусиль, щоб вам допомогти.","/ˈsɜːrtnli/"],
  ["choose","вибирати","It was hard to choose between the two job offers.","Було важко вибрати між двома пропозиціями роботи.","/tʃuːz/"],
  ["complete","завершувати, повний","Please complete the form and return it by Friday.","Будь ласка, заповни форму і поверни її до п'ятниці.","/kəmˈpliːt/"],
  ["control","контролювати, контроль","It's important to control your spending every month.","Важливо контролювати свої витрати щомісяця.","/kənˈtrəʊl/"],
  ["cost","коштувати, вартість","How much does this jacket cost? It looks expensive.","Скільки коштує ця куртка? Вона виглядає дорого.","/kɒst/"],
  ["count","рахувати, лічити","Can you count the number of people in the room?","Чи можеш ти порахувати кількість людей у кімнаті?","/kaʊnt/"],
  ["cover","покривати, охоплювати","Snow covered the streets and rooftops overnight.","Сніг покрив вулиці і дахи протягом ночі.","/ˈkʌvər/"],
  ["create","створювати","She used the app to create a beautiful photo album.","Вона використала застосунок, щоб створити красивий фотоальбом.","/kriˈeɪt/"],
  ["culture","культура","Travelling helps you understand different cultures better.","Подорожі допомагають краще зрозуміти різні культури.","/ˈkʌltʃər/"],
  ["dangerous","небезпечний","Driving too fast on icy roads is extremely dangerous.","Їздити надто швидко на крижаних дорогах вкрай небезпечно.","/ˈdeɪndʒərəs/"],
  ["dark","темний, темрява","It was so dark outside that I couldn't see anything.","Надворі було так темно, що я нічого не бачив.","/dɑːrk/"],
  ["definitely","точно, безперечно","I will definitely come to your party on Saturday.","Я точно прийду на твою вечірку в суботу.","/ˈdefɪnətli/"],
  ["design","дизайн, проектувати","She designed the new logo for the company website.","Вона розробила новий логотип для сайту компанії.","/dɪˈzaɪn/"],
  ["difficult","важкий, складний","The exam was more difficult than I had expected.","Іспит виявився важчим, ніж я очікував.","/ˈdɪfɪkəlt/"],
  ["distance","відстань","The distance between the two cities is about 300 km.","Відстань між двома містами становить близько 300 км.","/ˈdɪstəns/"],
  ["each","кожен, кожна","Each student received a certificate at the ceremony.","Кожен студент отримав сертифікат на церемонії.","/iːtʃ/"],
  ["effect","ефект, вплив","The medicine had a positive effect on her recovery.","Ліки позитивно вплинули на її одужання.","/ɪˈfekt/"],
  ["else","ще, інший","Is there anything else I can help you with today?","Чи є ще щось, чим я можу тобі допомогти?","/els/"],
  ["end","кінець, закінчувати","At the end of the film, everyone was crying.","Наприкінці фільму всі плакали.","/end/"],
  ["energy","енергія","She had so much energy that she never seemed tired.","У неї було стільки енергії, що вона ніколи не здавалася втомленою.","/ˈenərdʒi/"],
  ["enough","достатньо","Do we have enough time to finish the project today?","У нас є достатньо часу, щоб завершити проект сьогодні?","/ɪˈnʌf/"],
  ["especially","особливо","I love all kinds of music, especially jazz and blues.","Я люблю всю музику, особливо джаз і блюз.","/ɪˈspeʃəli/"],
  ["everyone","всі, кожен","Everyone enjoyed the celebration — it was a great party.","Всі насолоджувалися святкуванням — це була чудова вечірка.","/ˈevriwʌn/"],
  ["exactly","точно, саме","That's exactly what I was thinking — great minds think alike.","Це саме те, про що я думав — великі уми мислять однаково.","/ɪɡˈzæktli/"],
  ["fact","факт","The fact is that we need more time to finish the work.","Факт у тому, що нам потрібно більше часу, щоб закінчити роботу.","/fækt/"],
  ["favour","послуга, схвалення","Could you do me a favour and post this letter?","Чи не міг би ти зробити мені послугу і відправити цей лист?","/ˈfeɪvər/"],
  ["few","кілька, мало","I have a few questions I'd like to ask you.","У мене є кілька питань, які я хотів би тобі поставити.","/fjuː/"],
  ["fight","боротися, бійка","They had a big fight but made up the next day.","У них була велика сварка, але наступного дня вони помирилися.","/faɪt/"],
  ["fill","наповнювати, заповнювати","Please fill in the form with your personal details.","Будь ласка, заповни форму своїми особистими даними.","/fɪl/"],
  ["finally","нарешті","After months of waiting, she finally got the job offer.","Після місяців очікування вона нарешті отримала пропозицію роботи.","/ˈfaɪnəli/"],
  ["finish","закінчувати, завершувати","I need to finish this report before the meeting starts.","Мені потрібно закінчити цей звіт до початку наради.","/ˈfɪnɪʃ/"],
  ["fire","вогонь, пожежа, звільняти","The fire spread quickly through the old wooden building.","Вогонь швидко поширився по старій дерев'яній будівлі.","/faɪər/"],
  ["force","сила, змушувати","You can't force someone to do something they don't want.","Ти не можеш змушувати когось робити те, чого він не хоче.","/fɔːrs/"],
  ["forget","забувати","Don't forget to bring your passport to the airport.","Не забудь взяти паспорт до аеропорту.","/fərˈɡet/"],
  ["form","форма, утворювати","Ice forms on the lake when the temperature drops.","Лід утворюється на озері, коли температура падає.","/fɔːrm/"],
  ["forward","вперед, подати","I'm looking forward to seeing you at the weekend.","Я з нетерпінням чекаю зустрічі з тобою у вихідні.","/ˈfɔːrwərd/"],
  ["fresh","свіжий","She opened the window to let in some fresh air.","Вона відкрила вікно, щоб впустити свіже повітря.","/freʃ/"],
  ["full","повний","The bus was so full that no one else could get on.","Автобус був такий переповнений, що ніхто більше не міг увійти.","/fʊl/"],
  ["half","половина","I only ate half of the pizza — I wasn't very hungry.","Я з'їв лише половину піци — я не дуже проголодався.","/hɑːf/"],
  ["hard","важкий, наполегливо","She worked hard every day to achieve her dream.","Вона щодня наполегливо працювала, щоб досягти своєї мрії.","/hɑːrd/"],
  ["hate","ненавидіти","He hates being late — he's always on time.","Він ненавидить спізнюватися — він завжди вчасно.","/heɪt/"],
  ["have","мати, здійснювати","Do you have any plans for the weekend?","У тебе є якісь плани на вихідні?","/hæv/"],
  ["hold","тримати, проводити","Please hold the door open while I carry the boxes.","Будь ласка, тримай двері відкритими, поки я несу коробки.","/həʊld/"],
  ["hope","сподіватися, надія","I hope everything goes well with your exam tomorrow.","Сподіваюся, все піде добре на твоєму іспиті завтра.","/həʊp/"],
  ["hurt","боліти, завдавати болю","My leg still hurts after the accident last week.","Моя нога все ще болить після нещасного випадку минулого тижня.","/hɜːrt/"],
  ["idea","ідея","That's a great idea — why didn't we think of it before?","Це чудова ідея — чому ми не подумали про це раніше?","/aɪˈdɪə/"],
  ["important","важливий","It's important to eat well and exercise regularly.","Важливо добре харчуватися і регулярно займатися спортом.","/ɪmˈpɔːrtənt/"],
  ["information","інформація","Please read all the information before signing the form.","Будь ласка, прочитай всю інформацію перед підписанням форми.","/ˌɪnfəˈmeɪʃən/"],
  ["interest","інтерес, зацікавлювати","She showed great interest in the history of ancient Rome.","Вона виявила великий інтерес до історії Стародавнього Риму.","/ˈɪntrəst/"],
  ["interesting","цікавий","The documentary about space was really interesting.","Документальний фільм про космос був справді цікавим.","/ˈɪntrəstɪŋ/"],
  ["kill","вбивати","The drought killed many plants in the garden.","Посуха знищила багато рослин у саду.","/kɪl/"],
  ["language","мова","She speaks three languages: English, French and Spanish.","Вона розмовляє трьома мовами: англійською, французькою та іспанською.","/ˈlæŋɡwɪdʒ/"],
  ["least","найменше, принаймні","At least ten people came to the event — maybe more.","Принаймні десять людей прийшли на захід — можливо, більше.","/liːst/"],
  ["leave","залишати, виходити","What time do you usually leave for work in the morning?","О котрій ти зазвичай виходиш на роботу вранці?","/liːv/"],
  ["less","менше","Try to spend less time on your phone and more with family.","Намагайся менше часу проводити з телефоном і більше — з родиною.","/les/"],
  ["lose","втрачати, програвати","I always lose my keys — I need to be more organised.","Я завжди втрачаю ключі — мені потрібно бути більш організованим.","/luːz/"],
  ["love","любити, любов","She loves spending weekends hiking in the mountains.","Вона обожнює проводити вихідні в піших походах горами.","/lʌv/"],
  ["main","головний, основний","What is the main reason you decided to change jobs?","Яка головна причина, чому ти вирішив змінити роботу?","/meɪn/"],
  ["modern","сучасний","The building has a very modern design with lots of glass.","Будівля має дуже сучасний дизайн із великою кількістю скла.","/ˈmɒdərn/"],
  ["near","близько, поблизу","Is there a pharmacy near here? I need some medicine.","Чи є тут поблизу аптека? Мені потрібні ліки.","/nɪər/"],
  ["need","потребувати, потреба","You need to practise every day to improve your English.","Тобі потрібно практикуватися щодня, щоб покращити свою англійську.","/niːd/"],
  ["normal","нормальний, звичайний","It's completely normal to feel nervous before an exam.","Цілком нормально нервувати перед іспитом.","/ˈnɔːrməl/"],
  ["often","часто","How often do you go to the gym each week?","Як часто ти ходиш до спортзалу щотижня?","/ˈɒfən/"],
  ["other","інший, інші","Some people prefer coffee, while others prefer tea.","Деякі люди воліють каву, тоді як інші — чай.","/ˈʌðər/"],
  ["outside","зовні, надвір","Let's eat outside today — the weather is perfect.","Давай поїмо надворі сьогодні — погода ідеальна.","/ˌaʊtˈsaɪd/"],
  ["place","місце","This is my favourite place to relax in the city.","Це моє улюблене місце для відпочинку в місті.","/pleɪs/"],
  ["plan","план, планувати","We need to make a plan before we start the project.","Нам потрібно скласти план, перш ніж розпочати проект.","/plæn/"],
  ["position","посада, позиція","She applied for the position of marketing manager.","Вона подала заявку на посаду менеджера з маркетингу.","/pəˈzɪʃən/"],
  ["power","влада, сила, потужність","Knowledge is power — education changes lives.","Знання — це сила — освіта змінює життя.","/ˈpaʊər/"],
  ["probably","мабуть, напевно","I'll probably finish work late tonight — don't wait.","Мабуть, я закінчу роботу сьогодні ввечері пізно — не чекай.","/ˈprɒbəbli/"],
  ["programme","програма, передача","What's your favourite TV programme of the week?","Яка твоя улюблена телевізійна передача тижня?","/ˈprəʊɡræm/"],
  ["public","громадський, публічний","The new park is open to the public every day.","Новий парк відкритий для громадськості щодня.","/ˈpʌblɪk/"],
  ["pull","тягнути, тягти","She had to pull the heavy suitcase up the stairs.","Їй довелося тягнути важку валізу вгору сходами.","/pʊl/"],
  ["push","штовхати, тиснути","Please push the button to call the elevator.","Будь ласка, натисни кнопку, щоб викликати ліфт.","/pʊʃ/"],
  ["put","класти, ставити","Please put your phone away during the meeting.","Будь ласка, прибери телефон під час наради.","/pʊt/"],
  ["realise","усвідомлювати, розуміти","I didn't realise how late it was until I looked at my watch.","Я не усвідомив, наскільки пізно, поки не глянув на годинник.","/ˈrɪəlaɪz/"],
  ["remember","пам'ятати","Do you remember the first day of school?","Ти пам'ятаєш перший день у школі?","/rɪˈmembər/"],
  ["repeat","повторювати","Could you please repeat that? I didn't catch it.","Чи міг би ти, будь ласка, повторити? Я не зрозумів.","/rɪˈpiːt/"],
  ["result","результат, наслідок","The exam results will be published next week.","Результати іспиту будуть опубліковані наступного тижня.","/rɪˈzʌlt/"],
  ["right","правильний, право, праворуч","Turn right at the traffic lights, then go straight.","Поверни праворуч на світлофорі, а потім їдь прямо.","/raɪt/"],
  ["rise","підніматися, зростати","The sun rises in the east and sets in the west.","Сонце сходить на сході і заходить на заході.","/raɪz/"],
  ["same","однаковий, той самий","We both ordered the same dish at the restaurant.","Ми обидва замовили одну й ту саму страву в ресторані.","/seɪm/"],
  ["save","рятувати, зберігати","Don't forget to save your work before you close the document.","Не забудь зберегти роботу перед закриттям документа.","/seɪv/"],
  ["scene","сцена, місце подій","The police arrived quickly at the scene of the accident.","Поліція швидко прибула на місце аварії.","/siːn/"],
  ["send","надсилати, відправляти","I'll send you the report by email before lunch.","Я надішлю тобі звіт електронною поштою до обіду.","/send/"],
  ["show","показувати, шоу","Let me show you how to use this software step by step.","Дозвольте показати вам, як використовувати цю програму крок за кроком.","/ʃəʊ/"],
  ["side","сторона, бік","There are trees on both sides of the road.","По обидва боки дороги ростуть дерева.","/saɪd/"],
  ["situation","ситуація","The situation is complicated — we need expert advice.","Ситуація складна — нам потрібна порада експерта.","/ˌsɪtʃuˈeɪʃən/"],
  ["sometimes","іноді, час від часу","Sometimes I walk to work instead of taking the bus.","Іноді я йду на роботу пішки замість того, щоб їхати автобусом.","/ˈsʌmtaɪmz/"],
  ["sort","вид, сортувати","What sort of music do you like to listen to?","Яку музику ти любиш слухати?","/sɔːrt/"],
  ["speak","говорити, розмовляти","She speaks English fluently and also knows German.","Вона вільно говорить по-англійськи і також знає німецьку.","/spiːk/"],
  ["spend","витрачати, проводити (час)","I like to spend my free time reading or cycling.","Я люблю проводити вільний час за читанням або їздою на велосипеді.","/spend/"],
  ["start","починати, початок","What time does the film start? I don't want to be late.","О котрій починається фільм? Я не хочу спізнитися.","/stɑːrt/"],
  ["story","історія, розповідь","She told me a funny story about what happened at work.","Вона розповіла мені смішну історію про те, що сталося на роботі.","/ˈstɔːri/"],
  ["suddenly","раптово, несподівано","The lights suddenly went out in the middle of the concert.","Світло раптово погасло посередині концерту.","/ˈsʌdənli/"],
  ["system","система","The school uses a new system to track student progress.","Школа використовує нову систему для відстеження прогресу учнів.","/ˈsɪstəm/"],
  ["test","тест, перевіряти","She studied hard and passed the test with flying colours.","Вона наполегливо вчилася і склала тест з відмінним результатом.","/test/"],
  ["though","хоча, проте","The weather was cold, though we still had a great time.","Погода була холодна, хоча ми все одно чудово провели час.","/ðəʊ/"],
  ["through","через, крізь","We drove through the tunnel to get to the other side.","Ми проїхали через тунель, щоб дістатися іншого боку.","/θruː/"],
  ["told","сказав, розповів","She told me the news as soon as she arrived home.","Вона повідомила мені новини, щойно прийшла додому.","/təʊld/"],
  ["true","правда, правдивий","Is it true that you're moving to another city?","Правда, що ти переїжджаєш до іншого міста?","/truː/"],
  ["understand","розуміти","I don't understand why you made that decision.","Я не розумію, чому ти прийняв таке рішення.","/ˌʌndəˈstænd/"],
  ["until","до (часу), поки не","Please wait here until I come back from the office.","Будь ласка, зачекай тут, поки я не повернуся з офісу.","/ənˈtɪl/"],
  ["used","використовуваний, звик","I'm used to waking up early — I've done it for years.","Я звик прокидатися рано — я так роблю вже роками.","/juːzd/"],
  ["usual","звичний, звичайний","She sat in her usual seat by the window on the train.","Вона сіла на своє звичне місце біля вікна в поїзді.","/ˈjuːʒuəl/"],
  ["usually","зазвичай","I usually have breakfast at seven and leave at eight.","Зазвичай я снідаю о сьомій і виходжу о восьмій.","/ˈjuːʒuəli/"],
  ["voice","голос","She has a beautiful voice — she should sing professionally.","У неї чудовий голос — вона мала б співати професійно.","/vɔɪs/"],
  ["wait","чекати, очікувати","You'll have to wait about twenty minutes for a table.","Вам доведеться зачекати близько двадцяти хвилин на столик.","/weɪt/"],
  ["want","хотіти, бажати","What do you want to do after you finish your studies?","Що ти хочеш робити після закінчення навчання?","/wɒnt/"],
  ["without","без","I can't imagine life without music and good books.","Я не можу уявити життя без музики і хороших книг.","/wɪˈðaʊt/"],
  ["worse","гірший, гірше","The traffic is worse on Mondays than any other day.","Пробки в понеділок гірші, ніж будь-який інший день.","/wɜːrs/"],
  ["yourself","себе, сам","You should be proud of yourself for what you achieved.","Ти маєш пишатися собою за те, чого досяг.","/jɔːrˈself/"],

  // ── B1 ────────────────────────────────────────────────────────
  ["achieve","досягати","Hard work and dedication help you achieve your goals.","Наполеглива праця і відданість допомагають досягати цілей.","/əˈtʃiːv/"],
  ["acknowledge","визнавати","She acknowledged that the mistake was hers.","Вона визнала, що помилка була її.","/əkˈnɒlɪdʒ/"],
  ["adapt","адаптуватися, пристосовуватися","It can take time to adapt to a new culture.","Може знадобитися час, щоб адаптуватися до нової культури.","/əˈdæpt/"],
  ["adequate","достатній, відповідний","The salary was not adequate for the amount of work required.","Зарплата не відповідала обсягу необхідної роботи.","/ˈædɪkwət/"],
  ["allocate","розподіляти, виділяти","The government plans to allocate more funds to education.","Уряд планує виділити більше коштів на освіту.","/ˈæləkeɪt/"],
  ["alternative","альтернатива, альтернативний","There is no alternative — we must act immediately.","Немає альтернативи — ми повинні діяти негайно.","/ɔːlˈtɜːrnətɪv/"],
  ["analyse","аналізувати","We need to analyse the data carefully before drawing conclusions.","Нам потрібно ретельно проаналізувати дані, перш ніж робити висновки.","/ˈænəlaɪz/"],
  ["analysis","аналіз","The analysis showed that sales increased by fifteen percent.","Аналіз показав, що продажі зросли на п'ятнадцять відсотків.","/əˈnæləsɪs/"],
  ["anticipate","передбачати, очікувати","We didn't anticipate such a large number of visitors.","Ми не передбачали такої великої кількості відвідувачів.","/ænˈtɪsɪpeɪt/"],
  ["apparent","очевидний, явний","It became apparent that the plan had serious flaws.","Стало очевидним, що план мав серйозні недоліки.","/əˈpærənt/"],
  ["appropriate","відповідний, доречний","It's important to wear appropriate clothes for the interview.","Важливо одягнути відповідний одяг на співбесіду.","/əˈprəʊpriət/"],
  ["approximately","приблизно, близько","The project will take approximately three months to complete.","Проект займе приблизно три місяці на завершення.","/əˈprɒksɪmətli/"],
  ["aspect","аспект, сторона","We need to consider every aspect of the problem carefully.","Нам потрібно уважно розглянути кожен аспект проблеми.","/ˈæspekt/"],
  ["assert","стверджувати, наполягати","She asserted that the figures in the report were incorrect.","Вона стверджувала, що цифри у звіті були неправильними.","/əˈsɜːrt/"],
  ["assess","оцінювати","Teachers assess students' progress at the end of each term.","Вчителі оцінюють прогрес учнів наприкінці кожного семестру.","/əˈses/"],
  ["assume","припускати","Don't assume you know the answer without checking the facts.","Не припускай, що знаєш відповідь, не перевіривши факти.","/əˈsjuːm/"],
  ["assumption","припущення","The plan was based on the assumption that prices would stay low.","План ґрунтувався на припущенні, що ціни залишаться низькими.","/əˈsʌmpʃən/"],
  ["attribute","приписувати, атрибут","His success can be attributed to hard work and discipline.","Його успіх можна приписати наполегливій праці та дисципліні.","/əˈtrɪbjuːt/"],
  ["behaviour","поведінка","Good behaviour is expected from all students in class.","Від усіх учнів на занятті очікується гарна поведінка.","/bɪˈheɪvjər/"],
  ["capable","здатний, спроможний","She is very capable of managing a large team effectively.","Вона цілком здатна ефективно керувати великою командою.","/ˈkeɪpəbəl/"],
  ["category","категорія","This book falls into the category of historical fiction.","Ця книга відноситься до категорії історичної прози.","/ˈkætəɡəri/"],
  ["challenge","виклик, кидати виклик","Learning a new language is a challenging but rewarding experience.","Вивчення нової мови — це складний, але корисний досвід.","/ˈtʃælɪndʒ/"],
  ["characteristic","характеристика, характерний","Attention to detail is a key characteristic of a good engineer.","Увага до деталей — ключова характеристика гарного інженера.","/ˌkærəktəˈrɪstɪk/"],
  ["circumstances","обставини","Under these difficult circumstances, we did our best.","За цих складних обставин ми зробили все можливе.","/ˈsɜːrkəmstænsɪz/"],
  ["component","компонент, складова","Each component of the engine must work perfectly together.","Кожен компонент двигуна повинен ідеально працювати разом.","/kəmˈpəʊnənt/"],
  ["concentrate","концентруватися, зосереджуватися","It's hard to concentrate when there's a lot of noise.","Важко концентруватися, коли навколо багато шуму.","/ˈkɒnsəntreɪt/"],
  ["conflict","конфлікт, суперечити","The new policy created a conflict between the two departments.","Нова політика спричинила конфлікт між двома відділами.","/ˈkɒnflɪkt/"],
  ["consequently","отже, як наслідок","He didn't study enough; consequently, he failed the exam.","Він недостатньо вчився; як наслідок, він провалив іспит.","/ˈkɒnsɪkwəntli/"],
  ["contrast","контраст, протиставляти","In contrast to her brother, she is very calm and patient.","На відміну від свого брата, вона дуже спокійна і терпелива.","/ˈkɒntrɑːst/"],
  ["controversial","суперечливий, спірний","Climate change is a controversial topic in some countries.","Зміна клімату є суперечливою темою в деяких країнах.","/ˌkɒntrəˈvɜːrʃəl/"],
  ["criticism","критика, зауваження","He took the criticism well and used it to improve his work.","Він добре сприйняв критику і використав її, щоб покращити свою роботу.","/ˈkrɪtɪsɪzəm/"],
  ["demonstrate","демонструвати, показувати","The teacher demonstrated how to solve the equation step by step.","Вчитель наочно показав, як розв'язати рівняння крок за кроком.","/ˈdemənstreɪt/"],
  ["detail","деталь, подробиця","Please describe the incident in as much detail as possible.","Будь ласка, опишіть інцидент з якомога більшою кількістю деталей.","/ˈdiːteɪl/"],
  ["distinction","відмінність, різниця","There is a clear distinction between the two approaches.","Між двома підходами існує чітка відмінність.","/dɪˈstɪŋkʃən/"],
  ["dominant","домінуючий, переважаючий","English is the dominant language in international business.","Англійська є домінуючою мовою в міжнародному бізнесі.","/ˈdɒmɪnənt/"],
  ["economy","економіка","The country's economy grew strongly over the past decade.","Економіка країни стрімко зростала протягом останнього десятиліття.","/ɪˈkɒnəmi/"],
  ["education","освіта, навчання","A good education opens many doors in life.","Хороша освіта відкриває багато дверей у житті.","/ˌedʒuˈkeɪʃən/"],
  ["emphasise","наголошувати, підкреслювати","The report emphasised the importance of regular exercise.","Звіт наголосив на важливості регулярних фізичних вправ.","/ˈemfəsaɪz/"],
  ["exception","виняток","This rule applies to everyone without exception.","Це правило поширюється на всіх без винятку.","/ɪkˈsepʃən/"],
  ["expectation","очікування, сподівання","The results exceeded everyone's expectations by a wide margin.","Результати перевершили очікування всіх із великим відривом.","/ˌekspekˈteɪʃən/"],
  ["fundamental","фундаментальний, основний","Respect for others is a fundamental principle of society.","Повага до інших — фундаментальний принцип суспільства.","/ˌfʌndəˈmentəl/"],
  ["generate","генерувати, породжувати","The new factory will generate hundreds of local jobs.","Новий завод створить сотні місцевих робочих місць.","/ˈdʒenəreɪt/"],
  ["global","глобальний, світовий","Climate change is one of the biggest global challenges today.","Зміна клімату — один із найбільших глобальних викликів сьогодні.","/ˈɡləʊbəl/"],
  ["guarantee","гарантія, гарантувати","The product comes with a two-year money-back guarantee.","Товар постачається з дворічною гарантією повернення грошей.","/ˌɡærənˈtiː/"],
  ["identify","ідентифікувати, визначити","Scientists have identified a new species of bird in the forest.","Вчені виявили новий вид птаха в лісі.","/aɪˈdentɪfaɪ/"],
  ["ideology","ідеологія","The two parties have very different political ideologies.","Дві партії мають дуже різні політичні ідеології.","/ˌaɪdiˈɒlədʒi/"],
  ["illustrate","ілюструвати, пояснювати","This example illustrates the main point of my argument.","Цей приклад ілюструє основну думку мого аргументу.","/ˈɪləstreɪt/"],
  ["implication","наслідок, підтекст","The implications of this decision could affect thousands.","Наслідки цього рішення можуть торкнутися тисяч людей.","/ˌɪmplɪˈkeɪʃən/"],
  ["individual","індивідуальний, особа","Each individual has the right to express their own opinion.","Кожна особа має право висловлювати власну думку.","/ˌɪndɪˈvɪdʒuəl/"],
  ["intention","намір, мета","My intention is to finish the project by the end of the month.","Мій намір — завершити проект до кінця місяця.","/ɪnˈtenʃən/"],
  ["judgement","судження, рішення","Trust your own judgement when making difficult decisions.","Довіряй власному судженню, приймаючи складні рішення.","/ˈdʒʌdʒmənt/"],
  ["majority","більшість","The majority of students passed the exam on the first attempt.","Більшість студентів здали іспит з першої спроби.","/məˈdʒɒrɪti/"],
  ["method","метод, спосіб","What method do you use to learn new vocabulary?","Який метод ти використовуєш для вивчення нової лексики?","/ˈmeθəd/"],
  ["motivation","мотивація","Without motivation, it's very difficult to achieve your goals.","Без мотивації дуже важко досягти своїх цілей.","/ˌməʊtɪˈveɪʃən/"],
  ["negative","негативний, від'ємний","Try to avoid negative thinking — focus on solutions instead.","Намагайся уникати негативного мислення — зосередься на рішеннях.","/ˈneɡətɪv/"],
  ["parameter","параметр, обмеження","We need to work within the parameters set by the client.","Нам потрібно працювати в межах параметрів, встановлених клієнтом.","/pəˈræmɪtər/"],
  ["performance","виступ, продуктивність","Her performance in the play received a standing ovation.","Її виступ у виставі отримав оплески стоячи.","/pərˈfɔːrməns/"],
  ["positive","позитивний, впевнений","Try to stay positive even when things don't go to plan.","Намагайся залишатися позитивним, навіть коли все іде не за планом.","/ˈpɒzətɪv/"],
  ["preference","перевага, вподобання","Do you have a preference for morning or evening meetings?","У тебе є перевага ранкових чи вечірніх нарад?","/ˈprefrəns/"],
  ["proportion","пропорція, частка","A large proportion of students study online nowadays.","Значна частка студентів сьогодні навчається онлайн.","/prəˈpɔːrʃən/"],
  ["reaction","реакція, відгук","Her reaction to the surprising news was completely unexpected.","Її реакція на несподівану новину була цілком несподіваною.","/riˈækʃən/"],
  ["recognise","розпізнавати, визнавати","I recognised her immediately from the photo.","Я відразу впізнав її за фотографією.","/ˈrekəɡnaɪz/"],
  ["recommend","рекомендувати, радити","I would highly recommend this book to anyone who loves history.","Я щиро рекомендую цю книгу всім, хто любить історію.","/ˌrekəˈmend/"],
  ["regardless","незважаючи на, попри","Regardless of the weather, the outdoor concert will go ahead.","Незважаючи на погоду, концерт просто неба відбудеться.","/rɪˈɡɑːrdləs/"],
  ["relationship","стосунки, відносини","A good working relationship is essential for team success.","Хороші робочі відносини необхідні для успіху команди.","/rɪˈleɪʃənʃɪp/"],
  ["requirement","вимога, потреба","A university degree is a requirement for this position.","Університетський диплом є вимогою для цієї посади.","/rɪˈkwaɪərmənt/"],
  ["resource","ресурс, засіб","Natural resources must be used responsibly for future generations.","Природні ресурси потрібно використовувати відповідально для майбутніх поколінь.","/rɪˈsɔːrs/"],
  ["responsibility","відповідальність","It's everyone's responsibility to protect the environment.","Захист навколишнього середовища — це відповідальність кожного.","/rɪˌspɒnsɪˈbɪlɪti/"],
  ["role","роль, функція","Technology plays a major role in modern education.","Технології відіграють важливу роль у сучасній освіті.","/rəʊl/"],
  ["statement","твердження, заява","The minister made an official statement about the new policy.","Міністр зробив офіційну заяву щодо нової політики.","/ˈsteɪtmənt/"],
  ["statistics","статистика","According to the latest statistics, unemployment is falling.","Відповідно до останньої статистики, безробіття знижується.","/stəˈtɪstɪks/"],
  ["structure","структура, будова","The structure of the report should be clear and logical.","Структура звіту має бути чіткою і логічною.","/ˈstrʌktʃər/"],
  ["suitable","підходящий, відповідний","This film is not suitable for children under twelve.","Цей фільм не підходить для дітей до дванадцяти років.","/ˈsuːtəbəl/"],
  ["technical","технічний, фаховий","The technical team is working to fix the problem now.","Технічна команда зараз працює над усуненням проблеми.","/ˈteknɪkəl/"],
  ["technique","техніка, метод","She used a special technique to paint the watercolour.","Вона використала спеціальну техніку для малювання акварелі.","/tekˈniːk/"],
  ["technology","технологія","Modern technology has completely changed how we communicate.","Сучасні технології повністю змінили те, як ми спілкуємося.","/tekˈnɒlədʒi/"],
  ["theory","теорія","His theory about the cause of the accident proved to be correct.","Його теорія щодо причини аварії виявилася правильною.","/ˈθɪəri/"],
  ["traditional","традиційний","The village holds a traditional festival every summer.","У селі щоліта проводиться традиційний фестиваль.","/trəˈdɪʃənəl/"],
  ["transform","трансформувати, перетворювати","The renovation completely transformed the old building.","Реновація повністю перетворила стару будівлю.","/trænsˈfɔːrm/"],
  ["trend","тенденція, мода","There is a growing trend towards working from home.","Спостерігається зростаюча тенденція до роботи вдома.","/trend/"],
  ["typical","типовий, характерний","This is a typical example of how the system works.","Це типовий приклад того, як працює система.","/ˈtɪpɪkəl/"],

  // ── C1 ────────────────────────────────────────────────────────
  ["albeit","хоча, хоч і","The project was a success, albeit a very expensive one.","Проект був успішним, хоч і дуже дорогим.","/ɔːlˈbiːɪt/"],
  ["ambiguity","двозначність, неоднозначність","The ambiguity in the contract led to a legal dispute.","Неоднозначність у контракті призвела до судового спору.","/ˌæmbɪˈɡjuːɪti/"],
  ["ambivalent","амбівалентний, суперечливий","She felt ambivalent about moving abroad for the new job.","Вона відчувала суперечливі почуття щодо переїзду за кордон заради нової роботи.","/æmˈbɪvələnt/"],
  ["analogy","аналогія, порівняння","He used an analogy to explain the complex scientific concept.","Він використав аналогію, щоб пояснити складну наукову концепцію.","/əˈnælədʒi/"],
  ["articulate","чітко висловлювати, красномовний","She articulated her arguments clearly and persuasively.","Вона чітко й переконливо виклала свої аргументи.","/ɑːrˈtɪkjuleɪt/"],
  ["assertion","твердження, стверджування","His assertion that the data was wrong turned out to be correct.","Його твердження про те, що дані були неправильними, виявилось вірним.","/əˈsɜːrʃən/"],
  ["autonomous","автономний, незалежний","The committee operates as an autonomous body within the university.","Комітет функціонує як автономний орган у межах університету.","/ɔːˈtɒnəməs/"],
  ["brevity","стислість, короткість","The report impressed everyone for its brevity and clarity.","Звіт вразив усіх своєю стислістю та чіткістю.","/ˈbrevɪti/"],
  ["catalyst","каталізатор, поштовх","The discovery acted as a catalyst for major scientific advances.","Відкриття стало каталізатором для великих наукових досягнень.","/ˈkætəlɪst/"],
  ["compelling","переконливий, захоплюючий","She made a compelling argument for reforming the tax system.","Вона навела переконливий аргумент на користь реформування податкової системи.","/kəmˈpelɪŋ/"],
  ["concurrent","одночасний, паралельний","The two events were concurrent, making it impossible to attend both.","Дві події відбувалися одночасно, тому відвідати обидві було неможливо.","/kənˈkɜːrənt/"],
  ["connotation","конотація, додатковий смисл","The word 'home' has warm connotations for most people.","Слово 'дім' має теплі конотації для більшості людей.","/ˌkɒnəˈteɪʃən/"],
  ["consensus","консенсус, загальна згода","The committee reached a consensus after hours of discussion.","Комітет дійшов консенсусу після годин дискусії.","/kənˈsensəs/"],
  ["contention","твердження, суперечка","Her main contention is that education funding must increase.","Її головне твердження полягає в тому, що фінансування освіти має зростати.","/kənˈtenʃən/"],
  ["corroborate","підтверджувати, підкріплювати","The witness's testimony corroborated the suspect's account.","Свідчення очевидця підтвердило версію підозрюваного.","/kəˈrɒbəreɪt/"],
  ["credibility","довіра, авторитет","His frequent mistakes undermined his credibility as an expert.","Його часті помилки підірвали його авторитет як експерта.","/ˌkredɪˈbɪlɪti/"],
  ["culminate","завершуватися, досягати кульмінації","Years of research culminated in a major scientific breakthrough.","Роки досліджень завершилися значним науковим проривом.","/ˈkʌlmɪneɪt/"],
  ["deduce","дедукувати, робити висновок","From the available evidence, scientists deduced the age of the fossil.","З наявних доказів вчені зробили висновок про вік скам'янілості.","/dɪˈdjuːs/"],
  ["defer","відкладати, поступатися","She decided to defer her studies for a year to travel.","Вона вирішила відкласти навчання на рік, щоб подорожувати.","/dɪˈfɜːr/"],
  ["delineate","окреслювати, чітко описувати","The report clearly delineated the roles of each team member.","Звіт чітко окреслив ролі кожного члена команди.","/dɪˈlɪnieɪt/"],
  ["elaborate","детально розробляти, докладний","Could you elaborate on your point about market trends?","Чи могли б ви детальніше розповісти про ринкові тенденції?","/ɪˈlæbərət/"],
  ["empirical","емпіричний, заснований на досвіді","The hypothesis must be tested using empirical evidence.","Гіпотезу необхідно перевірити за допомогою емпіричних доказів.","/ɪmˈpɪrɪkəl/"],
  ["erroneous","помилковий, хибний","The article was based on erroneous data and had to be corrected.","Стаття ґрунтувалась на помилкових даних і потребувала виправлення.","/ɪˈrəʊniəs/"],
  ["evasive","ухильний, такий, що уникає","He gave an evasive answer instead of addressing the question directly.","Він дав ухильну відповідь замість того, щоб відповісти прямо.","/ɪˈveɪsɪv/"],
  ["exemplify","ілюструвати, служити прикладом","This painting exemplifies the best qualities of Impressionism.","Ця картина ілюструє найкращі якості імпресіонізму.","/ɪɡˈzemplɪfaɪ/"],
  ["exhaustive","вичерпний, всебічний","The team conducted an exhaustive review of all available data.","Команда провела вичерпний огляд всіх наявних даних.","/ɪɡˈzɔːstɪv/"],
  ["formulate","формулювати, розробляти","It took months to formulate an effective solution to the problem.","Знадобилися місяці, щоб сформулювати ефективне вирішення проблеми.","/ˈfɔːrmjuleɪt/"],
  ["innovative","інноваційний, новаторський","The company is known for its innovative approach to design.","Компанія відома своїм інноваційним підходом до дизайну.","/ˈɪnəveɪtɪv/"],
  ["juxtapose","зіставляти, порівнювати","The article juxtaposes traditional and modern teaching methods.","Стаття зіставляє традиційні та сучасні методи навчання.","/ˌdʒʌkstəˈpəʊz/"],
  ["pragmatic","прагматичний, практичний","We need a pragmatic approach — not just idealistic theories.","Нам потрібен прагматичний підхід, а не лише ідеалістичні теорії.","/præɡˈmætɪk/"],
  ["prevalent","поширений, переважаючий","Smartphone use is now prevalent among all age groups.","Використання смартфонів тепер поширене серед усіх вікових груп.","/ˈprevələnt/"],
  ["proliferate","розмножуватися, швидко поширюватися","Online courses have proliferated in the last few years.","Онлайн-курси стрімко поширилися за останні кілька років.","/prəˈlɪfəreɪt/"],
  ["qualitative","якісний (про аналіз)","The researchers used qualitative methods to gather participant opinions.","Дослідники використали якісні методи для збору думок учасників.","/ˈkwɒlɪtətɪv/"],
  ["quantitative","кількісний (про аналіз)","The study provides quantitative data on consumer spending habits.","Дослідження надає кількісні дані про споживчі звички витрат.","/ˈkwɒntɪtətɪv/"],
  ["ramification","наслідок, розгалуження","The ramifications of this policy change could be far-reaching.","Наслідки цієї зміни політики можуть бути далекосяжними.","/ˌræmɪfɪˈkeɪʃən/"],
  ["resonate","резонувати, відгукуватися","His speech resonated deeply with the young audience.","Його промова глибоко відгукнулася в молодій аудиторії.","/ˈrezəneɪt/"],
  ["rhetoric","риторика, красномовство","Political rhetoric rarely translates into concrete action.","Політична риторика рідко перетворюється на конкретні дії.","/ˈretərɪk/"],
  ["scrutinize","ретельно перевіряти, вивчати","The auditors scrutinized every transaction in the accounts.","Аудитори ретельно перевірили кожну операцію в бухгалтерській звітності.","/ˈskruːtɪnaɪz/"],
  ["seminal","основоположний, вплинувший","This book is considered a seminal work in modern linguistics.","Ця книга вважається основоположною працею в сучасній лінгвістиці.","/ˈsemɪnəl/"],
  ["skeptical","скептичний","Many scientists remain skeptical about the new theory.","Багато вчених залишаються скептичними щодо нової теорії.","/ˈskeptɪkəl/"],
  ["subjective","суб'єктивний","Artistic judgement is always somewhat subjective in nature.","Художнє судження завжди певною мірою суб'єктивне за своєю природою.","/səbˈdʒektɪv/"],
  ["supersede","витісняти, замінювати","Digital technology has superseded many traditional print methods.","Цифрові технології витіснили багато традиційних методів друку.","/ˌsuːpərˈsiːd/"],
  ["synthesize","синтезувати, об'єднувати","The researcher synthesized findings from over fifty different studies.","Дослідник синтезував результати понад п'ятдесяти різних досліджень.","/ˈsɪnθəsaɪz/"],
  ["trajectory","траєкторія, курс розвитку","The company's growth trajectory has been impressive over five years.","Траєкторія зростання компанії була вражаючою протягом п'яти років.","/trəˈdʒektəri/"],
  ["unprecedented","безпрецедентний","The pandemic caused unprecedented disruption to global economies.","Пандемія спричинила безпрецедентні збої в глобальній економіці.","/ʌnˈpresɪdentɪd/"],
  ["validate","підтверджувати, перевіряти","The experiment validated the researchers' original hypothesis.","Експеримент підтвердив початкову гіпотезу дослідників.","/ˈvælɪdeɪt/"],

  // ── 💼 Робота та кар'єра ─────────────────────────────────────
  ["resignation","звільнення, відставка","She handed in her resignation after ten years at the company.","Вона подала заяву про звільнення після десяти років у компанії.","/ˌrezɪɡˈneɪʃən/"],
  ["pension","пенсія","He worked for forty years and now receives a good pension.","Він пропрацював сорок років і тепер отримує хорошу пенсію.","/ˈpenʃən/"],
  ["freelance","фрілансер, на фрілансі","She works as a freelance designer for several clients.","Вона працює дизайнером-фрілансером для кількох клієнтів.","/ˈfriːlɑːns/"],
  ["appraisal","оцінка (роботи), атестація","Her annual appraisal showed she had exceeded all her targets.","Її щорічна атестація показала, що вона перевершила всі свої цілі.","/əˈpreɪzəl/"],
  ["presentation","презентація, доповідь","She gave an excellent presentation to the board of directors.","Вона зробила чудову презентацію перед радою директорів.","/ˌprezənˈteɪʃən/"],

  // ── 💻 Технології та інтернет ─────────────────────────────────
  ["website","вебсайт","Check the company's website for more information about the event.","Перевірте вебсайт компанії для отримання додаткової інформації про захід.","/ˈwebsaɪt/"],
  ["scroll","прокручувати, гортати","She scrolled through her social media feed for twenty minutes.","Вона гортала стрічку соціальних мереж двадцять хвилин.","/skrəʊl/"],
  ["bluetooth","блютус, бездротове з'єднання","Connect the headphones via bluetooth before playing music.","Підключи навушники через блютус перед відтворенням музики.","/ˈbluːtuːθ/"],
  ["coding","кодування, програмування","She spent the evening coding a new feature for the app.","Вона провела вечір, програмуючи нову функцію для застосунку.","/ˈkəʊdɪŋ/"],
  ["hacker","хакер","The company hired an ethical hacker to test its security.","Компанія найняла етичного хакера для перевірки своєї безпеки.","/ˈhækər/"],
  ["virus","вірус (комп'ютерний/біологічний)","A computer virus destroyed all the files on his laptop.","Комп'ютерний вірус знищив усі файли на його ноутбуку.","/ˈvaɪrəs/"],
  ["charger","зарядний пристрій","My phone is dead and I forgot to bring my charger.","Мій телефон розрядився, і я забув взяти зарядний пристрій.","/ˈtʃɑːrdʒər/"],

  // ── 🏥 Здоров'я та медицина ──────────────────────────────────
  ["appointment","прийом (лікаря), зустріч","I have a doctor's appointment at three o'clock tomorrow.","У мене прийом у лікаря о третій годині завтра.","/əˈpɔɪntmənt/"],
  ["pulse","пульс","The nurse checked his pulse and said it was perfectly normal.","Медсестра перевірила його пульс і сказала, що він абсолютно нормальний.","/pʌls/"],
  ["headache","головний біль","I have a terrible headache — I need to take some painkillers.","У мене жахливий головний біль — мені потрібно прийняти знеболювальне.","/ˈhedeɪk/"],
  ["dose","доза","Take one dose of the medicine twice a day after meals.","Приймайте одну дозу ліків двічі на день після їжі.","/dəʊs/"],
  ["clinic","клініка, медичний центр","She went to the clinic for a routine health check-up.","Вона пішла до клініки на плановий медичний огляд.","/ˈklɪnɪk/"],
  ["recovery","одужання, відновлення","His recovery after the operation was faster than expected.","Його відновлення після операції відбулося швидше, ніж очікувалося.","/rɪˈkʌvəri/"],
  ["diabetes","діабет","She was diagnosed with type 2 diabetes at the age of forty.","Їй поставили діагноз цукровий діабет 2 типу у віці сорока років.","/ˌdaɪəˈbiːtiːz/"],

  // ── 🍽️ Їжа та кулінарія ──────────────────────────────────────
  ["ingredient","інгредієнт","The recipe has only five simple ingredients you can find anywhere.","У рецепті лише п'ять простих інгредієнтів, які можна знайти будь-де.","/ɪnˈɡriːdiənt/"],
  ["vegetarian","вегетаріанець, вегетаріанський","She has been vegetarian for three years and feels much healthier.","Вона є вегетаріанкою вже три роки і почувається набагато здоровішою.","/ˌvedʒɪˈteəriən/"],
  ["spicy","гострий, пряний","I love spicy food, but it gives me heartburn sometimes.","Я люблю гостру їжу, але іноді вона викликає у мене печію.","/ˈspaɪsi/"],
  ["flavour","смак, аромат","This soup has a wonderful rich flavour from the herbs.","Цей суп має чудовий насичений смак завдяки травам.","/ˈfleɪvər/"],
  ["portion","порція","The portion sizes at that restaurant are huge.","Розмір порцій у тому ресторані величезний.","/ˈpɔːrʃən/"],
  ["grill","гриль, смажити на грилі","She grilled the vegetables with a little olive oil and salt.","Вона посмажила овочі на грилі з невеликою кількістю оливкової олії і солі.","/ɡrɪl/"],
  ["season","приправляти, сезон","Season the chicken with salt, pepper and garlic before roasting.","Приправ курку сіллю, перцем та часником перед запіканням.","/ˈsiːzən/"],
  ["appetiser","закуска","We ordered a selection of appetisers to share before the main course.","Ми замовили набір закусок, щоб поділитися перед основною стравою.","/ˈæpɪtaɪzər/"],
  ["dessert","десерт","I always save room for dessert — especially chocolate cake.","Я завжди залишаю місце для десерту — особливо для шоколадного торту.","/dɪˈzɜːrt/"],
  ["gluten","глютен","She avoids gluten because she has a severe intolerance to it.","Вона уникає глютену, бо має серйозну непереносимість до нього.","/ˈɡluːtən/"],
  ["organic","органічний","More people are choosing organic produce for health reasons.","Дедалі більше людей обирають органічні продукти з міркувань здоров'я.","/ɔːrˈɡænɪk/"],
  ["protein","протеїн, білок","Eggs, meat and beans are excellent sources of protein.","Яйця, м'ясо та квасоля є чудовими джерелами білка.","/ˈprəʊtiːn/"],
  ["vitamin","вітамін","Oranges are a great source of vitamin C for the immune system.","Апельсини є чудовим джерелом вітаміну C для імунної системи.","/ˈvɪtəmɪn/"],
  ["calorie","калорія","This smoothie contains only 120 calories per serving.","Цей смузі містить лише 120 калорій на порцію.","/ˈkæləri/"],

  // ── ✈️ Подорожі та транспорт ──────────────────────────────────
  ["boarding","посадка (в літак/автобус)","Boarding starts one hour before the scheduled departure time.","Посадка починається за одну годину до запланованого часу відправлення.","/ˈbɔːrdɪŋ/"],
  ["reservation","бронювання, резервація","I made a reservation at the restaurant for seven o'clock.","Я зробив бронювання в ресторані на сьому годину.","/ˌrezəˈveɪʃən/"],
  ["accommodation","житло, проживання","The travel package includes flights and accommodation for seven nights.","Туристичний пакет включає авіаквитки та проживання на сім ночей.","/əˌkɒməˈdeɪʃən/"],
  ["shuttle","шатл, маршрутка","There's a free shuttle bus between the hotel and the airport.","Між готелем та аеропортом курсує безкоштовний шатл-автобус.","/ˈʃʌtəl/"],
  ["platform","платформа (залізнична), майданчик","The train to Paris departs from platform six in ten minutes.","Потяг до Парижа відправляється з шостої платформи за десять хвилин.","/ˈplætfɔːrm/"],
  ["cancel","скасовувати","The flight was cancelled due to severe weather conditions.","Рейс скасували через несприятливі погодні умови.","/ˈkænsəl/"],
  ["turbulence","турбулентність","Passengers were asked to fasten seatbelts due to turbulence.","Пасажирів попросили пристебнути ремені безпеки через турбулентність.","/ˈtɜːrbjuləns/"],
  ["seasick","морська хвороба, у кого нудить на морі","She felt terribly seasick on the ferry crossing the Channel.","Їй було дуже погано від морської хвороби на поромі через Ла-Манш.","/ˈsiːsɪk/"],
  ["insurance","страхування, страховка","Always take out travel insurance before going abroad.","Завжди оформлюй туристичну страховку перед поїздкою за кордон.","/ɪnˈʃʊərəns/"],

  // ── 🌍 Природа та довкілля ────────────────────────────────────
  ["climate","клімат","The climate in the south of the country is warm and dry.","Клімат на півдні країни теплий і сухий.","/ˈklaɪmɪt/"],
  ["pollution","забруднення","Air pollution in big cities is a major health concern.","Забруднення повітря у великих містах є серйозною проблемою для здоров'я.","/pəˈluːʃən/"],
  ["emissions","викиди (парникових газів)","The new law aims to reduce carbon emissions by thirty percent.","Новий закон спрямований на скорочення викидів вуглецю на тридцять відсотків.","/ɪˈmɪʃənz/"],
  ["renewable","відновлювана (енергія)","Solar panels are an excellent source of renewable energy.","Сонячні панелі є чудовим джерелом відновлюваної енергії.","/rɪˈnjuːəbəl/"],
  ["deforestation","вирубка лісів","Deforestation is destroying the natural habitat of many species.","Вирубка лісів руйнує природне середовище існування багатьох видів.","/ˌdiːˌfɒrɪˈsteɪʃən/"],
  ["earthquake","землетрус","A powerful earthquake struck the coastal region last night.","Потужний землетрус вразив прибережний регіон минулої ночі.","/ˈɜːrθkweɪk/"],
  ["tsunami","цунамі","The coastal town was destroyed by a massive tsunami.","Прибережне містечко було знищено масивним цунамі.","/tsuːˈnɑːmi/"],
  ["coral","корал, кораловий","Rising ocean temperatures are killing coral reefs worldwide.","Підвищення температури океану вбиває коралові рифи по всьому світу.","/ˈkɒrəl/"],
  ["sustainable","сталий, збалансований","Sustainable development meets today's needs without harming the future.","Сталий розвиток задовольняє сьогоднішні потреби, не завдаючи шкоди майбутньому.","/səˈsteɪnəbəl/"],
  ["conservation","збереження, охорона природи","Wildlife conservation efforts have helped save several endangered species.","Зусилля з охорони дикої природи допомогли врятувати кілька видів, що перебувають під загрозою.","/ˌkɒnsəˈveɪʃən/"],
  ["endangered","під загрозою зникнення","The giant panda was once critically endangered but numbers have grown.","Велика панда колись перебувала під критичною загрозою зникнення, але популяція зросла.","/ɪnˈdeɪndʒərd/"],
  ["atmosphere","атмосфера","The atmosphere in the old café was warm and welcoming.","Атмосфера в старому кафе була теплою і привітною.","/ˈætməsfɪər/"],
  ["ozone","озон, озоновий шар","The ozone layer protects Earth from harmful ultraviolet radiation.","Озоновий шар захищає Землю від шкідливого ультрафіолетового випромінювання.","/ˈəʊzəʊn/"],
  ["pesticide","пестицид","Farmers are being encouraged to use fewer pesticides on crops.","Фермерів заохочують використовувати менше пестицидів на посівах.","/ˈpestɪsaɪd/"],

  // ── 💛 Емоції та характер ─────────────────────────────────────
  ["frustrated","розчарований, збентежений","She felt frustrated when nobody listened to her suggestions.","Вона відчувала розчарування, коли ніхто не слухав її пропозиції.","/frʌˈstreɪtɪd/"],
  ["ambitious","амбітний, цілеспрямований","He is very ambitious and plans to become CEO within five years.","Він дуже амбітний і планує стати генеральним директором протягом п'яти років.","/æmˈbɪʃəs/"],
  ["pessimistic","песимістичний","She tends to be pessimistic about the future when things go wrong.","Вона схильна до песимізму щодо майбутнього, коли справи йдуть не так.","/ˌpesɪˈmɪstɪk/"],
  ["empathy","емпатія, співпереживання","Good teachers show empathy towards students who are struggling.","Хороші вчителі виявляють емпатію до учнів, які мають труднощі.","/ˈempəθi/"],
  ["enthusiasm","ентузіазм, захоплення","Her enthusiasm for the project inspired the whole team.","Її ентузіазм до проекту надихнув усю команду.","/ɪnˈθjuːziæzəm/"],
  ["loneliness","самотність","Loneliness is a growing problem in many modern cities.","Самотність — це зростаюча проблема в багатьох сучасних містах.","/ˈləʊnlinəs/"],
  ["curiosity","цікавість, допитливість","His curiosity about science led him to become a researcher.","Його цікавість до науки привела його до того, що він став дослідником.","/ˌkjʊəriˈɒsɪti/"],
  ["courage","сміливість, мужність","It takes real courage to speak up when you know something is wrong.","Потрібна справжня сміливість, щоб висловитися, коли знаєш, що щось не так.","/ˈkɜːrɪdʒ/"],
  ["loyalty","лояльність, відданість","She showed great loyalty to her team even during difficult times.","Вона виявила велику відданість своїй команді навіть у важкі часи.","/ˈlɔɪəlti/"],
  ["honesty","чесність","Honesty is the foundation of any strong and lasting relationship.","Чесність — основа будь-яких міцних і тривалих стосунків.","/ˈɒnɪsti/"],
  ["tolerance","толерантність, терпимість","Cultural tolerance is essential in a diverse and multicultural society.","Культурна толерантність необхідна в різноманітному і мультикультурному суспільстві.","/ˈtɒlərəns/"],
  ["excitement","хвилювання, збудження","The children couldn't hide their excitement on Christmas morning.","Діти не могли приховати своє хвилювання вранці на Різдво.","/ɪkˈsaɪtmənt/"],

  // ── A1 basics ────────────────────────────────────────────────
  ["above","вище, над","The plane flew above the clouds for hours.","Літак летів вище хмар кілька годин.","/əˈbʌv/"],
  ["after","після","Let's meet for coffee after work today.","Давай зустрінемося на каву після роботи сьогодні.","/ˈɑːftər/"],
  ["again","знову","Please say that again — I didn't hear you.","Скажи це знову — я тебе не чув.","/əˈɡen/"],
  ["ago","тому","She moved to London three years ago.","Вона переїхала до Лондона три роки тому.","/əˈɡəʊ/"],
  ["all","весь, всі","All the students passed the final exam.","Всі студенти здали фінальний іспит.","/ɔːl/"],
  ["also","також","He speaks French and also knows some Italian.","Він розмовляє французькою і також знає трохи італійської.","/ˈɔːlsəʊ/"],
  ["always","завжди","She always drinks a cup of tea in the morning.","Вона завжди п'є чашку чаю вранці.","/ˈɔːlweɪz/"],
  ["answer","відповідь, відповідати","Please answer the question in complete sentences.","Будь ласка, відповідай на питання повними реченнями.","/ˈɑːnsər/"],
  ["any","будь-який, жодний","Do you have any questions before we begin?","У вас є будь-які запитання перед початком?","/ˈeni/"],
  ["ask","запитувати","Don't be afraid to ask for help when you need it.","Не бійся просити про допомогу, коли вона тобі потрібна.","/ɑːsk/"],
  ["away","далеко, геть","The nearest supermarket is only five minutes away.","Найближчий супермаркет лише за п'ять хвилин.","/əˈweɪ/"],
  ["bad","поганий","The weather was so bad that we stayed inside all day.","Погода була настільки погана, що ми провели весь день вдома.","/bæd/"],
  ["ball","м'яч","The children kicked the ball around the garden.","Діти ганяли м'яч по саду.","/bɔːl/"],
  ["because","тому що","I stayed home because I was feeling sick.","Я залишився вдома, тому що погано себе почував.","/bɪˈkɒz/"],
  ["big","великий","They live in a big house near the park.","Вони живуть у великому будинку біля парку.","/bɪɡ/"],
  ["black","чорний","She always wears black clothes to work.","Вона завжди носить чорний одяг на роботу.","/blæk/"],
  ["blue","синій, блакитний","The sky is a beautiful clear blue today.","Небо сьогодні прекрасне і ясно-блакитне.","/bluː/"],
  ["bread","хліб","She baked fresh bread every morning for the family.","Вона пекла свіжий хліб щоранку для родини.","/bred/"],
  ["brown","коричневий","He has brown hair and green eyes.","У нього коричневе волосся і зелені очі.","/braʊn/"],
  ["call","дзвонити, називати","I'll call you tomorrow morning to confirm the plan.","Я подзвоню тобі завтра вранці, щоб підтвердити план.","/kɔːl/"],
  ["class","клас, урок","The class starts at nine o'clock every weekday.","Урок починається о дев'ятій щодня крім вихідних.","/klɑːs/"],
  ["clean","чистий, прибирати","Please keep your room clean and tidy at all times.","Будь ласка, тримай свою кімнату чистою і охайною.","/kliːn/"],
  ["clock","годинник","The clock on the wall shows the wrong time.","Годинник на стіні показує неправильний час.","/klɒk/"],
  ["close","закривати, близький","Please close the window — it's getting cold.","Будь ласка, закрий вікно — стає холодно.","/kləʊz/"],
  ["come","приходити, приїжджати","Can you come to the party on Saturday evening?","Ти можеш прийти на вечірку в суботу ввечері?","/kʌm/"],
  ["cut","різати, скорочувати","Be careful when you cut vegetables with a sharp knife.","Будь обережним, коли ріжеш овочі гострим ножем.","/kʌt/"],
  ["dad","тато","My dad taught me how to ride a bicycle.","Мій тато навчив мене їздити на велосипеді.","/dæd/"],
  ["door","двері","Please lock the door when you leave the house.","Будь ласка, замкни двері, коли виходиш з дому.","/dɔːr/"],
  ["down","вниз, донизу","The cat jumped down from the high shelf.","Кіт зістрибнув вниз з високої полиці.","/daʊn/"],
  ["draw","малювати, рисувати","She loves to draw portraits of her friends.","Вона обожнює малювати портрети своїх друзів.","/drɔː/"],
  ["drink","пити, напій","Would you like something to drink with your meal?","Бажаєте щось випити до їжі?","/drɪŋk/"],
  ["drive","їздити, водити","He learned to drive a car when he was eighteen.","Він навчився водити машину, коли йому було вісімнадцять.","/draɪv/"],
  ["eat","їсти","We usually eat dinner together as a family.","Ми зазвичай їмо вечерю разом як родина.","/iːt/"],
  ["egg","яйце","I had two fried eggs for breakfast this morning.","Сьогодні вранці я з'їв два яйця на сніданок.","/eɡ/"],
  ["eight","вісім","The meeting starts at eight o'clock in the morning.","Нарада починається о восьмій годині ранку.","/eɪt/"],
  ["enjoy","насолоджуватися","I really enjoy reading books on rainy afternoons.","Я дуже люблю читати книги в дощові пополудні.","/ɪnˈdʒɔɪ/"],
  ["every","кожен, кожна","She goes for a walk every morning before breakfast.","Вона ходить на прогулянку щоранку перед сніданком.","/ˈevri/"],
  ["far","далеко, далекий","Is the train station far from the city centre?","Чи далеко залізнична станція від центру міста?","/fɑːr/"],
  ["fast","швидкий, швидко","The cheetah is the fastest land animal in the world.","Гепард — найшвидша наземна тварина у світі.","/fɑːst/"],
  ["feel","відчувати, почуватися","I feel much better after a good night's sleep.","Я почуваюся набагато краще після хорошого нічного сну.","/fiːl/"],
  ["find","знаходити","Can you help me find my keys? I lost them again.","Можеш допомогти мені знайти ключі? Я знову їх загубив.","/faɪnd/"],
  ["five","п'ять","We have five minutes left before the class ends.","У нас залишилося п'ять хвилин до кінця уроку.","/faɪv/"],
  ["food","їжа","This restaurant serves excellent food at fair prices.","Цей ресторан подає чудову їжу за помірними цінами.","/fuːd/"],
  ["four","чотири","The package should arrive in four to five business days.","Посилка має прийти за чотири-п'ять робочих дні.","/fɔːr/"],
  ["fruit","фрукт","Eating fresh fruit every day is good for your health.","Їсти свіжі фрукти щодня корисно для здоров'я.","/fruːt/"],
  ["fun","веселощі, цікавий","We had so much fun at the beach last weekend.","Ми так добре повеселилися на пляжі минулого вікенду.","/fʌn/"],
  ["game","гра","The children played a board game after dinner.","Діти зіграли в настільну гру після вечері.","/ɡeɪm/"],
  ["give","давати, подарувати","Please give me a few minutes to think about it.","Будь ласка, дай мені кілька хвилин подумати.","/ɡɪv/"],
  ["go","йти, їхати","Let's go to the cinema tonight — there's a great film.","Ходімо в кіно сьогодні ввечері — там чудовий фільм.","/ɡəʊ/"],
  ["good","хороший, добрий","She is a very good teacher who explains clearly.","Вона дуже хороший вчитель, який пояснює зрозуміло.","/ɡʊd/"],
  ["great","чудовий, великий","That was a great idea — everyone loved it.","Це була чудова ідея — всім вона сподобалась.","/ɡreɪt/"],
  ["green","зелений","The park is full of beautiful green trees in summer.","Парк влітку повний красивих зелених дерев.","/ɡriːn/"],
  ["grow","рости, вирощувати","Children grow so fast — she's already taller than me.","Діти ростуть так швидко — вона вже вища за мене.","/ɡrəʊ/"],
  ["head","голова","She shook her head to say no to the offer.","Вона похитала головою на знак відмови від пропозиції.","/hed/"],
  ["hear","чути","I can't hear you — please speak a little louder.","Я не чую тебе — говори, будь ласка, трохи голосніше.","/hɪər/"],
  ["hello","привіт","Hello! My name is Anna. Nice to meet you.","Привіт! Мене звати Анна. Приємно познайомитися.","/həˈləʊ/"],
  ["help","допомагати, допомога","Could you please help me carry these heavy bags?","Чи не міг би ти допомогти мені нести ці важкі сумки?","/help/"],
  ["here","тут, сюди","Please come here and look at this together.","Будь ласка, підійди сюди і подивися на це разом зі мною.","/hɪər/"],
  ["high","високий, вгорі","The eagle flew high above the mountain peaks.","Орел летів високо над вершинами гір.","/haɪ/"],
  ["hot","гарячий, спекотний","It's too hot to go outside in the afternoon today.","Сьогодні вдень надто спекотно, щоб виходити надвір.","/hɒt/"],
  ["jump","стрибати, стрибок","The dog jumped over the fence with ease.","Пес легко перестрибнув через паркан.","/dʒʌmp/"],
  ["keep","тримати, зберігати","Please keep this information private — don't tell anyone.","Будь ласка, тримай цю інформацію в секреті.","/kiːp/"],
  ["know","знати","Do you know where the nearest pharmacy is?","Ти знаєш, де знаходиться найближча аптека?","/nəʊ/"],
  ["learn","вчитися, дізнаватися","It takes time to learn a new language well.","Потрібен час, щоб добре вивчити нову мову.","/lɜːrn/"],
  ["let","дозволяти, дати змогу","Let me know if you need any help with the project.","Дай мені знати, якщо тобі потрібна допомога з проектом.","/let/"],
  ["light","світло, легкий","Please turn on the light — it's getting dark outside.","Увімкни, будь ласка, світло — надворі темніє.","/laɪt/"],
  ["listen","слухати","Please listen carefully to the instructions before you start.","Будь ласка, уважно прослухай інструкції перед початком.","/ˈlɪsən/"],
  ["little","маленький, трохи","A little patience goes a long way in difficult situations.","Трохи терпіння допомагає в складних ситуаціях.","/ˈlɪtl/"],
  ["live","жити","They live in a small apartment near the city centre.","Вони живуть у маленькій квартирі біля центру міста.","/lɪv/"],
  ["long","довгий, довго","The meeting was so long that everyone felt tired.","Нарада була настільки довгою, що всі втомилися.","/lɒŋ/"],
  ["meat","м'ясо","I don't eat meat — I've been a vegetarian for five years.","Я не їм м'яса — я вегетаріанець вже п'ять років.","/miːt/"],
  ["meet","зустрічати, познайомитися","I'd love to meet your family at the party.","Я б хотів познайомитися з твоєю родиною на вечірці.","/miːt/"],
  ["nice","приємний, гарний","What a nice surprise — I didn't expect to see you here!","Який приємний сюрприз — я не очікував тебе тут побачити!","/naɪs/"],
  ["nine","дев'ять","The library closes at nine o'clock in the evening.","Бібліотека зачиняється о дев'ятій годині вечора.","/naɪn/"],
  ["number","число, номер","Can I have your phone number so I can call you?","Можеш дати мені свій номер телефону, щоб я міг зателефонувати?","/ˈnʌmbər/"],
  ["old","старий, літній","My grandmother is eighty years old and still very active.","Моїй бабусі вісімдесят років, і вона все ще дуже активна.","/əʊld/"],
  ["open","відкривати, відкритий","Please open the window — the room needs some fresh air.","Будь ласка, відкрий вікно — в кімнаті потрібно свіже повітря.","/ˈəʊpən/"],
  ["orange","апельсин, помаранчевий","She drinks a glass of fresh orange juice every morning.","Вона щоранку п'є склянку свіжовичавленого апельсинового соку.","/ˈɒrɪndʒ/"],
  ["page","сторінка","Please turn to page fifteen in your textbook now.","Будь ласка, відкрийте п'ятнадцяту сторінку у вашому підручнику.","/peɪdʒ/"],
  ["pen","ручка","Could I borrow your pen to sign this document?","Можу я позичити твою ручку, щоб підписати цей документ?","/pen/"],
  ["picture","картина, фото","She painted a beautiful picture of the sunset.","Вона намалювала красиву картину заходу сонця.","/ˈpɪktʃər/"],
  ["play","грати, п'єса","The children love to play outside after school.","Діти люблять гратися надворі після школи.","/pleɪ/"],
  ["police","поліція","The police arrived at the scene within minutes.","Поліція прибула на місце події за кілька хвилин.","/pəˈliːs/"],
  ["rain","дощ, іти (про дощ)","It started to rain just as we left the house.","Почався дощ якраз тоді, коли ми вийшли з дому.","/reɪn/"],
  ["read","читати","I like to read a chapter of my book before bed.","Я люблю читати розділ книги перед сном.","/riːd/"],
  ["red","червоний","She wore a beautiful red dress to the party.","Вона прийшла на вечірку в красивій червоній сукні.","/red/"],
  ["ride","їхати, кататися","I ride my bicycle to work every day to stay fit.","Я щодня їжджу на роботу на велосипеді, щоб бути у формі.","/raɪd/"],
  ["road","дорога","The road was closed because of roadworks for a week.","Дорогу перекрили через дорожні роботи на тиждень.","/rəʊd/"],
  ["room","кімната","The hotel room had a wonderful view of the ocean.","Готельний номер мав чудовий вид на океан.","/ruːm/"],
  ["run","бігти, бігати","She runs five kilometres every morning before breakfast.","Вона бігає п'ять кілометрів щоранку до сніданку.","/rʌn/"],
  ["say","говорити, казати","What did she say about the new project plan?","Що вона сказала про новий план проекту?","/seɪ/"],
  ["see","бачити","Can you see the mountains from your apartment window?","Чи видно гори з вікна твоєї квартири?","/siː/"],
  ["seven","сім","There are seven days in a week and four weeks in a month.","У тижні сім днів і чотири тижні в місяці.","/ˈsevən/"],
  ["short","короткий, невисокий","The film was only ninety minutes — quite short for a thriller.","Фільм тривав лише дев'яносто хвилин — досить коротко для трилера.","/ʃɔːrt/"],
  ["sing","співати","She sings in a local choir every weekend.","Вона співає в місцевому хорі кожні вихідні.","/sɪŋ/"],
  ["six","шість","We need six chairs for the dinner table tonight.","Нам потрібно шість стільців для обіднього столу сьогодні ввечері.","/sɪks/"],
  ["sleep","спати, сон","Adults need at least seven to eight hours of sleep.","Дорослим потрібно принаймні сім-вісім годин сну.","/sliːp/"],
  ["small","маленький, невеликий","The café is small but very cosy and welcoming.","Кав'ярня маленька, але дуже затишна і привітна.","/smɔːl/"],
  ["smile","посміхатися, посмішка","Her warm smile made everyone feel welcome immediately.","Її тепла посмішка змусила всіх відразу відчути себе бажаними.","/smaɪl/"],
  ["snow","сніг, іти (про сніг)","It snowed all night and the streets were completely white.","Сніг ішов усю ніч, і вулиці стали повністю білими.","/snəʊ/"],
  ["sport","спорт","Playing sport regularly is great for your health.","Регулярні заняття спортом чудово впливають на здоров'я.","/spɔːrt/"],
  ["spring","весна","The flowers begin to bloom in spring after the long winter.","Квіти починають цвісти навесні після довгої зими.","/sprɪŋ/"],
  ["star","зірка","You can see thousands of stars in the sky on a clear night.","В ясну ніч на небі можна побачити тисячі зірок.","/stɑːr/"],
  ["stay","залишатися","Would you like to stay for dinner with us tonight?","Хочеш залишитися на вечерю з нами сьогодні?","/steɪ/"],
  ["stop","зупинятися, зупинка","The bus stops right outside the school entrance.","Автобус зупиняється прямо біля входу до школи.","/stɒp/"],
  ["strong","сильний, міцний","You need to be strong both mentally and physically.","Потрібно бути сильним як розумово, так і фізично.","/strɒŋ/"],
  ["sugar","цукор","Do you take sugar in your coffee or do you drink it black?","Ти кладеш цукор у каву чи п'єш її без цукру?","/ˈʃʊɡər/"],
  ["swim","плавати, купатися","She learned to swim when she was only four years old.","Вона навчилася плавати, коли їй було лише чотири роки.","/swɪm/"],
  ["talk","розмовляти, говорити","We need to talk about what happened at the meeting.","Нам потрібно поговорити про те, що сталося на нараді.","/tɔːk/"],
  ["tall","високий","He is the tallest player on the basketball team.","Він найвищий гравець у баскетбольній команді.","/tɔːl/"],
  ["ten","десять","I'll be ready in ten minutes — just give me a moment.","Я буду готовий через десять хвилин — дай мені хвилинку.","/ten/"],
  ["think","думати, вважати","I think we should leave early to avoid the traffic.","Я думаю, що нам варто виїхати раніше, щоб уникнути пробок.","/θɪŋk/"],
  ["three","три","She has lived in three different countries in her life.","Вона жила у трьох різних країнах протягом свого життя.","/θriː/"],
  ["today","сьогодні","Today is a perfect day to go for a walk in the park.","Сьогодні ідеальний день для прогулянки в парку.","/təˈdeɪ/"],
  ["together","разом","Let's work together to find the best solution.","Давай працювати разом, щоб знайти найкраще рішення.","/təˈɡeðər/"],
  ["town","місто (невелике)","She grew up in a small town in the countryside.","Вона виросла в маленькому містечку в сільській місцевості.","/taʊn/"],
  ["try","намагатися, спробувати","Always try your best even when things feel difficult.","Завжди намагайся робити все від тебе можливе навіть у складних ситуаціях.","/traɪ/"],
  ["two","два","She has two brothers and one younger sister.","У неї два брати і одна молодша сестра.","/tuː/"],
  ["umbrella","парасоля","Don't forget to take your umbrella — it looks like rain.","Не забудь взяти парасолю — схоже, буде дощ.","/ʌmˈbrelə/"],
  ["walk","ходити, прогулянка","We went for a long walk along the river on Sunday.","Ми пішли на довгу прогулянку вздовж річки в неділю.","/wɔːk/"],
  ["white","білий","She wrote on the whiteboard with a blue marker pen.","Вона писала на дошці синім маркером.","/waɪt/"],
  ["window","вікно","The cat likes to sit by the window and watch birds.","Кіт любить сидіти біля вікна і спостерігати за птахами.","/ˈwɪndəʊ/"],
  ["word","слово","I learned a new word in English every day this month.","Цього місяця я вивчав нове англійське слово щодня.","/wɜːrd/"],
  ["work","працювати, робота","She works hard every day to achieve her goals.","Вона щодня наполегливо працює, щоб досягти своїх цілей.","/wɜːrk/"],
  ["world","світ","Travelling the world is her biggest dream in life.","Подорожувати світом — її найбільша мрія в житті.","/wɜːrld/"],
  ["write","писати","She writes in her diary every evening before bed.","Вона щовечора пише у своєму щоденнику перед сном.","/raɪt/"],
  ["yellow","жовтий","The sunflowers in the field were bright yellow.","Соняшники на полі були яскраво-жовтими.","/ˈjeləʊ/"],
  ["young","молодий","He is young but very experienced for his age.","Він молодий, але дуже досвідчений для свого віку.","/jʌŋ/"],
  ["zero","нуль, нуль","The temperature dropped to zero degrees overnight.","Температура вночі опустилася до нуля градусів.","/ˈzɪərəʊ/"],
];

// ── Read & parse current words.js ─────────────────────────────
const raw = readFileSync(wordsPath, 'utf8');
// File format: export const W=[...];
const startIdx = raw.indexOf('[');
const endIdx   = raw.lastIndexOf(']') + 1;
const arrStr   = raw.slice(startIdx, endIdx);
const current  = JSON.parse(arrStr);

// ── Merge (deduplicate by lowercase english) ──────────────────
const existingSet = new Set(current.map(w => w[0].toLowerCase()));
const toAdd = NEW_WORDS.filter(w => !existingSet.has(w[0].toLowerCase()));

const merged = [...current, ...toAdd];

// ── Sort alphabetically by english word ───────────────────────
merged.sort((a, b) => a[0].toLowerCase().localeCompare(b[0].toLowerCase()));

// ── Write back ────────────────────────────────────────────────
const prefix = raw.slice(0, startIdx);
const suffix = raw.slice(endIdx);
const newContent = prefix + JSON.stringify(merged) + suffix;
writeFileSync(wordsPath, newContent, 'utf8');

console.log(`✅ Added ${toAdd.length} new words (skipped ${NEW_WORDS.length - toAdd.length} duplicates).`);
console.log(`📚 Total words now: ${merged.length}`);
if (toAdd.length > 0) {
  console.log('New words added:', toAdd.map(w => w[0]).join(', '));
}
