import { W } from '../data/words.js';
const have = new Set(W.map(w => w[0].toLowerCase()));

// Expanded Oxford 5000 word list by CEFR level
const OXFORD = {
  A1: [
    'apple','baby','bag','bath','bed','bike','bird','boat','book','box','boy',
    'bread','brother','car','cat','chair','child','city','class','cold','come',
    'cook','cup','cut','dance','day','door','draw','dream','drink','drive','drop',
    'dry','eat','eye','face','fall','farm','feel','fire','fish','fly','foot',
    'friend','fun','game','garden','girl','give','glass','hand','head','heart',
    'home','horse','hot','house','idea','jump','keep','kid','know','large',
    'last','later','learn','leg','let','life','light','listen','little','live',
    'long','love','make','man','meal','milk','miss','money','more','mountain',
    'mouth','move','much','music','name','new','night','nose','now','number',
    'often','open','out','outside','page','park','part','pay','place','plant',
    'play','point','put','rain','read','right','road','room','run','school',
    'see','set','short','sister','sit','sky','sleep','slow','small','soft',
    'start','stop','story','study','sun','swim','table','take','talk','town',
    'tree','turn','under','use','village','walk','watch','water','way','well',
    'win','window','woman','word','write','year',
  ],
  A2: [
    'able','accept','across','active','activity','actually','adult','advice',
    'afternoon','age','agree','airport','almost','alone','along','although',
    'amount','angry','animal','another','answer','appear','area','around',
    'arrive','attack','autumn','available','awful','balance','beautiful',
    'become','before','behind','belong','below','benefit','best','better',
    'body','both','bottom','bring','business','call','camp','capture','cause',
    'centre','chance','change','character','charge','check','climb','close',
    'clothes','club','collect','colour','comfort','common','community','compare',
    'condition','confident','connect','continue','cross','decide','deep',
    'deliver','depend','describe','detail','different','direction','dirty',
    'discuss','divide','dress','during','early','earn','easy','either','empty',
    'enjoy','enough','enter','especially','even','evening','event','every',
    'everyone','example','except','exercise','explain','explore','extra','fail',
    'familiar','famous','fast','final','follow','force','forward','free','fresh',
    'front','full','future','glad','goal','good','grow','guess','guide',
    'happen','happy','hard','hear','herself','himself','hold','holiday','hope',
    'hour','hurt','image','include','individual','inside','instead','interest',
    'issue','join','kind','knock','land','late','lead','leave','level','lift',
    'likely','line','list','look','loud','lucky','machine','main','manage',
    'map','mark','maybe','mean','meet','message','middle','mine','minute',
    'modern','mother','must','near','need','next','nice','north','nothing',
    'notice','offer','often','old','once','only','opinion','opposite','order',
    'other','own','pass','past','people','perhaps','person','phone','pick',
    'please','plus','popular','position','possible','practice','problem',
    'process','programme','project','put','quite','reach','ready','real',
    'reason','receive','recent','record','remember','repeat','reply','rest',
    'result','return','rich','safe','same','save','second','seem','send',
    'shape','share','show','sign','similar','since','situation','size','skill',
    'smile','social','some','soon','sorry','south','speak','spend','sport',
    'stay','step','still','street','strong','subject','sure','system','theme',
    'themselves','tired','together','touch','trouble','true','try','view',
    'voice','want','warm','week','while','whole','wide','without','worry',
    'worth','young',
  ],
  B1: [
    'abandon','absence','absolute','access','accurate','acquire','adjust',
    'affect','agency','alike','allow','alongside','alternative','analyse',
    'announce','anxious','appropriate','approve','aspect','assess','assist',
    'associate','attitude','attract','aware','award','basis','border',
    'capable','capture','career','carry','category','challenge','channel',
    'chart','circumstances','cite','claim','clarify','classic','comfortable',
    'comment','commit','communicate','complex','concentrate','conclude',
    'consequence','considerable','consist','context','contrast','contribute',
    'convention','convince','correspond','creative','critical','currently',
    'damage','deadline','declaration','define','demonstrate','deny','determined',
    'difficulty','diplomatic','document','dominant','efficient','eliminate',
    'emotional','emphasis','enable','encourage','engage','evaluate','evidence',
    'evident','exceed','exclude','explicit','expose','extensive','factor',
    'failure','feature','focus','formal','fundamental','generate','global',
    'gradually','grant','guarantee','handle','identify','impact','indicate',
    'influence','informal','initially','integrate','intense','intention',
    'investigate','justify','key','launch','lead','link','major','material',
    'mechanism','motivate','negative','neutral','obtain','obvious','occur',
    'oppose','option','overcome','participate','perspective','potential',
    'predict','prefer','previous','principle','priority','process','profession',
    'prohibit','promote','propose','protection','prove','pursue','raise',
    'react','recognize','reduce','reform','region','regulate','reject','relate',
    'reliable','represent','role','seek','select','separate','significant',
    'solve','specific','statement','status','strategy','structure','submit',
    'succeed','survey','task','threat','unique','update','various','version',
    'vital',
    // extra B1 Oxford 5000
    'acknowledge','adapt','administration','agenda','apparently','application',
    'appreciate','approximately','assume','basis','colleague','considerable',
    'consistent','construction','consultation','controversial','conventional',
    'corporation','debate','decade','decline','despite','destination','distinct',
    'diversity','domestic','economy','effective','election','emerge','employ',
    'enforce','enterprise','environment','establish','estimate','ethics',
    'examine','exception','expectation','expand','facility','framework',
    'highlight','immediately','impact','implement','imply','impose','index',
    'infrastructure','initiative','instance','institution','interaction',
    'interpretation','investment','limit','local','maintain','majority',
    'maximum','minimum','network','objective','obtain','organisation','outcome',
    'output','participant','partnership','perform','period','perspective',
    'phase','policy','population','potential','previous','procedure','produce',
    'publish','quality','ratio','rely','remove','require','resource','respond',
    'scheme','sector','sequence','significant','source','specific','statistics',
    'sufficient','summary','target','technique','technology','tradition',
    'transfer','undergo','valid','whereas',
  ],
  B2: [
    'absorb','accomplish','accumulate','acknowledge','adequate','advocate',
    'allocate','ambition','anticipate','apparent','arbitrary','assert',
    'attribute','authority','autonomy','boost','catalyst','collaborate',
    'competent','compile','compose','compromise','concede','conduct','confront',
    'consensus','constraint','coordinate','cultivate','dedicate','deliberate',
    'designate','devote','diminish','distinction','distribute','diverse',
    'dynamic','elaborate','emerge','emphasise','ensure','exclude','facilitate',
    'implement','imply','incentive','incorporate','initiate','interpret',
    'maximize','minimize','monitor','negotiate','objective','perceive',
    'persist','phase','precede','preliminary','prioritise','proportion',
    'prospect','refine','reinforce','remedy','restrict','retain','revenue',
    'revise','scope','specify','stabilise','subsequent','substantial',
    'supplement','sustain','tolerate','transition','undergo','utilise',
    'validate','verify','whereas',
    // extra B2
    'abstract','adjacent','aggregate','albeit','ambiguous','analogy',
    'aspiration','assertion','coherent','comprehensive','concurrent',
    'confine','contradiction','controversial','criterion','deduce','depict',
    'derive','differentiate','discrepancy','disparity','distinction','embed',
    'empirical','enforce','equivalent','explicit','fluctuate','forthcoming',
    'hierarchy','implicit','inconsistency','indispensable','inhibit','insight',
    'integral','intrinsic','invoke','irrelevant','justify','legitimate',
    'mitigate','moreover','nonetheless','nonetheless','notion','orient',
    'overlap','predominant','presume','prohibit','reinstate','render',
    'resolution','retain','rigid','simulate','straightforward','subordinate',
    'supplement','suppress','sustain','terminate','unanimous','underlying',
    'unify','violate','widespread',
  ],
  C1: [
    'abstain','alleviate','ambivalent','articulate','astute','augment',
    'brevity','circumvent','clandestine','coerce','concur','conjecture',
    'consolidate','contemplate','contend','curtail','daunting','debilitating',
    'defer','delve','deplete','discern','disseminate','eloquent','exacerbate',
    'exemplify','expedite','formidable','foster','gauge','harbour','impede',
    'inaugurate','incline','induce','inhibit','innate','invoke','juxtapose',
    'lucid','meticulous','mitigate','nuance','obscure','perpetuate','plausible',
    'postulate','pragmatic','precipitate','predominant','proliferate','prompt',
    'rational','reconcile','scrutinise','sparse','speculate','substantiate',
    'supersede','suppress','tangible','transcend','undermine','unprecedented',
    'vague','yield',
    // extra C1
    'accentuate','acrimony','adamant','adhere','adjacent','admonish',
    'adversarial','aggravate','allude','ambivalent','analogous','anomaly',
    'antagonise','appease','apprehensive','arduous','articulate','assimilate',
    'atrocity','austere','belittle','benevolent','bolster','candid','catalyst',
    'chronic','circumspect','clamour','coercive','cogent','coherent',
    'complacent','conciliate','condescend','conjure','conscientious','contempt',
    'contentious','contradict','culminate','cynical','defiant','deliberate',
    'delineate','deplete','despondent','detrimental','devious','diffuse',
    'diligent','discredit','disdain','dismantle','dispel','disregard',
    'dissent','elusive','empower','encompass','endorse','enigmatic','entail',
    'erode','escalate','exacerbate','exert','explicit','exploit','fragile',
    'fruitless','futile','groundbreaking','hypothetical','imminent','impartial',
    'impending','indeterminate','indifferent','infer','inherent','integral',
    'intractable','irreversible','isolate','legitimate','lenient','lucrative',
    'manifest','meticulous','mitigate','mobilise','momentous','negate',
    'negligible','notoriety','nuanced','oblivious','obsolete','omit',
    'opportune','optimise','ostracise','outweigh','paramount','partisan',
    'patronise','pernicious','persevere','pertinent','plausible','precarious',
    'prestigious','prevail','profound','proliferate','proportionate','provoke',
    'prudent','radical','reassert','rectify','refute','relentless','reluctant',
    'remedy','rigorous','robust','sceptical','scrutiny','sporadic','stagnate',
    'steadfast','stringent','subjective','subtle','tenacious','transparent',
    'turbulent','unequivocal','unprecedented','versatile','viable','volatile',
    'wary','zealous',
  ],
  C2: [
    'accolade','acquiesce','adamantine','adroit','affable','aggrandise',
    'alacrity','anachronism','ancillary','annihilate','antithesis','apocryphal',
    'approbation','arcane','ardour','assiduous','atone','audacious','auspicious',
    'bellicose','benign','bequeath','bombastic','candour','castigate','caveat',
    'chicanery','circumlocution','clemency','coalesce','cognisant','compunction',
    'confound','convoluted','culpable','cupidity','deference','delinquent',
    'delusion','denunciation','depravity','desolate','desultory','diffidence',
    'dilettante','disaffected','disenfranchise','disillusion','disparage',
    'dissemble','duplicity','ebullient','efficacy','effusive','egregious',
    'elicit','embroil','empiricism','endemic','engender','ephemeral',
    'equivocate','erudite','esoteric','estrange','euphemism','evasive',
    'exonerate','expedient','facetious','fallacious','fastidious','fervent',
    'flippant','furtive','garrulous','grandeur','gratuitous','guileless',
    'hubris','hyperbole','iconoclast','impeccable','inadvertent','incisive',
    'incoherent','incongruous','indignant','indolent','inexorable','insolent',
    'intransigent','irrefutable','laconic','lampoon','lethargic','litigious',
    'magnanimous','malevolent','mendacious','mercurial','munificent','myopic',
    'nefarious','nihilism','obsequious','obstinate','obtuse','odious',
    'omnipotent','onerous','ostentatious','parochial','pedantic','perfidious',
    'placate','polemic','pompous','pragmatism','precipitous','preposterous',
    'presuppose','procrastinate','profligate','prolific','proverbial',
    'provocateur','punitive','quandary','querulous','rapacious','reclusive',
    'recondite','recrimination','redress','repudiate','reticent','rhetoric',
    'sagacious','sanctimonious','sardonic','scrupulous','serendipity',
    'solicitous','sophistry','spurious','stoic','subversive','sycophant',
    'taciturn','temerity','tenuous','torpid','transgress','treacherous',
    'truculent','ubiquitous','unscrupulous','vacillate','vehement','venerate',
    'verbose','vindicate','visceral','volatile','wanton','whimsical','zealotry',
  ],

  // ── Oxford 5000 common collocations & expressions ─────────────
  expressions: [
    'as a result','at least','as well as','in addition','in order to',
    'in terms of','on the other hand','in fact','in general','as long as',
    'at the same time','in particular','in practice','on behalf of',
    'in spite of','regardless of','with regard to','as a whole',
    'in the long run','on a regular basis',
  ],

  // ── Oxford 5000 extra verbs (B1-C1) ──────────────────────────
  verbs2: [
    'acknowledge','acquire','advocate','allocate','alter','anticipate',
    'assemble','boost','clarify','collaborate','compile','confront',
    'contrast','deduce','depict','derive','devise','differentiate',
    'discourage','disguise','disrupt','distinguish','elaborate','embed',
    'emerge','enable','enforce','enhance','ensure','entail','equip',
    'exceed','exchange','exclude','exhibit','expand','exploit','expose',
    'facilitate','fluctuate','foster','gauge','generate','highlight',
    'implement','impose','incorporate','indicate','induce','inhibit',
    'initiate','insert','inspect','insist','instruct','interpret',
    'justify','launch','locate','maintain','modify','monitor','motivate',
    'neglect','negotiate','notify','obtain','operate','organise','overcome',
    'perceive','permit','persist','predict','preserve','prevent','proceed',
    'prohibit','promote','propose','pursue','react','reinforce','relate',
    'rely','remove','replace','represent','require','resist','respond',
    'restrict','retain','reveal','review','revise','satisfy','select',
    'specify','submit','suppress','sustain','target','transform','undergo',
    'undermine','update','utilise','validate','verify','violate','yield',
  ],

  // ── Oxford 5000 extra nouns (B1-C1) ──────────────────────────
  nouns2: [
    'absence','abundance','accommodation','accuracy','acquisition',
    'adaptation','administration','adolescence','adoption','agenda',
    'allegation','alliance','allocation','allowance','ambiguity',
    'analysis','anticipation','approval','assessment','assumption',
    'breakdown','campaign','capability','capacity','casualty',
    'clarification','classification','collaboration','commitment',
    'commodity','compensation','complexity','component','conflict',
    'confrontation','consensus','constraint','consumption','convention',
    'conviction','cooperation','coordination','corporation','corruption',
    'creativity','credibility','criterion','cultivation','debate',
    'deception','deficiency','deficit','delay','delegation','dependence',
    'destination','deterioration','deviation','dialogue','dilemma',
    'dimension','disorder','disruption','distinction','distortion',
    'documentation','dominance','drawback','duration','economy',
    'eligibility','emergence','emphasis','endorsement','engagement',
    'enterprise','entity','environment','exception','exclusion',
    'execution','exemption','expectation','expertise','exposure',
    'extension','flexibility','fluctuation','framework','frequency',
    'fulfilment','governance','generation','globalisation','implication',
    'incentive','inconsistency','independence','infrastructure',
    'initiation','innovation','input','integration','investigation',
    'justification','mechanism','migration','modification','momentum',
    'motivation','obligation','obstacle','participation','perception',
    'perspective','prevalence','procedure','qualification','rationale',
    'regulation','reinforcement','rejection','relevance','reputation',
    'resentment','restriction','retention','scrutiny','sequence',
    'shortage','simulation','specification','stereotype','stimulation',
    'strategy','subordination','substitution','transition','transparency',
    'trigger','variation','verification','vulnerability',
  ],

  // ── Oxford 5000 extra adjectives (B1-C1) ─────────────────────
  adjectives2: [
    'abstract','acute','additional','adverse','aggregate','ambitious',
    'analogous','anonymous','arbitrary','artificial','authoritative',
    'autonomous','beneficial','biased','characteristic','chronic',
    'circular','coherent','collaborative','collective','compact',
    'compatible','concurrent','confidential','consistent','contemporary',
    'controversial','credible','cumulative','decisive','defensive',
    'definitive','deliberate','dependent','derived','digital','discrete',
    'discriminatory','dispersed','distinctive','distributed','efficient',
    'eligible','empirical','enormous','essential','ethical','evident',
    'evolutionary','exclusive','explicit','external','extreme','factual',
    'fragile','functional','genuine','hierarchical','identical','immediate',
    'implicit','incentive','inevitable','integral','intensive','intermediate',
    'intrinsic','invisible','isolated','legal','legitimate','linear',
    'logical','marginal','meaningful','moderate','mutual','neutral',
    'normative','objective','operational','optimal','original','parallel',
    'peripheral','permanent','persistent','precise','predictable',
    'preliminary','prevalent','primary','progressive','proportional',
    'provisional','rational','regional','regulatory','repetitive',
    'representative','rigid','robust','scattered','sensitive','sequential',
    'simultaneous','specific','stable','statistical','straightforward',
    'structural','subjective','substantial','superficial','temporary',
    'terminal','transparent','underlying','unprecedented','urgent',
    'valid','viable','vulnerable','widespread',
  ],

  // ── Additional Oxford 5000 verbs ─────────────────────────────
  verbs: [
    'accompany','accuse','achieve','adapt','admire','affect','afford','agree',
    'alert','allocate','allow','alter','analyse','anticipate','apologise',
    'apply','approach','argue','arise','assemble','assess','assign','assist',
    'assume','attempt','attend','attract','avoid','blame','borrow','bother',
    'breathe','carry','cause','celebrate','challenge','charge','cite','clarify',
    'classify','collect','combine','commit','communicate','compare','compete',
    'complain','compose','concentrate','concern','conduct','confirm','consent',
    'consider','construct','contain','convince','convert','cooperate','correct',
    'damage','deal','declare','dedicate','delay','demonstrate','depend','derive',
    'describe','deserve','designate','destroy','determine','develop','differ',
    'diminish','disappear','discover','discuss','distribute','divide','emerge',
    'employ','encourage','enhance','ensure','estimate','evaluate','exceed',
    'exchange','exclude','expand','expect','expose','extend','fail','favour',
    'function','generate','grant','handle','happen','harm','highlight','ignore',
    'imagine','implement','imply','impose','inform','inspire','interpret','invest',
    'involve','justify','launch','limit','link','locate','maintain','measure',
    'mention','modify','motivate','neglect','notify','obtain','operate','oppose',
    'organise','overcome','perform','permit','predict','prefer','prevent',
    'produce','prohibit','promote','propose','protect','prove','provide',
    'publish','pursue','raise','react','realise','recognise','recommend',
    'recover','refer','reflect','reject','relate','rely','remove','replace',
    'represent','resist','respond','restrict','retain','reveal','review',
    'satisfy','select','separate','suggest','supply','support','survive',
    'sustain','target','tolerate','transfer','transform','translate','treat',
    'understand','update','validate','verify','violate','withdraw','yield',
  ],

  // ── Additional Oxford 5000 nouns ──────────────────────────────
  nouns: [
    'access','achievement','action','adjustment','advantage','agenda','analysis',
    'approach','argument','aspect','assessment','assumption','atmosphere',
    'attempt','attitude','authority','awareness','background','behaviour',
    'belief','benefit','capacity','category','challenge','channel','charge',
    'choice','circumstance','claim','climate','colleague','commitment',
    'competition','complaint','complexity','component','concept','conclusion',
    'conflict','connection','consequence','consumption','contribution','control',
    'controversy','criticism','culture','currency','decline','definition',
    'demand','description','development','distinction','distribution','domain',
    'effectiveness','efficiency','element','emotion','emphasis','encouragement',
    'error','evaluation','evidence','exception','expense','explanation',
    'exploration','failure','feature','framework','freedom','function','gap',
    'guidance','guilt','growth','identity','impact','implication','income',
    'increase','independence','indication','inequality','influence','innovation',
    'input','insight','intelligence','interaction','interest','interpretation',
    'investment','leadership','legislation','logic','loss','means','model',
    'motivation','nature','network','notion','obstacle','offence','operation',
    'opportunity','origin','outcome','output','partnership','pattern','payment',
    'penalty','perception','performance','phenomenon','potential','poverty',
    'pressure','principle','priority','procedure','proportion','provision',
    'purpose','quality','range','reality','reduction','reference','relationship',
    'relevance','reliance','requirement','resistance','responsibility','revenue',
    'scale','scope','sector','selection','sequence','significance','solution',
    'source','stability','stereotype','stress','structure','submission',
    'substance','success','summary','superiority','supply','tension','theory',
    'threat','tolerance','transition','trend','uncertainty','unity','validity',
    'variation','vulnerability','welfare','willingness',
  ],

  // ── Additional Oxford 5000 adjectives ────────────────────────
  adjectives: [
    'abstract','acceptable','accessible','accurate','adequate','alternative',
    'apparent','appropriate','arbitrary','aware','capable','certain','chronic',
    'coherent','comparable','compatible','competitive','complex','comprehensive',
    'concrete','conditional','consistent','controversial','conventional',
    'cooperative','corresponding','creative','crucial','dedicated','definite',
    'deliberate','dependent','desirable','determined','diverse','dominant',
    'eligible','enormous','equal','equivalent','essential','evident','excessive',
    'exclusive','explicit','extensive','extreme','favourable','flexible',
    'formal','fundamental','genuine','global','gradual','gradual','harmful',
    'horizontal','hostile','ideal','identical','immediate','implicit','inevitable',
    'informal','inherent','initial','innovative','integral','intense','logical',
    'minimal','minor','modest','mutual','negative','neutral','obvious','optional',
    'original','passive','particular','permanent','positive','potential',
    'practical','precise','preliminary','primary','prior','prominent','rational',
    'realistic','reasonable','relevant','reliable','rigid','robust','secondary',
    'sensitive','severe','significant','stable','straightforward','subsequent',
    'substantial','sufficient','suitable','systematic','temporary','theoretical',
    'transparent','ultimate','universal','valid','variable','vertical','virtual',
    'visible','vulnerable','widespread',
  ],

  // ── Additional Oxford 5000 adverbs / connectors ───────────────
  adverbs: [
    'accordingly','actually','additionally','alternatively','approximately',
    'broadly','carefully','clearly','collectively','consequently','considerably',
    'constantly','continuously','correctly','deliberately','directly','equally',
    'essentially','eventually','exactly','explicitly','extremely','fairly',
    'formally','frequently','fundamentally','generally','gradually','heavily',
    'highly','increasingly','independently','indirectly','inevitably','largely',
    'mainly','mostly','naturally','necessarily','notably','obviously',
    'occasionally','partially','particularly','potentially','precisely',
    'primarily','properly','rapidly','rarely','relatively','respectively',
    'roughly','seriously','significantly','simply','slightly','specifically',
    'strongly','subsequently','substantially','suddenly','surprisingly',
    'systematically','therefore','thoroughly','typically','ultimately','uniquely',
    'virtually','widely',
  ],

  // ── Oxford 5000 phrasal verbs ─────────────────────────────────
  phrasals2: [
    'back up','break into','bring about','bring back','build up',
    'call off','call on','carry out','check in','check out',
    'come across','come up with','cut back','cut down','cut off',
    'deal with','die out','draw up','drop off','fall apart',
    'fall behind','figure out','get along','get away','get back',
    'get over','give back','give out','go ahead','go along with',
    'go away','go over','hand in','hand out','keep away',
    'keep up with','lay off','leave out','let down','live up to',
    'look back','look out','look up to','make out','make up for',
    'pass away','pick out','pull off','put aside','put forward',
    'put out','put up','run away','run into','set off',
    'settle down','stand out','stand up for','step up','take apart',
    'take back','take on','talk over','think through','throw away',
    'try out','turn down','turn into','turn out','use up',
    'work on','work through','write down','write off',
  ],

  // ── Oxford 5000 compound nouns ────────────────────────────────
  compounds: [
    'age group','air pollution','bank account','birth rate','blood pressure',
    'body language','carbon footprint','case study','civil rights',
    'climate change','contact details','cost of living','credit card',
    'customer service','data protection','decision making','economic growth',
    'energy consumption','equal opportunity','exchange rate','food chain',
    'free trade','global warming','health care','interest rate','job market',
    'labour market','law enforcement','learning curve','life expectancy',
    'living standard','long term','market share','mass media','mental health',
    'middle class','natural disaster','news agency','open source',
    'peer pressure','per capita','point of view','public sector',
    'quality of life','raw material','role model','rule of law',
    'sea level','short term','side effect','skill set','social media',
    'social network','standard of living','state of mind','stock market',
    'supply chain','tax rate','think tank','trade off','turning point',
    'unemployment rate','urban area','value added','work experience',
    'working class','world view',
  ],

  // ── Oxford 5000 AWL academic verbs ───────────────────────────
  awl_verbs: [
    'abstract','accelerate','accumulate','administer','affirm',
    'approximate','assemble','attain','attribute','coincide',
    'commence','compensate','complement','comply','conceive',
    'contradict','correlate','deduce','depict','derive',
    'detect','deviate','discriminate','distort','diversify',
    'elaborate','equate','erode','estimate','exemplify',
    'exploit','formulate','inhabit','interact','invoke',
    'legislate','likewise','offset','orient','participate',
    'perceive','persist','portray','precede','presume',
    'reconstruct','refine','register','relocate','resolve',
    'simulate','stimulate','substitute','supplement','terminate',
    'transmit','underlie','undertake','unify','vary',
  ],

  // ── Oxford 5000 AWL academic nouns ───────────────────────────
  awl_nouns: [
    'amendment','annotation','approximation','coefficient','commodity',
    'connotation','convention','criteria','dimension','domain',
    'entity','equation','error','ethic','formula',
    'goal','hierarchy','incidence','indicator','inference',
    'margin','medium','minimum','module','norm',
    'notion','output','parameter','period','principal',
    'publication','ratio','shift','symbol','syntax',
    'technique','trigger',
  ],

  // ── Oxford 5000 B1/B2 verbs (frequent & important) ───────────
  verbs3: [
    'abolish','absorb','abuse','achieve','acknowledge','activate',
    'adapt','address','adhere','adjust','advocate','allocate',
    'alter','amend','appeal','apply','appreciate','approach',
    'approve','argue','assert','assist','associate','assume',
    'attach','attempt','attend','attribute','boost','calculate',
    'categorise','cease','challenge','characterise','clarify',
    'collaborate','combine','commit','compensate','compile',
    'compute','conceal','confirm','confront','consent','construct',
    'contemplate','convert','cooperate','correct','create',
    'criticise','cultivate','customise','damage','debate',
    'declare','dedicate','defend','delegate','deliver',
    'demonstrate','deploy','derive','designate','detect',
    'determine','distribute','document','dominate','empower',
    'enforce','enhance','establish','evaluate','exclude',
    'expand','exploit','expose','extend','facilitate',
    'forecast','formulate','found','frame','fulfil',
    'generate','highlight','host','identify','ignore',
    'implement','improve','indicate','induce','influence',
    'inspect','inspire','interact','interpret','introduce',
    'justify','launch','locate','maintain','measure',
    'mediate','modify','monitor','negotiate','obtain',
    'oppose','optimise','originate','overcome','perceive',
    'perform','permit','persist','portray','predict',
    'preserve','prohibit','propose','protect','provide',
    'publish','pursue','reassess','rebuild','recover',
    'recycle','reduce','refer','register','regulate',
    'reinforce','reject','rely','remove','represent',
    'research','resolve','restrict','retain','reveal',
    'reward','satisfy','secure','separate','stimulate',
    'submit','succeed','supplement','support','suspend',
    'sustain','target','transform','transmit','undermine',
    'validate','vary','verify',
  ],

  // ── Oxford 5000 B2/C1 nouns (frequent & important) ───────────
  nouns3: [
    'abundance','accomplishment','accusation','acquisition',
    'adaptation','administration','admission','adolescent',
    'adversity','affiliation','aftermath','aggression','allegiance',
    'allocation','ambiguity','ancestry','anticipation',
    'apparatus','appreciation','appropriation','arbitration',
    'assertion','assumption','attribution','bureaucrat',
    'calculation','categorisation','characteristic','clarity',
    'collaboration','complication','comprehension','concession',
    'confirmation','confrontation','consent','consideration',
    'consolidation','contradiction','contribution','controversy',
    'conviction','coordination','corruption','creativity',
    'credibility','cultivation','customisation','declaration',
    'deficiency','deficit','delegation','deliberation',
    'demonstration','deployment','detection','determination',
    'disparity','disruption','distortion','dominance',
    'elimination','empowerment','enhancement','enthusiasm',
    'erosion','establishment','evaluation','exaggeration',
    'exclusion','exploitation','exploration','facilitation',
    'fluctuation','formulation','foundation','fulfilment',
    'generalisation','governance','growth','hostility',
    'identification','implication','incorporation','indication',
    'inequality','initiative','insight','inspiration',
    'integration','interpretation','justification','legislation',
    'legitimacy','limitation','marginalisation','mediation',
    'methodology','migration','modification','momentum',
    'motivation','negotiation','obligation','optimisation',
    'orientation','participation','perception','persistence',
    'perspective','prevalence','prioritisation','productivity',
    'prohibition','promotion','proportion','proposition',
    'qualification','reasoning','reconciliation','reinforcement',
    'representation','restriction','retaliation','retention',
    'scrutiny','simulation','specification','stabilisation',
    'stereotype','stimulation','strategy','subordination',
    'substitution','transformation','transparency','uncertainty',
    'utilisation','validation','vulnerability',
  ],

  // ── Oxford 5000 collocations (verb + noun) ───────────────────
  collocations: [
    'achieve a goal','address a problem','adopt a policy',
    'apply for a job','attend a meeting','break a record',
    'build a relationship','carry out research','cause damage',
    'conduct a survey','consider an option','draw a conclusion',
    'express an opinion','face a challenge','find a solution',
    'gain experience','give a presentation','have an impact',
    'hold a position','identify a need','make a decision',
    'meet a deadline','overcome a barrier','pay attention',
    'perform a task','play a role','pose a threat',
    'provide support','raise awareness','reach a consensus',
    'resolve a conflict','set a goal','share information',
    'take responsibility','tackle an issue','undergo training',
  ],

  // ── Oxford 5000 idiomatic expressions ───────────────────────
  idioms2: [
    'a blessing in disguise','a piece of cake','at the drop of a hat',
    'back to square one','beat around the bush','bite the bullet',
    'break new ground','burn bridges','by and large',
    'call it a day','change of heart','cross that bridge',
    'cut corners','face the music','get cold feet',
    'get the ball rolling','give the benefit of the doubt',
    'go the extra mile','hit the nail on the head',
    'in a nutshell','in the long run','keep a low profile',
    'keep in mind','level playing field','miss the point',
    'not my cup of tea','on thin ice','once in a blue moon',
    'open a can of worms','out of the blue','pass the buck',
    'pull strings','read between the lines','reinvent the wheel',
    'see eye to eye','show of hands','sit on the fence',
    'spill the beans','steal the show','take it with a grain of salt',
    'the ball is in your court','the bigger picture','think outside the box',
    'throw in the towel','under the weather','up in the air',
    'versus','weigh up the pros and cons',
  ],

  // ── Oxford 5000 B1/B2 topic vocabulary: Environment ──────────
  environment: [
    'atmosphere','biodiversity','conservation','deforestation','drought',
    'ecosystem','emission','endangered','erosion','fossil fuel',
    'habitat','hurricane','landfill','ozone layer','pesticide',
    'precipitation','recyclable','renewable','sewage','solar panel',
    'species','toxic','typhoon','wildfire','wind turbine',
  ],

  // ── Oxford 5000 B1/B2 topic vocabulary: Technology ───────────
  technology: [
    'algorithm','application','artificial intelligence','automation',
    'bandwidth','browser','cloud computing','cybersecurity','database',
    'device','encryption','firewall','hardware','interface','malware',
    'network','password','platform','processor','programming',
    'prototype','router','server','software','startup',
    'streaming','update','upload','username','virtual reality',
    'wireless','workflow',
  ],

  // ── Oxford 5000 B2/C1 topic vocabulary: Economy & Business ───
  business2: [
    'bankruptcy','benchmark','brand','breakeven','bribery',
    'budget','buyout','cashflow','commodity','competitive advantage',
    'compliance','consumer','contractor','copyright','corporate',
    'cost-effective','debt','demographic','depreciation','downturn',
    'due diligence','earnings','equity','expenditure','fiscal',
    'forecast','franchise','gross','incentive','incorporation',
    'inflation','insolvency','intellectual property','inventory',
    'invoice','liability','liquidation','logistics','merger',
    'monopoly','niche','overhead','outsource','patent',
    'profit margin','quarterly','recession','redundancy','revenue',
    'shareholder','sole trader','startup','subsidy','takeover',
    'tariff','taxation','turnover','valuation','venture capital',
    'wholesale','workforce',
  ],

  // ── Oxford 5000 B1/B2 topic vocabulary: Society & Culture ─────
  society: [
    'asylum seeker','bias','census','citizenship','civic',
    'civil society','class system','cohesion','colonialism',
    'community centre','consensus','conservative','constitution',
    'cultural heritage','customs','demography','deportation',
    'detention','diaspora','ethnocentric','extremism','feminism',
    'gender equality','gentrification','grassroots','ideology',
    'immigration','inclusive','indigenous','integration','liberal',
    'mainstream','marginalised','multicultural','nationalism',
    'norm','oppression','patriarchy','pluralism','populism',
    'prejudice','privilege','progressive','racism','radical',
    'referendum','refugee','segregation','social justice',
    'stereotyping','suffrage','tolerance','welfare state',
    'xenophobia',
  ],

  // ── Oxford 5000 B1/B2 topic vocabulary: Health & Science ──────
  health2: [
    'antibiotic','antidepressant','artery','biopsy','cardiac',
    'cardiovascular','clinical','cognitive','complication',
    'congenital','consultation','contraception','deficiency',
    'dementia','epidemic','fatigue','genetic','hygiene',
    'immunity','infectious','insomnia','malnutrition','obesity',
    'organ','outbreak','pandemic','parasite','pathogen',
    'pharmacy','placebo','prevention','prognosis','psychiatric',
    'psychologist','pulmonary','relapse','respiratory','sedative',
    'side effect','specimen','sterile','stroke','syndrome',
    'transplant','trauma','tumour','ulcer','vitamin',
  ],

  // ── Oxford 5000 B2/C1 academic vocabulary ────────────────────
  academic2: [
    'abstract noun','abstract thinking','analytical','argumentation',
    'assertion','citation','clause','cohesion','collocation',
    'connotation','deduction','discourse','essay structure',
    'evidence-based','exemplification','exposition','fallacy',
    'hedging','induction','inference','literary device',
    'logical fallacy','nominalization','objective','paragraph',
    'paraphrase','peer review','plagiarism','premise','proposition',
    'qualitative','quantitative','quotation','reasoning','refutation',
    'register','rhetorical','rubric','scholar','scope',
    'structure','stylistic','summary','syntax','thesis statement',
    'topic sentence','transition','validity',
  ],
  // ── Oxford 5000 B1/B2 verbs (batch 4) ───────────────────────
  verbs4: [
    'accelerate','accompany','accuse','acquire','act','adapt','add','admire',
    'adopt','advertise','affect','afford','aim','alert','allocate','allow',
    'alter','amend','announce','apologise','appoint','approach','approve',
    'argue','arise','assemble','assess','assign','assist','attach','attract',
    'avoid','blame','borrow','bother','breathe','celebrate','charge','cite',
    'classify','collect','combine','commit','compare','compete','complain',
    'concentrate','concern','consent','contain','convince','convert','cooperate',
    'correct','damage','deal','declare','dedicate','delay','deny','depend',
    'describe','deserve','destroy','differ','diminish','disappear','disclose',
    'discuss','divide','earn','employ','encourage','ensure','estimate',
    'evaluate','examine','exchange','exist','expect','express','fail','favour',
    'follow','fund','function','grant','handle','harm','hire','host','ignore',
    'imagine','impose','inform','invest','involve','launch','link','manage',
    'measure','mention','motivate','notify','obtain','oppose','perform',
    'permit','prefer','prevent','produce','prohibit','protect','prove',
    'publish','raise','realise','recognise','recommend','recover','refer',
    'reflect','reject','relate','replace','resist','respond','restrict',
    'satisfy','select','separate','simplify','suggest','supply','survive',
    'transfer','translate','treat','withdraw',
  ],

  // ── Oxford 5000 B1/B2 adjectives (batch 3) ──────────────────
  adjectives3: [
    'abandoned','accidental','accurate','active','actual','additional',
    'adequate','advanced','affordable','aggressive','ambitious','ancient',
    'annual','anxious','appropriate','approximate','available','average',
    'awful','balanced','basic','beneficial','blind','bold','brief',
    'capable','careful','certain','classic','clear','comfortable','common',
    'competitive','complete','complex','confident','conscious','creative',
    'critical','crucial','cultural','curious','current','dangerous','decent',
    'deep','dense','detailed','direct','distant','dominant','double',
    'dramatic','dynamic','eager','easy','effective','elderly','enormous',
    'equal','ethnic','eventual','excessive','experienced','extra','extreme',
    'false','familiar','famous','fierce','final','fine','fixed','flexible',
    'foreign','formal','fresh','frequent','full','further','genuine',
    'glad','global','good','gradual','greater','guilty','happy','harsh',
    'helpful','historical','honest','horrible','huge','human','humble',
    'ideal','illegal','immediate','important','independent','indirect',
    'individual','informal','inner','intense','interested','internal',
    'isolated','joint','just','kind','key','large','latest','likely',
    'limited','lonely','low','mainstream','major','massive','mature',
    'meaningful','mental','mere','modern','moral','multiple','narrow',
    'national','natural','negative','nearby','necessary','normal',
    'obvious','official','ongoing','open','ordinary','organised',
    'outstanding','overall','painful','particular','passive','permanent',
    'personal','physical','political','popular','positive','powerful',
    'private','proper','public','pure','quick','radical','rapid',
    'rare','real','regular','remote','responsible','rich','rough',
    'rural','safe','separate','serious','severe','sharp','similar',
    'single','social','solid','special','steady','strict','strong',
    'sudden','suitable','superior','surprising','sustainable','typical',
    'ultimate','unique','unnecessary','unusual','useful','various',
    'violent','warm','weak','willing','wrong','young',
  ],

  // ── Oxford 5000 Law & Politics vocabulary ────────────────────
  law_politics: [
    'acquittal','amendment','appeal','arrest','attorney','bail',
    'bill','campaign','candidate','charter','civil law','coalition',
    'contempt','conviction','court','crime','criminal','cross-examine',
    'decree','defamation','defendant','deliberate','democracy','detention',
    'dictatorship','diplomacy','diplomat','doctrine','election','electoral',
    'embassy','enforce','evidence','federal','fine','fraud','government',
    'grievance','guilty','hearing','human rights','immunity','impeach',
    'indict','injunction','innocent','inquiry','judge','judicial','jury',
    'justice','law','lawsuit','lawyer','legislation','legislature','liable',
    'mandate','minister','monarchy','motion','municipality','oath',
    'offence','parliament','parole','penalty','petition','plaintiff',
    'plea','policy','politician','politics','poll','precedent','prison',
    'probation','prosecution','protest','regulation','republic','ruling',
    'sanction','senate','sentence','settlement','sovereignty','statute',
    'suspect','testimony','treaty','tribunal','verdict','vote','witness',
  ],

  // ── Oxford 5000 Media & Communication vocabulary ─────────────
  media_comm: [
    'advertise','advertisement','agenda','anchor','article','audience',
    'bias','blog','broadcast','cable','caption','censorship','channel',
    'circulation','clickbait','column','commentary','correspondent',
    'coverage','critique','debate','documentary','editorial','embed',
    'expose','feature','footage','format','freelance','hashtag','headline',
    'influencer','interview','investigative','journalist','launch','leak',
    'live stream','magazine','media literacy','mislead','narrative',
    'newsroom','objectivity','opinion','outlet','paparazzi','podcast',
    'press','print','propaganda','publish','quote','rating','readership',
    'reporter','rhetoric','satire','scoop','sensational','source',
    'sponsor','subscription','tabloid','target audience','viral',
    'vlog','website','wire service',
  ],

  // ── Oxford 5000 Education & Learning vocabulary ──────────────
  education_vocab: [
    'academic','accreditation','assessment','attend','attendance',
    'bachelor','bursary','certificate','classroom','coach','competency',
    'comprehension','compulsory','curriculum','degree','diploma',
    'discipline','distance learning','dropout','e-learning','enrol',
    'enrolment','entrance exam','essay','examination','exercise','faculty',
    'feedback','field trip','final exam','fluency','formal education',
    'gifted','grade','graduate','graduation','grant','homework','institution',
    'instruction','intake','internship','lecture','lecturer','lesson',
    'library','literacy','marking','master','memorise','mentor','module',
    'numeracy','objective','pass','peer','performance','postgraduate',
    'practise','prerequisite','primary school','principal','professor',
    'pupil','qualification','quiz','reception','research','revision',
    'scholarship','secondary school','seminar','skill','student','subject',
    'syllabus','task','teacher','term','test','textbook','thesis',
    'timetable','transcript','tuition','tutor','tutorial','undergraduate',
    'university','vocational','workshop',
  ],

  // ── Oxford 5000 Food & Nutrition vocabulary ──────────────────
  food_vocab: [
    'additive','allergy','antioxidant','appetite','aroma','bake','barbecue',
    'beverage','bland','boil','calorie','carbohydrate','cholesterol','chop',
    'condiment','cuisine','dairy','deficiency','deli','dessert','diet',
    'digest','dine','dish','ferment','flavour','fry','garnish','gluten',
    'gourmet','grain','grease','grill','herb','homemade','hunger','ingredient',
    'intolerance','lactose','lean','marinate','microwave','mineral','mince',
    'nourish','nutrient','nutrition','obese','organic','oven','overweight',
    'plant-based','portion','poultry','preserve','processed','protein',
    'recipe','roast','savoury','seasonal','simmer','snack','sodium','spice',
    'steam','stew','supplement','sustainable food','taste','texture',
    'vegan','vegetarian','vitamin',
  ],

  // ── Oxford 5000 Travel & Transport vocabulary ─────────────────
  travel_vocab: [
    'accommodation','airline','airport','backpack','baggage','boarding pass',
    'border','budget','cabin','campsite','cancel','cargo','charter',
    'check-in','commute','connection','customs','delay','departure',
    'destination','embassy','excursion','expedition','fare','flight',
    'freight','fuel','guide','highway','hostel','infrastructure','itinerary',
    'jet lag','journey','landmark','layover','licence','luggage','map',
    'motorway','navigation','passport','platform','port','railway',
    'reservation','resort','route','runway','schedule','station',
    'stopover','suitcase','terminal','ticket','timetable','toll',
    'tourist','transfer','transit','transport','travel agency','trek',
    'trip','tunnel','vehicle','visa','voyage',
  ],

  // ── Oxford 5000 Environment & Sustainability (extended) ───────
  environment2: [
    'acid rain','adaptation','biodegradable','biomass','carbon neutral',
    'carbon offset','chlorofluorocarbon','climate model','composting',
    'conservation area','contaminate','coral reef','depletion',
    'desertification','ecological','ecotourism','endangered species',
    'energy efficiency','environmental impact','extinction','flood plain',
    'fossil record','geothermal','glacier retreat','greenhouse effect',
    'groundwater','habitat destruction','hydrosphere','ice cap',
    'land degradation','methane','microplastic','net zero',
    'nitrogen cycle','ocean acidification','organic farming','ozone depletion',
    'permafrost','photosynthesis','pollution','rainforest',
    'renewable energy','rewilding','soil erosion','solar energy',
    'sustainability','tidal power','toxic waste','urban heat island',
    'waste management','water cycle','water scarcity','wetland',
    'wind energy','zero emission',
  ],

  // ── Oxford 5000 common adverbs (batch 2) ─────────────────────
  adverbs2: [
    'above all','absolutely','across','allegedly','almost','already',
    'also','altogether','anywhere','apart','apparently','as a rule',
    'at best','at least','at once','barely','besides','beyond','carefully',
    'certainly','closely','commonly','currently','deeply','directly',
    'entirely','especially','everywhere','ever','fairly','far','finally',
    'firmly','firstly','for instance','fortunately','frankly',
    'generally speaking','gradually','hard','hardly','hence','here',
    'honestly','however','ideally','in brief','in contrast','in detail',
    'in short','in theory','indeed','initially','instead','jointly',
    'just','lately','likely','literally','locally','long','meanwhile',
    'merely','minimally','moreover','mostly','namely','neither',
    'next','nonetheless','not only','notably','now','nowhere',
    'obviously','officially','once','only','otherwise','overall',
    'perfectly','plainly','previously','promptly','quite','rather',
    'readily','recently','reportedly','safely','scarcely','seldom',
    'so far','somehow','somewhat','soon','still','strictly','subsequently',
    'surely','temporarily','there','thus','together','totally',
    'typically','unless','until','usually','very','well','yet',
  ],
  // ── Oxford 5000 Sport & Leisure vocabulary ───────────────────
  sport_leisure: [
    'amateur','arena','athlete','athletic','badminton','championship',
    'coach','competitor','court','cricket','cycling','defeat','defender',
    'draw','endurance','fan','final','fitness','goalkeeper','gym',
    'gymnastics','hobby','hockey','league','leisure','marathon','medal',
    'membership','opponent','pitch','playoff','professional','qualify',
    'referee','relay','rival','round','score','spectator','sponsor',
    'sportsmanship','squad','stadium','stamina','strategy','stretching',
    'substitute','tactics','team spirit','tournament','trainer',
    'training','trophy','umpire','venue','warm-up','workout',
  ],

  // ── Oxford 5000 Arts & Entertainment vocabulary ──────────────
  arts_entertain: [
    'abstract art','acoustic','actor','animation','art gallery',
    'audition','ballet','biography','blockbuster','box office',
    'cast','ceramics','choreography','cinema','classical music',
    'comedy','composer','costume','critic','curator','director',
    'drama','ensemble','exhibition','fiction','genre','illustration',
    'improvisation','installation','lyrics','masterpiece','melody',
    'memoir','musical','narrative','novelist','orchestra','painting',
    'performance','plot','playwright','plot twist','portrait',
    'premiere','production','protagonist','rehearsal','review',
    'sculpture','screenplay','script','sequel','set design','soundtrack',
    'spectacle','stage','studio','symphony','talent show','theatre',
    'venue','villain',
  ],

  // ── Oxford 5000 Crime & Safety vocabulary ────────────────────
  crime_safety: [
    'alarm','arson','assault','burglar','burglary','CCTV','convict',
    'detective','disorder','evacuate','evidence','felony','firearm',
    'forensic','fraudster','getaway','hijack','hostage','interrogation',
    'investigate','kidnap','larceny','manslaughter','misdemeanour',
    'mugging','offender','perpetrator','pickpocket','poaching','raid',
    'ransom','robbery','sabotage','security guard','shoplifting',
    'smuggling','stalking','suspicious','swindler','theft','thief',
    'trespassing','vandalism','victim','vigilante','watchdog',
  ],

  // ── Oxford 5000 Family & Relationships vocabulary ────────────
  family_relations: [
    'affection','ancestor','bond','bride','bridegroom','companionship',
    'compatible','custody','dependant','divorce','engagement','estranged',
    'extended family','fiancé','foster','genealogy','generation gap',
    'godparent','guardian','heir','heritage','household','in-laws',
    'inheritance','intimacy','kinship','matrimony','nephew','niece',
    'nuclear family','offspring','only child','orphan','rapport',
    'reconciliation','reunion','separation','sibling','single parent',
    'spouse','stepfather','stepmother','toddler','twin','upbringing',
    'widow','widower',
  ],

  // ── Oxford 5000 Work & Employment vocabulary ─────────────────
  work_employment: [
    'applicant','apprenticeship','bonus','career','colleague',
    'commute','contract','CV','dismissal','employee','employer',
    'employment','freelancer','gig economy','headhunter','hierarchy',
    'incentive','induction','interview','job satisfaction','job security',
    'jobseeker','layoff','minimum wage','negotiation','networking',
    'occupation','overtime','paid leave','part-time','pension',
    'performance review','perk','probation period','productivity',
    'promotion','qualification','recruiter','recruitment','redundancy',
    'remote work','resignation','résumé','retirement','salary',
    'severance','shift work','sick leave','staff','supervisor',
    'trade union','training','vacancy','wage','work-life balance',
    'workforce','workload','workplace',
  ],

  // ── Oxford 5000 Housing & Daily Life vocabulary ──────────────
  housing_life: [
    'apartment block','appliance','balcony','basement','bill','blinds',
    'ceiling','chores','cottage','courtyard','décor','deposit',
    'detached house','dishwasher','district','drainage','dwelling',
    'eviction','fixture','flatmate','furnished','heating','homeowner',
    'household chores','landlord','lease','lodger','maintenance',
    'mortgage','neighbourhood','outskirts','plumbing','property',
    'real estate','renovation','rent','residence','residential',
    'roommate','semi-detached','skyscraper','suburb','tenant',
    'terraced house','utilities','ventilation','veranda',
  ],

  // ── Oxford 5000 Science & Research vocabulary ────────────────
  science_research: [
    'apparatus','astronomy','atom','bacteria','biology','botany',
    'cell','chemical','chemistry','chromosome','data','DNA',
    'ecosystem','electron','element','embryo','evolution','experiment',
    'fossil','gene','genetics','geology','gravity','hypothesis',
    'laboratory','laser','mammal','matter','microscope','molecule',
    'neuron','nucleus','observation','organism','particle','physics',
    'pressure','probe','protein','radiation','reaction','reproduction',
    'reptile','researcher','sample','specimen','telescope','theory',
    'tissue','vaccine','variable','virus',
  ],

  // ── Oxford 5000 phrasal verbs (batch 3) ──────────────────────
  phrasals3: [
    'account for','add up','ask around','back away','blow up',
    'break down','break out','bring up','brush up on','burst into',
    'butt in','calm down','carry on','catch up on','clear up',
    'come about','come along','come down with','count on','cross out',
    'cut in','dawn on','dress up','drop by','drop in',
    'ease off','end up','fall back on','fall for','fall through',
    'fill in','fit in','get ahead','get around','get by',
    'get through','give in','give up','go for','go off',
    'go through','grow up','hand over','hang on','hold back',
    'hold on','keep on','knock out','lay out','let on',
    'live on','look after','look down on','look forward to','look into',
    'look through','make up','mess up','mix up','move on',
    'narrow down','own up','pass on','pick up','point out',
    'pull through','push through','put off','put through','rule out',
    'run out of','set up','show off','show up','sort out',
    'speak up','split up','stick to','take after','take off',
    'take over','take up','tear apart','think over','tidy up',
    'tip off','touch on','trade in','wear off','wear out',
    'wind up','wipe out','wrap up',
  ],

  // ── Oxford 5000 noun + preposition / adjective + preposition collocations ──
  preposition_colloc: [
    'access to','addicted to','afraid of','agree with','angry about',
    'anxious about','apologise for','approve of','ashamed of',
    'aware of','based on','blame for','capable of','complain about',
    'composed of','concerned about','confident in','congratulate on',
    'conscious of','consist of','dependent on','devoted to',
    'different from','disappointed with','due to','eligible for',
    'engaged in','envious of','equal to','equivalent to','exposed to',
    'familiar with','famous for','fond of','grateful for','guilty of',
    'identical to','ignorant of','immune to','in charge of','in favour of',
    'in need of','independent of','inferior to','interested in',
    'involved in','jealous of','keen on','known for','linked to',
    'married to','nervous about','opposed to','popular with',
    'proud of','reliant on','responsible for','satisfied with',
    'similar to','suspicious of','sympathetic to','tired of',
    'typical of','worried about',
  ],
  // ── Oxford 5000 Weather & Nature vocabulary ──────────────────
  weather_nature: [
    'avalanche','blizzard','breeze','canyon','cave','cliff','climate',
    'cloud','coastline','current','desert','dew','downpour','drizzle',
    'dune','earthquake','flood','fog','forecast','frost','gale',
    'geyser','glacier','gust','hail','heatwave','horizon','humidity',
    'lagoon','landscape','lightning','meadow','mist','moisture',
    'monsoon','mudslide','oasis','peak','plain','plateau','pond',
    'rainfall','rainforest','reservoir','ridge','sandstorm','shower',
    'sleet','slope','snowfall','storm','stream','summit','swamp',
    'temperature','terrain','thunder','tide','tornado','tropical',
    'tsunami','valley','volcano','waterfall','wave','wilderness',
  ],

  // ── Oxford 5000 Body & Health (extended) vocabulary ──────────
  body_health2: [
    'allergic','ankle','appetite','blister','bloodstream','bruise',
    'chest','chronic illness','collarbone','concussion','cramp',
    'digestive system','dislocate','elbow','exhaustion','fracture',
    'gland','heartbeat','hormone','immune system','infection',
    'inflammation','injury','intestine','jaw','joint','kidney',
    'ligament','liver','lung','metabolism','muscle','nausea',
    'nerve','nutrient','overdose','painkiller','paralysis',
    'physiotherapy','pulse','rash','recovery','rehabilitation',
    'remedy','rib','scar','shoulder blade','skull','spine',
    'sprain','stamina','swelling','symptom','therapy','throat',
    'tissue','tonsil','vein','wound','wrist',
  ],

  // ── Oxford 5000 Money & Shopping vocabulary ──────────────────
  money_shopping: [
    'allowance','bargain','bill','budget','cashier','cheque',
    'consumer','coupon','currency','customer','debit card','deposit',
    'discount','expense','fund','grocery','installment','inventory',
    'invoice','loan','loyalty card','luxury','mortgage','outlet',
    'overdraft','payment','pension','price tag','purchase',
    'receipt','refund','retail','revenue','sale','savings account',
    'shopping cart','spending','statement','subsidy','supermarket',
    'surcharge','transaction','treasury','vendor','voucher','wallet',
    'warranty','wholesale','withdrawal',
  ],

  // ── Oxford 5000 Communication & Language vocabulary ──────────
  comm_language: [
    'accent','ambiguous','articulate','bilingual','body language',
    'colloquial','conversation','dialect','dialogue','eloquence',
    'expression','fluent','gesture','grammar','idiom','interpreter',
    'intonation','jargon','lexicon','linguistics','literal','mimic',
    'mispronounce','mother tongue','multilingual','mumble','mutter',
    'native speaker','nonverbal','phrase','pronunciation','proverb',
    'pun','rhetoric','sign language','slang','stammer','stutter',
    'subtitle','synonym','terminology','tone','translation',
    'utterance','verbal','vernacular','vocabulary','vowel',
  ],

  // ── Oxford 5000 Time & Sequence vocabulary ───────────────────
  time_sequence: [
    'aftermath','aforementioned','beforehand','chronological','concurrently',
    'consecutive','contemporary','decade','deadline','duration',
    'epoch','era','foreseeable','impending','imminent','interim',
    'interval','meanwhile','milestone','momentary','overdue','pending',
    'periodic','perpetual','prior','prolonged','provisional','recurring',
    'simultaneously','span','subsequent','temporary','timeless',
    'timely','transient',
  ],

  // ── Oxford 5000 Quantity & Measurement vocabulary ────────────
  quantity_measure: [
    'aggregate','approximate','average','calculate','dimension',
    'dozen','estimate','extent','fraction','gauge','gross',
    'increment','magnitude','margin','maximum','measurement',
    'minimum','numerous','percentage','proportion','quantity',
    'quota','ratio','scale','statistic','sum','threshold','total',
    'volume','weight','width',
  ],

  // ── Oxford 5000 common collocations (batch 2) ────────────────
  collocations2: [
    'ask a favour','catch the eye','do the dishes','draw attention',
    'earn a living','fall in love','gain weight','get in touch',
    'give way','go bankrupt','have a word','keep a promise',
    'keep a secret','lend a hand','lose touch','lose weight',
    'make a difference','make an effort','make friends','make progress',
    'make sense','pay a visit','pay the price','run a business',
    'run a risk','save time','set an example','set a record',
    'spend time','take a break','take a chance','take a look',
    'take action','take care','take notes','take part','take place',
    'take risks','tell a lie','tell the truth','waste time',
  ],
};

const gaps = {};
let totalMissing = 0;

Object.entries(OXFORD).forEach(([level, words]) => {
  const missing = [...new Set(words)].filter(w => !have.has(w));
  if (missing.length > 0) {
    gaps[level] = missing;
    totalMissing += missing.length;
  }
});

if (totalMissing === 0) {
  console.log('✅ No gaps found in current Oxford list!');
} else {
  Object.entries(gaps).forEach(([level, words]) => {
    console.log(`\n${level} missing (${words.length}):`);
    words.forEach(w => console.log(`  ${w}`));
  });
}

console.log(`\nTotal words in dictionary: ${W.length}`);
console.log(`Total missing: ${totalMissing}`);
