import { W } from '../data/words.js';
const have = new Set(W.map(w => w[0].toLowerCase()));

// Expanded Oxford 5000 word list by CEFR level
const OXFORD = {
  A1: [
    'apple','baby','bag','bath','bed','bike','bird','boat','book','box','boy',
    'bread','brother','car','cat','chair','child','city','class','cold','come',
    'cook','cup','cut','dance','day','door','draw','dream','drink','drive','drop',
    'dry','eat','eye','face','fall','farm','feel','fire','fish','fly','foot',
    'friend','fun','game','garden','girl','give','glass','hand','head','heart',
    'home','horse','hot','house','idea','jump','keep','kid','know','large',
    'last','later','learn','leg','let','life','light','listen','little','live',
    'long','love','make','man','meal','milk','miss','money','more','mountain',
    'mouth','move','much','music','name','new','night','nose','now','number',
    'often','open','out','outside','page','park','part','pay','place','plant',
    'play','point','put','rain','read','right','road','room','run','school',
    'see','set','short','sister','sit','sky','sleep','slow','small','soft',
    'start','stop','story','study','sun','swim','table','take','talk','town',
    'tree','turn','under','use','village','walk','watch','water','way','well',
    'win','window','woman','word','write','year',
  ],
  A2: [
    'able','accept','across','active','activity','actually','adult','advice',
    'afternoon','age','agree','airport','almost','alone','along','although',
    'amount','angry','animal','another','answer','appear','area','around',
    'arrive','attack','autumn','available','awful','balance','beautiful',
    'become','before','behind','belong','below','benefit','best','better',
    'body','both','bottom','bring','business','call','camp','capture','cause',
    'centre','chance','change','character','charge','check','climb','close',
    'clothes','club','collect','colour','comfort','common','community','compare',
    'condition','confident','connect','continue','cross','decide','deep',
    'deliver','depend','describe','detail','different','direction','dirty',
    'discuss','divide','dress','during','early','earn','easy','either','empty',
    'enjoy','enough','enter','especially','even','evening','event','every',
    'everyone','example','except','exercise','explain','explore','extra','fail',
    'familiar','famous','fast','final','follow','force','forward','free','fresh',
    'front','full','future','glad','goal','good','grow','guess','guide',
    'happen','happy','hard','hear','herself','himself','hold','holiday','hope',
    'hour','hurt','image','include','individual','inside','instead','interest',
    'issue','join','kind','knock','land','late','lead','leave','level','lift',
    'likely','line','list','look','loud','lucky','machine','main','manage',
    'map','mark','maybe','mean','meet','message','middle','mine','minute',
    'modern','mother','must','near','need','next','nice','north','nothing',
    'notice','offer','often','old','once','only','opinion','opposite','order',
    'other','own','pass','past','people','perhaps','person','phone','pick',
    'please','plus','popular','position','possible','practice','problem',
    'process','programme','project','put','quite','reach','ready','real',
    'reason','receive','recent','record','remember','repeat','reply','rest',
    'result','return','rich','safe','same','save','second','seem','send',
    'shape','share','show','sign','similar','since','situation','size','skill',
    'smile','social','some','soon','sorry','south','speak','spend','sport',
    'stay','step','still','street','strong','subject','sure','system','theme',
    'themselves','tired','together','touch','trouble','true','try','view',
    'voice','want','warm','week','while','whole','wide','without','worry',
    'worth','young',
  ],
  B1: [
    'abandon','absence','absolute','access','accurate','acquire','adjust',
    'affect','agency','alike','allow','alongside','alternative','analyse',
    'announce','anxious','appropriate','approve','aspect','assess','assist',
    'associate','attitude','attract','aware','award','basis','border',
    'capable','capture','career','carry','category','challenge','channel',
    'chart','circumstances','cite','claim','clarify','classic','comfortable',
    'comment','commit','communicate','complex','concentrate','conclude',
    'consequence','considerable','consist','context','contrast','contribute',
    'convention','convince','correspond','creative','critical','currently',
    'damage','deadline','declaration','define','demonstrate','deny','determined',
    'difficulty','diplomatic','document','dominant','efficient','eliminate',
    'emotional','emphasis','enable','encourage','engage','evaluate','evidence',
    'evident','exceed','exclude','explicit','expose','extensive','factor',
    'failure','feature','focus','formal','fundamental','generate','global',
    'gradually','grant','guarantee','handle','identify','impact','indicate',
    'influence','informal','initially','integrate','intense','intention',
    'investigate','justify','key','launch','lead','link','major','material',
    'mechanism','motivate','negative','neutral','obtain','obvious','occur',
    'oppose','option','overcome','participate','perspective','potential',
    'predict','prefer','previous','principle','priority','process','profession',
    'prohibit','promote','propose','protection','prove','pursue','raise',
    'react','recognize','reduce','reform','region','regulate','reject','relate',
    'reliable','represent','role','seek','select','separate','significant',
    'solve','specific','statement','status','strategy','structure','submit',
    'succeed','survey','task','threat','unique','update','various','version',
    'vital',
    // extra B1 Oxford 5000
    'acknowledge','adapt','administration','agenda','apparently','application',
    'appreciate','approximately','assume','basis','colleague','considerable',
    'consistent','construction','consultation','controversial','conventional',
    'corporation','debate','decade','decline','despite','destination','distinct',
    'diversity','domestic','economy','effective','election','emerge','employ',
    'enforce','enterprise','environment','establish','estimate','ethics',
    'examine','exception','expectation','expand','facility','framework',
    'highlight','immediately','impact','implement','imply','impose','index',
    'infrastructure','initiative','instance','institution','interaction',
    'interpretation','investment','limit','local','maintain','majority',
    'maximum','minimum','network','objective','obtain','organisation','outcome',
    'output','participant','partnership','perform','period','perspective',
    'phase','policy','population','potential','previous','procedure','produce',
    'publish','quality','ratio','rely','remove','require','resource','respond',
    'scheme','sector','sequence','significant','source','specific','statistics',
    'sufficient','summary','target','technique','technology','tradition',
    'transfer','undergo','valid','whereas',
  ],
  B2: [
    'absorb','accomplish','accumulate','acknowledge','adequate','advocate',
    'allocate','ambition','anticipate','apparent','arbitrary','assert',
    'attribute','authority','autonomy','boost','catalyst','collaborate',
    'competent','compile','compose','compromise','concede','conduct','confront',
    'consensus','constraint','coordinate','cultivate','dedicate','deliberate',
    'designate','devote','diminish','distinction','distribute','diverse',
    'dynamic','elaborate','emerge','emphasise','ensure','exclude','facilitate',
    'implement','imply','incentive','incorporate','initiate','interpret',
    'maximize','minimize','monitor','negotiate','objective','perceive',
    'persist','phase','precede','preliminary','prioritise','proportion',
    'prospect','refine','reinforce','remedy','restrict','retain','revenue',
    'revise','scope','specify','stabilise','subsequent','substantial',
    'supplement','sustain','tolerate','transition','undergo','utilise',
    'validate','verify','whereas',
    // extra B2
    'abstract','adjacent','aggregate','albeit','ambiguous','analogy',
    'aspiration','assertion','coherent','comprehensive','concurrent',
    'confine','contradiction','controversial','criterion','deduce','depict',
    'derive','differentiate','discrepancy','disparity','distinction','embed',
    'empirical','enforce','equivalent','explicit','fluctuate','forthcoming',
    'hierarchy','implicit','inconsistency','indispensable','inhibit','insight',
    'integral','intrinsic','invoke','irrelevant','justify','legitimate',
    'mitigate','moreover','nonetheless','nonetheless','notion','orient',
    'overlap','predominant','presume','prohibit','reinstate','render',
    'resolution','retain','rigid','simulate','straightforward','subordinate',
    'supplement','suppress','sustain','terminate','unanimous','underlying',
    'unify','violate','widespread',
  ],
  C1: [
    'abstain','alleviate','ambivalent','articulate','astute','augment',
    'brevity','circumvent','clandestine','coerce','concur','conjecture',
    'consolidate','contemplate','contend','curtail','daunting','debilitating',
    'defer','delve','deplete','discern','disseminate','eloquent','exacerbate',
    'exemplify','expedite','formidable','foster','gauge','harbour','impede',
    'inaugurate','incline','induce','inhibit','innate','invoke','juxtapose',
    'lucid','meticulous','mitigate','nuance','obscure','perpetuate','plausible',
    'postulate','pragmatic','precipitate','predominant','proliferate','prompt',
    'rational','reconcile','scrutinise','sparse','speculate','substantiate',
    'supersede','suppress','tangible','transcend','undermine','unprecedented',
    'vague','yield',
    // extra C1
    'accentuate','acrimony','adamant','adhere','adjacent','admonish',
    'adversarial','aggravate','allude','ambivalent','analogous','anomaly',
    'antagonise','appease','apprehensive','arduous','articulate','assimilate',
    'atrocity','austere','belittle','benevolent','bolster','candid','catalyst',
    'chronic','circumspect','clamour','coercive','cogent','coherent',
    'complacent','conciliate','condescend','conjure','conscientious','contempt',
    'contentious','contradict','culminate','cynical','defiant','deliberate',
    'delineate','deplete','despondent','detrimental','devious','diffuse',
    'diligent','discredit','disdain','dismantle','dispel','disregard',
    'dissent','elusive','empower','encompass','endorse','enigmatic','entail',
    'erode','escalate','exacerbate','exert','explicit','exploit','fragile',
    'fruitless','futile','groundbreaking','hypothetical','imminent','impartial',
    'impending','indeterminate','indifferent','infer','inherent','integral',
    'intractable','irreversible','isolate','legitimate','lenient','lucrative',
    'manifest','meticulous','mitigate','mobilise','momentous','negate',
    'negligible','notoriety','nuanced','oblivious','obsolete','omit',
    'opportune','optimise','ostracise','outweigh','paramount','partisan',
    'patronise','pernicious','persevere','pertinent','plausible','precarious',
    'prestigious','prevail','profound','proliferate','proportionate','provoke',
    'prudent','radical','reassert','rectify','refute','relentless','reluctant',
    'remedy','rigorous','robust','sceptical','scrutiny','sporadic','stagnate',
    'steadfast','stringent','subjective','subtle','tenacious','transparent',
    'turbulent','unequivocal','unprecedented','versatile','viable','volatile',
    'wary','zealous',
  ],
  C2: [
    'accolade','acquiesce','adamantine','adroit','affable','aggrandise',
    'alacrity','anachronism','ancillary','annihilate','antithesis','apocryphal',
    'approbation','arcane','ardour','assiduous','atone','audacious','auspicious',
    'bellicose','benign','bequeath','bombastic','candour','castigate','caveat',
    'chicanery','circumlocution','clemency','coalesce','cognisant','compunction',
    'confound','convoluted','culpable','cupidity','deference','delinquent',
    'delusion','denunciation','depravity','desolate','desultory','diffidence',
    'dilettante','disaffected','disenfranchise','disillusion','disparage',
    'dissemble','duplicity','ebullient','efficacy','effusive','egregious',
    'elicit','embroil','empiricism','endemic','engender','ephemeral',
    'equivocate','erudite','esoteric','estrange','euphemism','evasive',
    'exonerate','expedient','facetious','fallacious','fastidious','fervent',
    'flippant','furtive','garrulous','grandeur','gratuitous','guileless',
    'hubris','hyperbole','iconoclast','impeccable','inadvertent','incisive',
    'incoherent','incongruous','indignant','indolent','inexorable','insolent',
    'intransigent','irrefutable','laconic','lampoon','lethargic','litigious',
    'magnanimous','malevolent','mendacious','mercurial','munificent','myopic',
    'nefarious','nihilism','obsequious','obstinate','obtuse','odious',
    'omnipotent','onerous','ostentatious','parochial','pedantic','perfidious',
    'placate','polemic','pompous','pragmatism','precipitous','preposterous',
    'presuppose','procrastinate','profligate','prolific','proverbial',
    'provocateur','punitive','quandary','querulous','rapacious','reclusive',
    'recondite','recrimination','redress','repudiate','reticent','rhetoric',
    'sagacious','sanctimonious','sardonic','scrupulous','serendipity',
    'solicitous','sophistry','spurious','stoic','subversive','sycophant',
    'taciturn','temerity','tenuous','torpid','transgress','treacherous',
    'truculent','ubiquitous','unscrupulous','vacillate','vehement','venerate',
    'verbose','vindicate','visceral','volatile','wanton','whimsical','zealotry',
  ],

  // ── Oxford 5000 common collocations & expressions ─────────────
  expressions: [
    'as a result','at least','as well as','in addition','in order to',
    'in terms of','on the other hand','in fact','in general','as long as',
    'at the same time','in particular','in practice','on behalf of',
    'in spite of','regardless of','with regard to','as a whole',
    'in the long run','on a regular basis',
  ],

  // ── Oxford 5000 extra verbs (B1-C1) ──────────────────────────
  verbs2: [
    'acknowledge','acquire','advocate','allocate','alter','anticipate',
    'assemble','boost','clarify','collaborate','compile','confront',
    'contrast','deduce','depict','derive','devise','differentiate',
    'discourage','disguise','disrupt','distinguish','elaborate','embed',
    'emerge','enable','enforce','enhance','ensure','entail','equip',
    'exceed','exchange','exclude','exhibit','expand','exploit','expose',
    'facilitate','fluctuate','foster','gauge','generate','highlight',
    'implement','impose','incorporate','indicate','induce','inhibit',
    'initiate','insert','inspect','insist','instruct','interpret',
    'justify','launch','locate','maintain','modify','monitor','motivate',
    'neglect','negotiate','notify','obtain','operate','organise','overcome',
    'perceive','permit','persist','predict','preserve','prevent','proceed',
    'prohibit','promote','propose','pursue','react','reinforce','relate',
    'rely','remove','replace','represent','require','resist','respond',
    'restrict','retain','reveal','review','revise','satisfy','select',
    'specify','submit','suppress','sustain','target','transform','undergo',
    'undermine','update','utilise','validate','verify','violate','yield',
  ],

  // ── Oxford 5000 extra nouns (B1-C1) ──────────────────────────
  nouns2: [
    'absence','abundance','accommodation','accuracy','acquisition',
    'adaptation','administration','adolescence','adoption','agenda',
    'allegation','alliance','allocation','allowance','ambiguity',
    'analysis','anticipation','approval','assessment','assumption',
    'breakdown','campaign','capability','capacity','casualty',
    'clarification','classification','collaboration','commitment',
    'commodity','compensation','complexity','component','conflict',
    'confrontation','consensus','constraint','consumption','convention',
    'conviction','cooperation','coordination','corporation','corruption',
    'creativity','credibility','criterion','cultivation','debate',
    'deception','deficiency','deficit','delay','delegation','dependence',
    'destination','deterioration','deviation','dialogue','dilemma',
    'dimension','disorder','disruption','distinction','distortion',
    'documentation','dominance','drawback','duration','economy',
    'eligibility','emergence','emphasis','endorsement','engagement',
    'enterprise','entity','environment','exception','exclusion',
    'execution','exemption','expectation','expertise','exposure',
    'extension','flexibility','fluctuation','framework','frequency',
    'fulfilment','governance','generation','globalisation','implication',
    'incentive','inconsistency','independence','infrastructure',
    'initiation','innovation','input','integration','investigation',
    'justification','mechanism','migration','modification','momentum',
    'motivation','obligation','obstacle','participation','perception',
    'perspective','prevalence','procedure','qualification','rationale',
    'regulation','reinforcement','rejection','relevance','reputation',
    'resentment','restriction','retention','scrutiny','sequence',
    'shortage','simulation','specification','stereotype','stimulation',
    'strategy','subordination','substitution','transition','transparency',
    'trigger','variation','verification','vulnerability',
  ],

  // ── Oxford 5000 extra adjectives (B1-C1) ─────────────────────
  adjectives2: [
    'abstract','acute','additional','adverse','aggregate','ambitious',
    'analogous','anonymous','arbitrary','artificial','authoritative',
    'autonomous','beneficial','biased','characteristic','chronic',
    'circular','coherent','collaborative','collective','compact',
    'compatible','concurrent','confidential','consistent','contemporary',
    'controversial','credible','cumulative','decisive','defensive',
    'definitive','deliberate','dependent','derived','digital','discrete',
    'discriminatory','dispersed','distinctive','distributed','efficient',
    'eligible','empirical','enormous','essential','ethical','evident',
    'evolutionary','exclusive','explicit','external','extreme','factual',
    'fragile','functional','genuine','hierarchical','identical','immediate',
    'implicit','incentive','inevitable','integral','intensive','intermediate',
    'intrinsic','invisible','isolated','legal','legitimate','linear',
    'logical','marginal','meaningful','moderate','mutual','neutral',
    'normative','objective','operational','optimal','original','parallel',
    'peripheral','permanent','persistent','precise','predictable',
    'preliminary','prevalent','primary','progressive','proportional',
    'provisional','rational','regional','regulatory','repetitive',
    'representative','rigid','robust','scattered','sensitive','sequential',
    'simultaneous','specific','stable','statistical','straightforward',
    'structural','subjective','substantial','superficial','temporary',
    'terminal','transparent','underlying','unprecedented','urgent',
    'valid','viable','vulnerable','widespread',
  ],

  // ── Additional Oxford 5000 verbs ─────────────────────────────
  verbs: [
    'accompany','accuse','achieve','adapt','admire','affect','afford','agree',
    'alert','allocate','allow','alter','analyse','anticipate','apologise',
    'apply','approach','argue','arise','assemble','assess','assign','assist',
    'assume','attempt','attend','attract','avoid','blame','borrow','bother',
    'breathe','carry','cause','celebrate','challenge','charge','cite','clarify',
    'classify','collect','combine','commit','communicate','compare','compete',
    'complain','compose','concentrate','concern','conduct','confirm','consent',
    'consider','construct','contain','convince','convert','cooperate','correct',
    'damage','deal','declare','dedicate','delay','demonstrate','depend','derive',
    'describe','deserve','designate','destroy','determine','develop','differ',
    'diminish','disappear','discover','discuss','distribute','divide','emerge',
    'employ','encourage','enhance','ensure','estimate','evaluate','exceed',
    'exchange','exclude','expand','expect','expose','extend','fail','favour',
    'function','generate','grant','handle','happen','harm','highlight','ignore',
    'imagine','implement','imply','impose','inform','inspire','interpret','invest',
    'involve','justify','launch','limit','link','locate','maintain','measure',
    'mention','modify','motivate','neglect','notify','obtain','operate','oppose',
    'organise','overcome','perform','permit','predict','prefer','prevent',
    'produce','prohibit','promote','propose','protect','prove','provide',
    'publish','pursue','raise','react','realise','recognise','recommend',
    'recover','refer','reflect','reject','relate','rely','remove','replace',
    'represent','resist','respond','restrict','retain','reveal','review',
    'satisfy','select','separate','suggest','supply','support','survive',
    'sustain','target','tolerate','transfer','transform','translate','treat',
    'understand','update','validate','verify','violate','withdraw','yield',
  ],

  // ── Additional Oxford 5000 nouns ──────────────────────────────
  nouns: [
    'access','achievement','action','adjustment','advantage','agenda','analysis',
    'approach','argument','aspect','assessment','assumption','atmosphere',
    'attempt','attitude','authority','awareness','background','behaviour',
    'belief','benefit','capacity','category','challenge','channel','charge',
    'choice','circumstance','claim','climate','colleague','commitment',
    'competition','complaint','complexity','component','concept','conclusion',
    'conflict','connection','consequence','consumption','contribution','control',
    'controversy','criticism','culture','currency','decline','definition',
    'demand','description','development','distinction','distribution','domain',
    'effectiveness','efficiency','element','emotion','emphasis','encouragement',
    'error','evaluation','evidence','exception','expense','explanation',
    'exploration','failure','feature','framework','freedom','function','gap',
    'guidance','guilt','growth','identity','impact','implication','income',
    'increase','independence','indication','inequality','influence','innovation',
    'input','insight','intelligence','interaction','interest','interpretation',
    'investment','leadership','legislation','logic','loss','means','model',
    'motivation','nature','network','notion','obstacle','offence','operation',
    'opportunity','origin','outcome','output','partnership','pattern','payment',
    'penalty','perception','performance','phenomenon','potential','poverty',
    'pressure','principle','priority','procedure','proportion','provision',
    'purpose','quality','range','reality','reduction','reference','relationship',
    'relevance','reliance','requirement','resistance','responsibility','revenue',
    'scale','scope','sector','selection','sequence','significance','solution',
    'source','stability','stereotype','stress','structure','submission',
    'substance','success','summary','superiority','supply','tension','theory',
    'threat','tolerance','transition','trend','uncertainty','unity','validity',
    'variation','vulnerability','welfare','willingness',
  ],

  // ── Additional Oxford 5000 adjectives ────────────────────────
  adjectives: [
    'abstract','acceptable','accessible','accurate','adequate','alternative',
    'apparent','appropriate','arbitrary','aware','capable','certain','chronic',
    'coherent','comparable','compatible','competitive','complex','comprehensive',
    'concrete','conditional','consistent','controversial','conventional',
    'cooperative','corresponding','creative','crucial','dedicated','definite',
    'deliberate','dependent','desirable','determined','diverse','dominant',
    'eligible','enormous','equal','equivalent','essential','evident','excessive',
    'exclusive','explicit','extensive','extreme','favourable','flexible',
    'formal','fundamental','genuine','global','gradual','gradual','harmful',
    'horizontal','hostile','ideal','identical','immediate','implicit','inevitable',
    'informal','inherent','initial','innovative','integral','intense','logical',
    'minimal','minor','modest','mutual','negative','neutral','obvious','optional',
    'original','passive','particular','permanent','positive','potential',
    'practical','precise','preliminary','primary','prior','prominent','rational',
    'realistic','reasonable','relevant','reliable','rigid','robust','secondary',
    'sensitive','severe','significant','stable','straightforward','subsequent',
    'substantial','sufficient','suitable','systematic','temporary','theoretical',
    'transparent','ultimate','universal','valid','variable','vertical','virtual',
    'visible','vulnerable','widespread',
  ],

  // ── Additional Oxford 5000 adverbs / connectors ───────────────
  adverbs: [
    'accordingly','actually','additionally','alternatively','approximately',
    'broadly','carefully','clearly','collectively','consequently','considerably',
    'constantly','continuously','correctly','deliberately','directly','equally',
    'essentially','eventually','exactly','explicitly','extremely','fairly',
    'formally','frequently','fundamentally','generally','gradually','heavily',
    'highly','increasingly','independently','indirectly','inevitably','largely',
    'mainly','mostly','naturally','necessarily','notably','obviously',
    'occasionally','partially','particularly','potentially','precisely',
    'primarily','properly','rapidly','rarely','relatively','respectively',
    'roughly','seriously','significantly','simply','slightly','specifically',
    'strongly','subsequently','substantially','suddenly','surprisingly',
    'systematically','therefore','thoroughly','typically','ultimately','uniquely',
    'virtually','widely',
  ],
};

const gaps = {};
let totalMissing = 0;

Object.entries(OXFORD).forEach(([level, words]) => {
  const missing = [...new Set(words)].filter(w => !have.has(w));
  if (missing.length > 0) {
    gaps[level] = missing;
    totalMissing += missing.length;
  }
});

if (totalMissing === 0) {
  console.log('✅ No gaps found in current Oxford list!');
} else {
  Object.entries(gaps).forEach(([level, words]) => {
    console.log(`\n${level} missing (${words.length}):`);
    words.forEach(w => console.log(`  ${w}`));
  });
}

console.log(`\nTotal words in dictionary: ${W.length}`);
console.log(`Total missing: ${totalMissing}`);
