// Vymova — js/features/word-data/antonyms-loader.ts
// Lazy per-language loader for per-language antonym data (formerly data/antonyms.ts's ANTONYMS_BY_LANG), generated by
// scripts/gen-lang-loader.js (scans data/antonyms-data/) — mirrors mode-utils.ts's
// TABLES/LANG_LOADERS pattern for word data. Only the learner's actual
// language(s) get downloaded instead of every language's data eagerly (see
// docs/architecture-assessment.md p.6). Regenerate (don't hand-edit the
// loader map) after adding or removing a data/antonyms-data/antonyms_xx.ts file.
import type { AntonymEntry } from '../../../data/antonyms.ts';
import { buildSynonymReverse } from '../../../data/synonyms.ts';

const CACHE: Partial<Record<string, Record<string, AntonymEntry[]>>> = {};
const REVERSE_CACHE: Partial<Record<string, Map<string, string>>> = {};
const LOADING: Partial<Record<string, Promise<void>>> = {};

const LOADERS: Partial<Record<string, () => Promise<Record<string, AntonymEntry[]>>>> = {
  en: () =>
    import('../../../data/antonyms-data/antonyms_en.ts').then((m) => m.ANTONYMS_EN),
  ua: () =>
    import('../../../data/antonyms-data/antonyms_ua.ts').then((m) => m.ANTONYMS_UA),
};

/** Returns the cached base dict for `lang`, or undefined if not loaded (yet). */
export function getAntonymsForLang(lang: string): Record<string, AntonymEntry[]> | undefined {
  return CACHE[lang];
}

/** Returns `lang`'s reverse-lookup map (member word → headword), built lazily on first call after the base dict is loaded. Undefined if the base dict itself isn't loaded yet. */
export function getAntonymReverseForLang(lang: string): Map<string, string> | undefined {
  const dict = CACHE[lang];
  if (!dict) return undefined;
  let rev = REVERSE_CACHE[lang];
  if (!rev) {
    rev = buildSynonymReverse(dict);
    REVERSE_CACHE[lang] = rev;
  }
  return rev;
}

/** Loads (and caches) `lang`'s base dict on first call; a no-op if already loaded/loading/unavailable. */
export async function ensureAntonymsLoaded(lang: string): Promise<void> {
  if (CACHE[lang]) return;
  const loader = LOADERS[lang];
  if (!loader) return;
  if (!LOADING[lang]) {
    LOADING[lang] = loader().then((data) => {
      CACHE[lang] = data;
    });
  }
  await LOADING[lang];
}

export type { AntonymEntry } from '../../../data/antonyms.ts';
