// Vymova — js/features/word-data/grammar-loader.ts
// Lazy per-language loader for per-language grammar data (formerly data/grammar.ts's GRAMMAR_BY_LANG), generated by
// scripts/gen-lang-loader.js (scans data/grammar-data/) — mirrors mode-utils.ts's
// TABLES/LANG_LOADERS pattern for word data. Only the learner's actual
// language(s) get downloaded instead of every language's data eagerly (see
// docs/architecture-assessment.md p.6). Regenerate (don't hand-edit the
// loader map) after adding or removing a data/grammar-data/grammar_xx.ts file.
import type { GrammarCategory } from '../../../data/grammar.ts';

const CACHE: Partial<Record<string, GrammarCategory[]>> = {};
const LOADING: Partial<Record<string, Promise<void>>> = {};

const LOADERS: Partial<Record<string, () => Promise<GrammarCategory[]>>> = {
  af: () =>
    import('../../../data/grammar-data/grammar_af.ts').then((m) => m.GRAMMAR_AF),
  am: () =>
    import('../../../data/grammar-data/grammar_am.ts').then((m) => m.GRAMMAR_AM),
  ar: () =>
    import('../../../data/grammar-data/grammar_ar.ts').then((m) => m.GRAMMAR_AR),
  as: () =>
    import('../../../data/grammar-data/grammar_as.ts').then((m) => m.GRAMMAR_AS),
  ay: () =>
    import('../../../data/grammar-data/grammar_ay.ts').then((m) => m.GRAMMAR_AY),
  az: () =>
    import('../../../data/grammar-data/grammar_az.ts').then((m) => m.GRAMMAR_AZ),
  be: () =>
    import('../../../data/grammar-data/grammar_be.ts').then((m) => m.GRAMMAR_BE),
  bg: () =>
    import('../../../data/grammar-data/grammar_bg.ts').then((m) => m.GRAMMAR_BG),
  bho: () =>
    import('../../../data/grammar-data/grammar_bho.ts').then((m) => m.GRAMMAR_BHO),
  bn: () =>
    import('../../../data/grammar-data/grammar_bn.ts').then((m) => m.GRAMMAR_BN),
  bo: () =>
    import('../../../data/grammar-data/grammar_bo.ts').then((m) => m.GRAMMAR_BO),
  br: () =>
    import('../../../data/grammar-data/grammar_br.ts').then((m) => m.GRAMMAR_BR),
  bs: () =>
    import('../../../data/grammar-data/grammar_bs.ts').then((m) => m.GRAMMAR_BS),
  ca: () =>
    import('../../../data/grammar-data/grammar_ca.ts').then((m) => m.GRAMMAR_CA),
  ceb: () =>
    import('../../../data/grammar-data/grammar_ceb.ts').then((m) => m.GRAMMAR_CEB),
  ch: () =>
    import('../../../data/grammar-data/grammar_ch.ts').then((m) => m.GRAMMAR_CH),
  co: () =>
    import('../../../data/grammar-data/grammar_co.ts').then((m) => m.GRAMMAR_CO),
  cs: () =>
    import('../../../data/grammar-data/grammar_cs.ts').then((m) => m.GRAMMAR_CS),
  cy: () =>
    import('../../../data/grammar-data/grammar_cy.ts').then((m) => m.GRAMMAR_CY),
  da: () =>
    import('../../../data/grammar-data/grammar_da.ts').then((m) => m.GRAMMAR_DA),
  de: () =>
    import('../../../data/grammar-data/grammar_de.ts').then((m) => m.GRAMMAR_DE),
  dth: () =>
    import('../../../data/grammar-data/grammar_dth.ts').then((m) => m.GRAMMAR_DTH),
  dv: () =>
    import('../../../data/grammar-data/grammar_dv.ts').then((m) => m.GRAMMAR_DV),
  dz: () =>
    import('../../../data/grammar-data/grammar_dz.ts').then((m) => m.GRAMMAR_DZ),
  el: () =>
    import('../../../data/grammar-data/grammar_el.ts').then((m) => m.GRAMMAR_EL),
  en: () =>
    import('../../../data/grammar-data/grammar_en.ts').then((m) => m.GRAMMAR_EN),
  eo: () =>
    import('../../../data/grammar-data/grammar_eo.ts').then((m) => m.GRAMMAR_EO),
  es: () =>
    import('../../../data/grammar-data/grammar_es.ts').then((m) => m.GRAMMAR_ES),
  et: () =>
    import('../../../data/grammar-data/grammar_et.ts').then((m) => m.GRAMMAR_ET),
  eu: () =>
    import('../../../data/grammar-data/grammar_eu.ts').then((m) => m.GRAMMAR_EU),
  fa: () =>
    import('../../../data/grammar-data/grammar_fa.ts').then((m) => m.GRAMMAR_FA),
  fi: () =>
    import('../../../data/grammar-data/grammar_fi.ts').then((m) => m.GRAMMAR_FI),
  fj: () =>
    import('../../../data/grammar-data/grammar_fj.ts').then((m) => m.GRAMMAR_FJ),
  fo: () =>
    import('../../../data/grammar-data/grammar_fo.ts').then((m) => m.GRAMMAR_FO),
  fr: () =>
    import('../../../data/grammar-data/grammar_fr.ts').then((m) => m.GRAMMAR_FR),
  fy: () =>
    import('../../../data/grammar-data/grammar_fy.ts').then((m) => m.GRAMMAR_FY),
  ga: () =>
    import('../../../data/grammar-data/grammar_ga.ts').then((m) => m.GRAMMAR_GA),
  gd: () =>
    import('../../../data/grammar-data/grammar_gd.ts').then((m) => m.GRAMMAR_GD),
  gl: () =>
    import('../../../data/grammar-data/grammar_gl.ts').then((m) => m.GRAMMAR_GL),
  gn: () =>
    import('../../../data/grammar-data/grammar_gn.ts').then((m) => m.GRAMMAR_GN),
  gu: () =>
    import('../../../data/grammar-data/grammar_gu.ts').then((m) => m.GRAMMAR_GU),
  gv: () =>
    import('../../../data/grammar-data/grammar_gv.ts').then((m) => m.GRAMMAR_GV),
  ha: () =>
    import('../../../data/grammar-data/grammar_ha.ts').then((m) => m.GRAMMAR_HA),
  haw: () =>
    import('../../../data/grammar-data/grammar_haw.ts').then((m) => m.GRAMMAR_HAW),
  he: () =>
    import('../../../data/grammar-data/grammar_he.ts').then((m) => m.GRAMMAR_HE),
  hi: () =>
    import('../../../data/grammar-data/grammar_hi.ts').then((m) => m.GRAMMAR_HI),
  hr: () =>
    import('../../../data/grammar-data/grammar_hr.ts').then((m) => m.GRAMMAR_HR),
  ht: () =>
    import('../../../data/grammar-data/grammar_ht.ts').then((m) => m.GRAMMAR_HT),
  hu: () =>
    import('../../../data/grammar-data/grammar_hu.ts').then((m) => m.GRAMMAR_HU),
  hy: () =>
    import('../../../data/grammar-data/grammar_hy.ts').then((m) => m.GRAMMAR_HY),
  id: () =>
    import('../../../data/grammar-data/grammar_id.ts').then((m) => m.GRAMMAR_ID),
  ig: () =>
    import('../../../data/grammar-data/grammar_ig.ts').then((m) => m.GRAMMAR_IG),
  is: () =>
    import('../../../data/grammar-data/grammar_is.ts').then((m) => m.GRAMMAR_IS),
  it: () =>
    import('../../../data/grammar-data/grammar_it.ts').then((m) => m.GRAMMAR_IT),
  ja: () =>
    import('../../../data/grammar-data/grammar_ja.ts').then((m) => m.GRAMMAR_JA),
  jv: () =>
    import('../../../data/grammar-data/grammar_jv.ts').then((m) => m.GRAMMAR_JV),
  ka: () =>
    import('../../../data/grammar-data/grammar_ka.ts').then((m) => m.GRAMMAR_KA),
  kk: () =>
    import('../../../data/grammar-data/grammar_kk.ts').then((m) => m.GRAMMAR_KK),
  km: () =>
    import('../../../data/grammar-data/grammar_km.ts').then((m) => m.GRAMMAR_KM),
  kn: () =>
    import('../../../data/grammar-data/grammar_kn.ts').then((m) => m.GRAMMAR_KN),
  ko: () =>
    import('../../../data/grammar-data/grammar_ko.ts').then((m) => m.GRAMMAR_KO),
  ku: () =>
    import('../../../data/grammar-data/grammar_ku.ts').then((m) => m.GRAMMAR_KU),
  kw: () =>
    import('../../../data/grammar-data/grammar_kw.ts').then((m) => m.GRAMMAR_KW),
  ky: () =>
    import('../../../data/grammar-data/grammar_ky.ts').then((m) => m.GRAMMAR_KY),
  la: () =>
    import('../../../data/grammar-data/grammar_la.ts').then((m) => m.GRAMMAR_LA),
  lad: () =>
    import('../../../data/grammar-data/grammar_lad.ts').then((m) => m.GRAMMAR_LAD),
  lb: () =>
    import('../../../data/grammar-data/grammar_lb.ts').then((m) => m.GRAMMAR_LB),
  ln: () =>
    import('../../../data/grammar-data/grammar_ln.ts').then((m) => m.GRAMMAR_LN),
  lo: () =>
    import('../../../data/grammar-data/grammar_lo.ts').then((m) => m.GRAMMAR_LO),
  lt: () =>
    import('../../../data/grammar-data/grammar_lt.ts').then((m) => m.GRAMMAR_LT),
  lv: () =>
    import('../../../data/grammar-data/grammar_lv.ts').then((m) => m.GRAMMAR_LV),
  mg: () =>
    import('../../../data/grammar-data/grammar_mg.ts').then((m) => m.GRAMMAR_MG),
  mh: () =>
    import('../../../data/grammar-data/grammar_mh.ts').then((m) => m.GRAMMAR_MH),
  mi: () =>
    import('../../../data/grammar-data/grammar_mi.ts').then((m) => m.GRAMMAR_MI),
  mk: () =>
    import('../../../data/grammar-data/grammar_mk.ts').then((m) => m.GRAMMAR_MK),
  ml: () =>
    import('../../../data/grammar-data/grammar_ml.ts').then((m) => m.GRAMMAR_ML),
  mn: () =>
    import('../../../data/grammar-data/grammar_mn.ts').then((m) => m.GRAMMAR_MN),
  mr: () =>
    import('../../../data/grammar-data/grammar_mr.ts').then((m) => m.GRAMMAR_MR),
  ms: () =>
    import('../../../data/grammar-data/grammar_ms.ts').then((m) => m.GRAMMAR_MS),
  mt: () =>
    import('../../../data/grammar-data/grammar_mt.ts').then((m) => m.GRAMMAR_MT),
  my: () =>
    import('../../../data/grammar-data/grammar_my.ts').then((m) => m.GRAMMAR_MY),
  nah: () =>
    import('../../../data/grammar-data/grammar_nah.ts').then((m) => m.GRAMMAR_NAH),
  ne: () =>
    import('../../../data/grammar-data/grammar_ne.ts').then((m) => m.GRAMMAR_NE),
  nl: () =>
    import('../../../data/grammar-data/grammar_nl.ts').then((m) => m.GRAMMAR_NL),
  no: () =>
    import('../../../data/grammar-data/grammar_no.ts').then((m) => m.GRAMMAR_NO),
  nv: () =>
    import('../../../data/grammar-data/grammar_nv.ts').then((m) => m.GRAMMAR_NV),
  ny: () =>
    import('../../../data/grammar-data/grammar_ny.ts').then((m) => m.GRAMMAR_NY),
  oc: () =>
    import('../../../data/grammar-data/grammar_oc.ts').then((m) => m.GRAMMAR_OC),
  om: () =>
    import('../../../data/grammar-data/grammar_om.ts').then((m) => m.GRAMMAR_OM),
  or: () =>
    import('../../../data/grammar-data/grammar_or.ts').then((m) => m.GRAMMAR_OR),
  pa: () =>
    import('../../../data/grammar-data/grammar_pa.ts').then((m) => m.GRAMMAR_PA),
  pau: () =>
    import('../../../data/grammar-data/grammar_pau.ts').then((m) => m.GRAMMAR_PAU),
  pcm: () =>
    import('../../../data/grammar-data/grammar_pcm.ts').then((m) => m.GRAMMAR_PCM),
  pl: () =>
    import('../../../data/grammar-data/grammar_pl.ts').then((m) => m.GRAMMAR_PL),
  ps: () =>
    import('../../../data/grammar-data/grammar_ps.ts').then((m) => m.GRAMMAR_PS),
  pt: () =>
    import('../../../data/grammar-data/grammar_pt.ts').then((m) => m.GRAMMAR_PT),
  qu: () =>
    import('../../../data/grammar-data/grammar_qu.ts').then((m) => m.GRAMMAR_QU),
  qya: () =>
    import('../../../data/grammar-data/grammar_qya.ts').then((m) => m.GRAMMAR_QYA),
  rm: () =>
    import('../../../data/grammar-data/grammar_rm.ts').then((m) => m.GRAMMAR_RM),
  ro: () =>
    import('../../../data/grammar-data/grammar_ro.ts').then((m) => m.GRAMMAR_RO),
  sc: () =>
    import('../../../data/grammar-data/grammar_sc.ts').then((m) => m.GRAMMAR_SC),
  sd: () =>
    import('../../../data/grammar-data/grammar_sd.ts').then((m) => m.GRAMMAR_SD),
  si: () =>
    import('../../../data/grammar-data/grammar_si.ts').then((m) => m.GRAMMAR_SI),
  sjn: () =>
    import('../../../data/grammar-data/grammar_sjn.ts').then((m) => m.GRAMMAR_SJN),
  sk: () =>
    import('../../../data/grammar-data/grammar_sk.ts').then((m) => m.GRAMMAR_SK),
  sl: () =>
    import('../../../data/grammar-data/grammar_sl.ts').then((m) => m.GRAMMAR_SL),
  sm: () =>
    import('../../../data/grammar-data/grammar_sm.ts').then((m) => m.GRAMMAR_SM),
  sn: () =>
    import('../../../data/grammar-data/grammar_sn.ts').then((m) => m.GRAMMAR_SN),
  so: () =>
    import('../../../data/grammar-data/grammar_so.ts').then((m) => m.GRAMMAR_SO),
  sq: () =>
    import('../../../data/grammar-data/grammar_sq.ts').then((m) => m.GRAMMAR_SQ),
  sr: () =>
    import('../../../data/grammar-data/grammar_sr.ts').then((m) => m.GRAMMAR_SR),
  su: () =>
    import('../../../data/grammar-data/grammar_su.ts').then((m) => m.GRAMMAR_SU),
  sv: () =>
    import('../../../data/grammar-data/grammar_sv.ts').then((m) => m.GRAMMAR_SV),
  sw: () =>
    import('../../../data/grammar-data/grammar_sw.ts').then((m) => m.GRAMMAR_SW),
  ta: () =>
    import('../../../data/grammar-data/grammar_ta.ts').then((m) => m.GRAMMAR_TA),
  te: () =>
    import('../../../data/grammar-data/grammar_te.ts').then((m) => m.GRAMMAR_TE),
  tet: () =>
    import('../../../data/grammar-data/grammar_tet.ts').then((m) => m.GRAMMAR_TET),
  tg: () =>
    import('../../../data/grammar-data/grammar_tg.ts').then((m) => m.GRAMMAR_TG),
  th: () =>
    import('../../../data/grammar-data/grammar_th.ts').then((m) => m.GRAMMAR_TH),
  ti: () =>
    import('../../../data/grammar-data/grammar_ti.ts').then((m) => m.GRAMMAR_TI),
  tk: () =>
    import('../../../data/grammar-data/grammar_tk.ts').then((m) => m.GRAMMAR_TK),
  tl: () =>
    import('../../../data/grammar-data/grammar_tl.ts').then((m) => m.GRAMMAR_TL),
  tlh: () =>
    import('../../../data/grammar-data/grammar_tlh.ts').then((m) => m.GRAMMAR_TLH),
  to: () =>
    import('../../../data/grammar-data/grammar_to.ts').then((m) => m.GRAMMAR_TO),
  tr: () =>
    import('../../../data/grammar-data/grammar_tr.ts').then((m) => m.GRAMMAR_TR),
  ty: () =>
    import('../../../data/grammar-data/grammar_ty.ts').then((m) => m.GRAMMAR_TY),
  ug: () =>
    import('../../../data/grammar-data/grammar_ug.ts').then((m) => m.GRAMMAR_UG),
  ur: () =>
    import('../../../data/grammar-data/grammar_ur.ts').then((m) => m.GRAMMAR_UR),
  uz: () =>
    import('../../../data/grammar-data/grammar_uz.ts').then((m) => m.GRAMMAR_UZ),
  val: () =>
    import('../../../data/grammar-data/grammar_val.ts').then((m) => m.GRAMMAR_VAL),
  vi: () =>
    import('../../../data/grammar-data/grammar_vi.ts').then((m) => m.GRAMMAR_VI),
  wo: () =>
    import('../../../data/grammar-data/grammar_wo.ts').then((m) => m.GRAMMAR_WO),
  xh: () =>
    import('../../../data/grammar-data/grammar_xh.ts').then((m) => m.GRAMMAR_XH),
  yi: () =>
    import('../../../data/grammar-data/grammar_yi.ts').then((m) => m.GRAMMAR_YI),
  yo: () =>
    import('../../../data/grammar-data/grammar_yo.ts').then((m) => m.GRAMMAR_YO),
  zh: () =>
    import('../../../data/grammar-data/grammar_zh.ts').then((m) => m.GRAMMAR_ZH),
  zu: () =>
    import('../../../data/grammar-data/grammar_zu.ts').then((m) => m.GRAMMAR_ZU),
};

/** Returns the cached data for `lang`, or undefined if not loaded (yet). */
export function getGrammarForLang(lang: string): GrammarCategory[] | undefined {
  return CACHE[lang];
}

/** Loads (and caches) `lang`'s data on first call; a no-op if already loaded/loading/unavailable. */
export async function ensureGrammarLoaded(lang: string): Promise<void> {
  if (CACHE[lang]) return;
  const loader = LOADERS[lang];
  if (!loader) return;
  if (!LOADING[lang]) {
    LOADING[lang] = loader().then((data) => {
      CACHE[lang] = data;
    });
  }
  await LOADING[lang];
}


export type { GrammarCategory, GrammarRule, GSection } from '../../../data/grammar.ts';
