// Vymova — js/features/word-data/lang-history-loader.ts
// Lazy per-language loader for per-language history data (formerly data/lang-history.ts's LANG_HISTORY), generated by
// scripts/gen-lang-loader.js (scans data/lang-history-data/) — mirrors mode-utils.ts's
// TABLES/LANG_LOADERS pattern for word data. Only the learner's actual
// language(s) get downloaded instead of every language's data eagerly (see
// docs/architecture-assessment.md p.6). Regenerate (don't hand-edit the
// loader map) after adding or removing a data/lang-history-data/lang-history_xx.ts file.
import type { LangHistoryEntry } from '../../../data/lang-history.ts';

const CACHE: Partial<Record<string, LangHistoryEntry>> = {};
const LOADING: Partial<Record<string, Promise<void>>> = {};

const LOADERS: Partial<Record<string, () => Promise<LangHistoryEntry>>> = {
  af: () =>
    import('../../../data/lang-history-data/lang-history_af.ts').then((m) => m.LANG_HISTORY_AF),
  am: () =>
    import('../../../data/lang-history-data/lang-history_am.ts').then((m) => m.LANG_HISTORY_AM),
  ar: () =>
    import('../../../data/lang-history-data/lang-history_ar.ts').then((m) => m.LANG_HISTORY_AR),
  as: () =>
    import('../../../data/lang-history-data/lang-history_as.ts').then((m) => m.LANG_HISTORY_AS),
  ay: () =>
    import('../../../data/lang-history-data/lang-history_ay.ts').then((m) => m.LANG_HISTORY_AY),
  az: () =>
    import('../../../data/lang-history-data/lang-history_az.ts').then((m) => m.LANG_HISTORY_AZ),
  be: () =>
    import('../../../data/lang-history-data/lang-history_be.ts').then((m) => m.LANG_HISTORY_BE),
  bg: () =>
    import('../../../data/lang-history-data/lang-history_bg.ts').then((m) => m.LANG_HISTORY_BG),
  bho: () =>
    import('../../../data/lang-history-data/lang-history_bho.ts').then((m) => m.LANG_HISTORY_BHO),
  bn: () =>
    import('../../../data/lang-history-data/lang-history_bn.ts').then((m) => m.LANG_HISTORY_BN),
  bo: () =>
    import('../../../data/lang-history-data/lang-history_bo.ts').then((m) => m.LANG_HISTORY_BO),
  br: () =>
    import('../../../data/lang-history-data/lang-history_br.ts').then((m) => m.LANG_HISTORY_BR),
  bs: () =>
    import('../../../data/lang-history-data/lang-history_bs.ts').then((m) => m.LANG_HISTORY_BS),
  ca: () =>
    import('../../../data/lang-history-data/lang-history_ca.ts').then((m) => m.LANG_HISTORY_CA),
  ceb: () =>
    import('../../../data/lang-history-data/lang-history_ceb.ts').then((m) => m.LANG_HISTORY_CEB),
  ch: () =>
    import('../../../data/lang-history-data/lang-history_ch.ts').then((m) => m.LANG_HISTORY_CH),
  co: () =>
    import('../../../data/lang-history-data/lang-history_co.ts').then((m) => m.LANG_HISTORY_CO),
  cs: () =>
    import('../../../data/lang-history-data/lang-history_cs.ts').then((m) => m.LANG_HISTORY_CS),
  cy: () =>
    import('../../../data/lang-history-data/lang-history_cy.ts').then((m) => m.LANG_HISTORY_CY),
  da: () =>
    import('../../../data/lang-history-data/lang-history_da.ts').then((m) => m.LANG_HISTORY_DA),
  de: () =>
    import('../../../data/lang-history-data/lang-history_de.ts').then((m) => m.LANG_HISTORY_DE),
  dth: () =>
    import('../../../data/lang-history-data/lang-history_dth.ts').then((m) => m.LANG_HISTORY_DTH),
  dv: () =>
    import('../../../data/lang-history-data/lang-history_dv.ts').then((m) => m.LANG_HISTORY_DV),
  dz: () =>
    import('../../../data/lang-history-data/lang-history_dz.ts').then((m) => m.LANG_HISTORY_DZ),
  el: () =>
    import('../../../data/lang-history-data/lang-history_el.ts').then((m) => m.LANG_HISTORY_EL),
  en: () =>
    import('../../../data/lang-history-data/lang-history_en.ts').then((m) => m.LANG_HISTORY_EN),
  eo: () =>
    import('../../../data/lang-history-data/lang-history_eo.ts').then((m) => m.LANG_HISTORY_EO),
  es: () =>
    import('../../../data/lang-history-data/lang-history_es.ts').then((m) => m.LANG_HISTORY_ES),
  et: () =>
    import('../../../data/lang-history-data/lang-history_et.ts').then((m) => m.LANG_HISTORY_ET),
  eu: () =>
    import('../../../data/lang-history-data/lang-history_eu.ts').then((m) => m.LANG_HISTORY_EU),
  fa: () =>
    import('../../../data/lang-history-data/lang-history_fa.ts').then((m) => m.LANG_HISTORY_FA),
  fi: () =>
    import('../../../data/lang-history-data/lang-history_fi.ts').then((m) => m.LANG_HISTORY_FI),
  fj: () =>
    import('../../../data/lang-history-data/lang-history_fj.ts').then((m) => m.LANG_HISTORY_FJ),
  fo: () =>
    import('../../../data/lang-history-data/lang-history_fo.ts').then((m) => m.LANG_HISTORY_FO),
  fr: () =>
    import('../../../data/lang-history-data/lang-history_fr.ts').then((m) => m.LANG_HISTORY_FR),
  fy: () =>
    import('../../../data/lang-history-data/lang-history_fy.ts').then((m) => m.LANG_HISTORY_FY),
  ga: () =>
    import('../../../data/lang-history-data/lang-history_ga.ts').then((m) => m.LANG_HISTORY_GA),
  gd: () =>
    import('../../../data/lang-history-data/lang-history_gd.ts').then((m) => m.LANG_HISTORY_GD),
  gl: () =>
    import('../../../data/lang-history-data/lang-history_gl.ts').then((m) => m.LANG_HISTORY_GL),
  gn: () =>
    import('../../../data/lang-history-data/lang-history_gn.ts').then((m) => m.LANG_HISTORY_GN),
  gu: () =>
    import('../../../data/lang-history-data/lang-history_gu.ts').then((m) => m.LANG_HISTORY_GU),
  gv: () =>
    import('../../../data/lang-history-data/lang-history_gv.ts').then((m) => m.LANG_HISTORY_GV),
  ha: () =>
    import('../../../data/lang-history-data/lang-history_ha.ts').then((m) => m.LANG_HISTORY_HA),
  haw: () =>
    import('../../../data/lang-history-data/lang-history_haw.ts').then((m) => m.LANG_HISTORY_HAW),
  he: () =>
    import('../../../data/lang-history-data/lang-history_he.ts').then((m) => m.LANG_HISTORY_HE),
  hi: () =>
    import('../../../data/lang-history-data/lang-history_hi.ts').then((m) => m.LANG_HISTORY_HI),
  hr: () =>
    import('../../../data/lang-history-data/lang-history_hr.ts').then((m) => m.LANG_HISTORY_HR),
  ht: () =>
    import('../../../data/lang-history-data/lang-history_ht.ts').then((m) => m.LANG_HISTORY_HT),
  hu: () =>
    import('../../../data/lang-history-data/lang-history_hu.ts').then((m) => m.LANG_HISTORY_HU),
  hy: () =>
    import('../../../data/lang-history-data/lang-history_hy.ts').then((m) => m.LANG_HISTORY_HY),
  id: () =>
    import('../../../data/lang-history-data/lang-history_id.ts').then((m) => m.LANG_HISTORY_ID),
  ig: () =>
    import('../../../data/lang-history-data/lang-history_ig.ts').then((m) => m.LANG_HISTORY_IG),
  is: () =>
    import('../../../data/lang-history-data/lang-history_is.ts').then((m) => m.LANG_HISTORY_IS),
  it: () =>
    import('../../../data/lang-history-data/lang-history_it.ts').then((m) => m.LANG_HISTORY_IT),
  ja: () =>
    import('../../../data/lang-history-data/lang-history_ja.ts').then((m) => m.LANG_HISTORY_JA),
  jv: () =>
    import('../../../data/lang-history-data/lang-history_jv.ts').then((m) => m.LANG_HISTORY_JV),
  ka: () =>
    import('../../../data/lang-history-data/lang-history_ka.ts').then((m) => m.LANG_HISTORY_KA),
  kk: () =>
    import('../../../data/lang-history-data/lang-history_kk.ts').then((m) => m.LANG_HISTORY_KK),
  km: () =>
    import('../../../data/lang-history-data/lang-history_km.ts').then((m) => m.LANG_HISTORY_KM),
  kn: () =>
    import('../../../data/lang-history-data/lang-history_kn.ts').then((m) => m.LANG_HISTORY_KN),
  ko: () =>
    import('../../../data/lang-history-data/lang-history_ko.ts').then((m) => m.LANG_HISTORY_KO),
  ku: () =>
    import('../../../data/lang-history-data/lang-history_ku.ts').then((m) => m.LANG_HISTORY_KU),
  kw: () =>
    import('../../../data/lang-history-data/lang-history_kw.ts').then((m) => m.LANG_HISTORY_KW),
  ky: () =>
    import('../../../data/lang-history-data/lang-history_ky.ts').then((m) => m.LANG_HISTORY_KY),
  la: () =>
    import('../../../data/lang-history-data/lang-history_la.ts').then((m) => m.LANG_HISTORY_LA),
  lad: () =>
    import('../../../data/lang-history-data/lang-history_lad.ts').then((m) => m.LANG_HISTORY_LAD),
  lb: () =>
    import('../../../data/lang-history-data/lang-history_lb.ts').then((m) => m.LANG_HISTORY_LB),
  ln: () =>
    import('../../../data/lang-history-data/lang-history_ln.ts').then((m) => m.LANG_HISTORY_LN),
  lo: () =>
    import('../../../data/lang-history-data/lang-history_lo.ts').then((m) => m.LANG_HISTORY_LO),
  lt: () =>
    import('../../../data/lang-history-data/lang-history_lt.ts').then((m) => m.LANG_HISTORY_LT),
  lv: () =>
    import('../../../data/lang-history-data/lang-history_lv.ts').then((m) => m.LANG_HISTORY_LV),
  mg: () =>
    import('../../../data/lang-history-data/lang-history_mg.ts').then((m) => m.LANG_HISTORY_MG),
  mh: () =>
    import('../../../data/lang-history-data/lang-history_mh.ts').then((m) => m.LANG_HISTORY_MH),
  mi: () =>
    import('../../../data/lang-history-data/lang-history_mi.ts').then((m) => m.LANG_HISTORY_MI),
  mk: () =>
    import('../../../data/lang-history-data/lang-history_mk.ts').then((m) => m.LANG_HISTORY_MK),
  ml: () =>
    import('../../../data/lang-history-data/lang-history_ml.ts').then((m) => m.LANG_HISTORY_ML),
  mn: () =>
    import('../../../data/lang-history-data/lang-history_mn.ts').then((m) => m.LANG_HISTORY_MN),
  mr: () =>
    import('../../../data/lang-history-data/lang-history_mr.ts').then((m) => m.LANG_HISTORY_MR),
  ms: () =>
    import('../../../data/lang-history-data/lang-history_ms.ts').then((m) => m.LANG_HISTORY_MS),
  mt: () =>
    import('../../../data/lang-history-data/lang-history_mt.ts').then((m) => m.LANG_HISTORY_MT),
  my: () =>
    import('../../../data/lang-history-data/lang-history_my.ts').then((m) => m.LANG_HISTORY_MY),
  nah: () =>
    import('../../../data/lang-history-data/lang-history_nah.ts').then((m) => m.LANG_HISTORY_NAH),
  ne: () =>
    import('../../../data/lang-history-data/lang-history_ne.ts').then((m) => m.LANG_HISTORY_NE),
  nl: () =>
    import('../../../data/lang-history-data/lang-history_nl.ts').then((m) => m.LANG_HISTORY_NL),
  no: () =>
    import('../../../data/lang-history-data/lang-history_no.ts').then((m) => m.LANG_HISTORY_NO),
  nv: () =>
    import('../../../data/lang-history-data/lang-history_nv.ts').then((m) => m.LANG_HISTORY_NV),
  ny: () =>
    import('../../../data/lang-history-data/lang-history_ny.ts').then((m) => m.LANG_HISTORY_NY),
  oc: () =>
    import('../../../data/lang-history-data/lang-history_oc.ts').then((m) => m.LANG_HISTORY_OC),
  om: () =>
    import('../../../data/lang-history-data/lang-history_om.ts').then((m) => m.LANG_HISTORY_OM),
  or: () =>
    import('../../../data/lang-history-data/lang-history_or.ts').then((m) => m.LANG_HISTORY_OR),
  pa: () =>
    import('../../../data/lang-history-data/lang-history_pa.ts').then((m) => m.LANG_HISTORY_PA),
  pau: () =>
    import('../../../data/lang-history-data/lang-history_pau.ts').then((m) => m.LANG_HISTORY_PAU),
  pcm: () =>
    import('../../../data/lang-history-data/lang-history_pcm.ts').then((m) => m.LANG_HISTORY_PCM),
  pl: () =>
    import('../../../data/lang-history-data/lang-history_pl.ts').then((m) => m.LANG_HISTORY_PL),
  ps: () =>
    import('../../../data/lang-history-data/lang-history_ps.ts').then((m) => m.LANG_HISTORY_PS),
  pt: () =>
    import('../../../data/lang-history-data/lang-history_pt.ts').then((m) => m.LANG_HISTORY_PT),
  qu: () =>
    import('../../../data/lang-history-data/lang-history_qu.ts').then((m) => m.LANG_HISTORY_QU),
  qya: () =>
    import('../../../data/lang-history-data/lang-history_qya.ts').then((m) => m.LANG_HISTORY_QYA),
  rm: () =>
    import('../../../data/lang-history-data/lang-history_rm.ts').then((m) => m.LANG_HISTORY_RM),
  ro: () =>
    import('../../../data/lang-history-data/lang-history_ro.ts').then((m) => m.LANG_HISTORY_RO),
  sc: () =>
    import('../../../data/lang-history-data/lang-history_sc.ts').then((m) => m.LANG_HISTORY_SC),
  sd: () =>
    import('../../../data/lang-history-data/lang-history_sd.ts').then((m) => m.LANG_HISTORY_SD),
  si: () =>
    import('../../../data/lang-history-data/lang-history_si.ts').then((m) => m.LANG_HISTORY_SI),
  sjn: () =>
    import('../../../data/lang-history-data/lang-history_sjn.ts').then((m) => m.LANG_HISTORY_SJN),
  sk: () =>
    import('../../../data/lang-history-data/lang-history_sk.ts').then((m) => m.LANG_HISTORY_SK),
  sl: () =>
    import('../../../data/lang-history-data/lang-history_sl.ts').then((m) => m.LANG_HISTORY_SL),
  sm: () =>
    import('../../../data/lang-history-data/lang-history_sm.ts').then((m) => m.LANG_HISTORY_SM),
  sn: () =>
    import('../../../data/lang-history-data/lang-history_sn.ts').then((m) => m.LANG_HISTORY_SN),
  so: () =>
    import('../../../data/lang-history-data/lang-history_so.ts').then((m) => m.LANG_HISTORY_SO),
  sq: () =>
    import('../../../data/lang-history-data/lang-history_sq.ts').then((m) => m.LANG_HISTORY_SQ),
  sr: () =>
    import('../../../data/lang-history-data/lang-history_sr.ts').then((m) => m.LANG_HISTORY_SR),
  su: () =>
    import('../../../data/lang-history-data/lang-history_su.ts').then((m) => m.LANG_HISTORY_SU),
  sv: () =>
    import('../../../data/lang-history-data/lang-history_sv.ts').then((m) => m.LANG_HISTORY_SV),
  sw: () =>
    import('../../../data/lang-history-data/lang-history_sw.ts').then((m) => m.LANG_HISTORY_SW),
  ta: () =>
    import('../../../data/lang-history-data/lang-history_ta.ts').then((m) => m.LANG_HISTORY_TA),
  te: () =>
    import('../../../data/lang-history-data/lang-history_te.ts').then((m) => m.LANG_HISTORY_TE),
  tet: () =>
    import('../../../data/lang-history-data/lang-history_tet.ts').then((m) => m.LANG_HISTORY_TET),
  tg: () =>
    import('../../../data/lang-history-data/lang-history_tg.ts').then((m) => m.LANG_HISTORY_TG),
  th: () =>
    import('../../../data/lang-history-data/lang-history_th.ts').then((m) => m.LANG_HISTORY_TH),
  ti: () =>
    import('../../../data/lang-history-data/lang-history_ti.ts').then((m) => m.LANG_HISTORY_TI),
  tk: () =>
    import('../../../data/lang-history-data/lang-history_tk.ts').then((m) => m.LANG_HISTORY_TK),
  tl: () =>
    import('../../../data/lang-history-data/lang-history_tl.ts').then((m) => m.LANG_HISTORY_TL),
  tlh: () =>
    import('../../../data/lang-history-data/lang-history_tlh.ts').then((m) => m.LANG_HISTORY_TLH),
  to: () =>
    import('../../../data/lang-history-data/lang-history_to.ts').then((m) => m.LANG_HISTORY_TO),
  tr: () =>
    import('../../../data/lang-history-data/lang-history_tr.ts').then((m) => m.LANG_HISTORY_TR),
  ty: () =>
    import('../../../data/lang-history-data/lang-history_ty.ts').then((m) => m.LANG_HISTORY_TY),
  ua: () =>
    import('../../../data/lang-history-data/lang-history_ua.ts').then((m) => m.LANG_HISTORY_UA),
  ug: () =>
    import('../../../data/lang-history-data/lang-history_ug.ts').then((m) => m.LANG_HISTORY_UG),
  ur: () =>
    import('../../../data/lang-history-data/lang-history_ur.ts').then((m) => m.LANG_HISTORY_UR),
  uz: () =>
    import('../../../data/lang-history-data/lang-history_uz.ts').then((m) => m.LANG_HISTORY_UZ),
  val: () =>
    import('../../../data/lang-history-data/lang-history_val.ts').then((m) => m.LANG_HISTORY_VAL),
  vi: () =>
    import('../../../data/lang-history-data/lang-history_vi.ts').then((m) => m.LANG_HISTORY_VI),
  wo: () =>
    import('../../../data/lang-history-data/lang-history_wo.ts').then((m) => m.LANG_HISTORY_WO),
  xh: () =>
    import('../../../data/lang-history-data/lang-history_xh.ts').then((m) => m.LANG_HISTORY_XH),
  yi: () =>
    import('../../../data/lang-history-data/lang-history_yi.ts').then((m) => m.LANG_HISTORY_YI),
  yo: () =>
    import('../../../data/lang-history-data/lang-history_yo.ts').then((m) => m.LANG_HISTORY_YO),
  zh: () =>
    import('../../../data/lang-history-data/lang-history_zh.ts').then((m) => m.LANG_HISTORY_ZH),
  zu: () =>
    import('../../../data/lang-history-data/lang-history_zu.ts').then((m) => m.LANG_HISTORY_ZU),
};

/** Returns the cached data for `lang`, or undefined if not loaded (yet). */
export function getLangHistoryForLang(lang: string): LangHistoryEntry | undefined {
  return CACHE[lang];
}

/** Loads (and caches) `lang`'s data on first call; a no-op if already loaded/loading/unavailable. */
export async function ensureLangHistoryLoaded(lang: string): Promise<void> {
  if (CACHE[lang]) return;
  const loader = LOADERS[lang];
  if (!loader) return;
  if (!LOADING[lang]) {
    LOADING[lang] = loader().then((data) => {
      CACHE[lang] = data;
    });
  }
  await LOADING[lang];
}


export type { LangHistoryEntry } from '../../../data/lang-history.ts';
