// Vymova — js/features/word-data/senses-loader.ts
// Lazy per-language loader for per-language sense data (formerly data/senses.ts's SENSES_BY_LANG), generated by
// scripts/gen-lang-loader.js (scans data/senses-data/) — mirrors mode-utils.ts's
// TABLES/LANG_LOADERS pattern for word data. Only the learner's actual
// language(s) get downloaded instead of every language's data eagerly (see
// docs/architecture-assessment.md p.6). Regenerate (don't hand-edit the
// loader map) after adding or removing a data/senses-data/senses_xx.ts file.
import type { SenseEntry } from '../../../data/senses.ts';

const CACHE: Partial<Record<string, Record<string, SenseEntry[]>>> = {};
const LOADING: Partial<Record<string, Promise<void>>> = {};

const LOADERS: Partial<Record<string, () => Promise<Record<string, SenseEntry[]>>>> = {
  de: () =>
    import('../../../data/senses-data/senses_de.ts').then((m) => m.SENSES_DE),
  el: () =>
    import('../../../data/senses-data/senses_el.ts').then((m) => m.SENSES_EL),
  en: () =>
    import('../../../data/senses-data/senses_en.ts').then((m) => m.SENSES_EN),
  es: () =>
    import('../../../data/senses-data/senses_es.ts').then((m) => m.SENSES_ES),
  fr: () =>
    import('../../../data/senses-data/senses_fr.ts').then((m) => m.SENSES_FR),
  he: () =>
    import('../../../data/senses-data/senses_he.ts').then((m) => m.SENSES_HE),
  it: () =>
    import('../../../data/senses-data/senses_it.ts').then((m) => m.SENSES_IT),
  nl: () =>
    import('../../../data/senses-data/senses_nl.ts').then((m) => m.SENSES_NL),
  pl: () =>
    import('../../../data/senses-data/senses_pl.ts').then((m) => m.SENSES_PL),
  pt: () =>
    import('../../../data/senses-data/senses_pt.ts').then((m) => m.SENSES_PT),
  tr: () =>
    import('../../../data/senses-data/senses_tr.ts').then((m) => m.SENSES_TR),
  ua: () =>
    import('../../../data/senses-data/senses_ua.ts').then((m) => m.SENSES_UA),
};

/** Returns the cached data for `lang`, or undefined if not loaded (yet). */
export function getSensesForLang(lang: string): Record<string, SenseEntry[]> | undefined {
  return CACHE[lang];
}

/** Loads (and caches) `lang`'s data on first call; a no-op if already loaded/loading/unavailable. */
export async function ensureSensesLoaded(lang: string): Promise<void> {
  if (CACHE[lang]) return;
  const loader = LOADERS[lang];
  if (!loader) return;
  if (!LOADING[lang]) {
    LOADING[lang] = loader().then((data) => {
      CACHE[lang] = data;
    });
  }
  await LOADING[lang];
}


export type { SenseEntry } from '../../../data/senses.ts';
