// Vymova — js/features/word-data/word-families-loader.ts
// Lazy per-language loader for per-language word-family data (formerly data/word-families.ts's WORD_FAMILIES_BY_LANG), generated by
// scripts/gen-lang-loader.js (scans data/word-families-data/) — mirrors mode-utils.ts's
// TABLES/LANG_LOADERS pattern for word data. Only the learner's actual
// language(s) get downloaded instead of every language's data eagerly (see
// docs/architecture-assessment.md p.6). Regenerate (don't hand-edit the
// loader map) after adding or removing a data/word-families-data/word-families_xx.ts file.

import { buildFamilyReverse } from '../../../data/word-families.ts';

const CACHE: Partial<Record<string, Record<string, string[]>>> = {};
const REVERSE_CACHE: Partial<Record<string, Map<string, string>>> = {};
const LOADING: Partial<Record<string, Promise<void>>> = {};

const LOADERS: Partial<Record<string, () => Promise<Record<string, string[]>>>> = {
  ar: () =>
    import('../../../data/word-families-data/word-families_ar.ts').then((m) => m.WORD_FAMILIES_AR),
  de: () =>
    import('../../../data/word-families-data/word-families_de.ts').then((m) => m.WORD_FAMILIES_DE),
  el: () =>
    import('../../../data/word-families-data/word-families_el.ts').then((m) => m.WORD_FAMILIES_EL),
  en: () =>
    import('../../../data/word-families-data/word-families_en.ts').then((m) => m.WORD_FAMILIES_EN),
  es: () =>
    import('../../../data/word-families-data/word-families_es.ts').then((m) => m.WORD_FAMILIES_ES),
  fr: () =>
    import('../../../data/word-families-data/word-families_fr.ts').then((m) => m.WORD_FAMILIES_FR),
  he: () =>
    import('../../../data/word-families-data/word-families_he.ts').then((m) => m.WORD_FAMILIES_HE),
  it: () =>
    import('../../../data/word-families-data/word-families_it.ts').then((m) => m.WORD_FAMILIES_IT),
  ja: () =>
    import('../../../data/word-families-data/word-families_ja.ts').then((m) => m.WORD_FAMILIES_JA),
  nl: () =>
    import('../../../data/word-families-data/word-families_nl.ts').then((m) => m.WORD_FAMILIES_NL),
  pl: () =>
    import('../../../data/word-families-data/word-families_pl.ts').then((m) => m.WORD_FAMILIES_PL),
  pt: () =>
    import('../../../data/word-families-data/word-families_pt.ts').then((m) => m.WORD_FAMILIES_PT),
  tr: () =>
    import('../../../data/word-families-data/word-families_tr.ts').then((m) => m.WORD_FAMILIES_TR),
  ua: () =>
    import('../../../data/word-families-data/word-families_ua.ts').then((m) => m.WORD_FAMILIES_UA),
  zh: () =>
    import('../../../data/word-families-data/word-families_zh.ts').then((m) => m.WORD_FAMILIES_ZH),
};

/** Returns the cached base dict for `lang`, or undefined if not loaded (yet). */
export function getWordFamiliesForLang(lang: string): Record<string, string[]> | undefined {
  return CACHE[lang];
}

/** Returns `lang`'s reverse-lookup map (member word → headword), built lazily on first call after the base dict is loaded. Undefined if the base dict itself isn't loaded yet. */
export function getWordFamilyReverseForLang(lang: string): Map<string, string> | undefined {
  const dict = CACHE[lang];
  if (!dict) return undefined;
  let rev = REVERSE_CACHE[lang];
  if (!rev) {
    rev = buildFamilyReverse(dict);
    REVERSE_CACHE[lang] = rev;
  }
  return rev;
}

/** Loads (and caches) `lang`'s base dict on first call; a no-op if already loaded/loading/unavailable. */
export async function ensureWordFamiliesLoaded(lang: string): Promise<void> {
  if (CACHE[lang]) return;
  const loader = LOADERS[lang];
  if (!loader) return;
  if (!LOADING[lang]) {
    LOADING[lang] = loader().then((data) => {
      CACHE[lang] = data;
    });
  }
  await LOADING[lang];
}
