/**
 * Vymova — src/state.ts
 * Centralized mutable app state (Phase 3: TypeScript).
 */

import type { AppState } from './types.js';

export const state: AppState = {
  duelSel: {
    mode:            'quiz',
    category:        '',
    difficulty:      'mixed',
    bestOf:          1,
    maxHints:        3,
    powerupsEnabled: true,
    lang:            localStorage.getItem('ew_learn_lang') ?? 'en',
    knowLang:        localStorage.getItem('ew_know_lang') ?? 'ua',
  },
  duelResumeSessions: [],
  duelChatHistory: [],
  duelSpecRoom: null,
  duelTournView: null,
  duelQuestion: {
    feedbackHtml:     '',
    speedText:        '',
    qPrimary:         '',
    qSecondary:       '',
    qTertiary:        '',
    choiceOptions:    [],
    choiceAnswer:     '',
    chosenOption:     null,
    hintNote:         null,
    writeInputValue:  '',
    inputBorderColor: '',
    waitingFinish:    false,
    showNextBtn:      false,
  },
  duelRoom: {
    roomId:           '',
    mySlot:           'p1',
    quizDeck:         [],
    quizIdx:          0,
    myScore:          0,
    myCorrect:        0,
    myWrong:          0,
    myFlags:          [],
    answered:         false,
    mode:             'quiz',
    finished:         false,
    myDone:           false,
    hintsLeft:        3,
    series:           { p1wins: 0, p2wins: 0, round: 1 },
    bestOf:           1,
    answerStartMs:    0,
    myPowerups:       { double: 1, skip: 1, freeze: 1 },
    doubleActive:     false,
    powerupsEnabled:  false,
    isAsyncChallenge: false,
    oppName:          '',
    oppAvatar:        '',
    oppScore:         0,
    oppIdx:           0,
    oppFlags:         [],
    roomCreatedAt:    0,
    roomSeed:         0,
    roomCategory:     '',
    roomDifficulty:   'mixed',
    roomMaxHints:     3,
    roomLang:         'en',
    roomKnowLang:     'ua',
  },
  duelScreen: 'lobby',
  duelCountdownNum: 3,
  duelResult: null,
  duelTempo: { visible: false, num: 4 },
  duelLobbyUI: {
    msg: { visible: false, text: '', challenge: null },
    waiting: { visible: false, roomCode: '', modeLabel: '' },
    joinRowVisible: true,
    createBtn: { disabled: false },
    joinBtn: { disabled: false },
    asyncBtn: { disabled: false },
    tournBtn4: { disabled: false, errorLabel: null },
    tournBtn8: { disabled: false, errorLabel: null },
  },
};
